# Local RAG, end to end — Ollama + FAISS

Everything in this notebook runs **on your laptop**. No API keys, no cloud, no bill.

By the end you will have built a question-answering system over 13 novels, watched it
give a **confident, cited, completely wrong answer**, worked out why, and fixed it.

## The pipeline we are building

```
                                  ┌─────────────────────────────────┐
                                  │  13 novels  (~1.9M words)       │  Part 2
                                  └────────────────┬────────────────┘
                                                   │  split into 300-word
                                                   ▼  windows, 60-word overlap
                                  ┌─────────────────────────────────┐
                                  │  8,509 chunks                   │  Part 3
                                  └────────────────┬────────────────┘
                                                   │  embeddinggemma
                                                   ▼  768-dim vectors
                                  ┌─────────────────────────────────┐
                                  │  FAISS index (cosine)           │  Part 4
                                  └────────────────┬────────────────┘
                                                   │
   ┌─────────────┐   embed        ┌────────────────▼────────────────┐
   │  question   ├───────────────▶│  top-k nearest chunks           │  Part 5
   └─────────────┘                └────────────────┬────────────────┘
                                                   │
                                  ┌────────────────▼────────────────┐
                                  │  !! this is where it breaks !!  │  Part 6
                                  └────────────────┬────────────────┘
                                                   │  pull in each hit's
                                                   ▼  neighbouring chunks
                                  ┌─────────────────────────────────┐
                                  │  windowed context               │  Part 7
                                  └────────────────┬────────────────┘
                                                   │
                                  ┌────────────────▼────────────────┐
                                  │  LLM answers, with citations    │  Part 8
                                  └────────────────┬────────────────┘
                                                   │
                                  ┌────────────────▼────────────────┐
                                  │  measure it / ship it (Flask)   │  Part 9-10
                                  └─────────────────────────────────┘
```

## Map

| Part | What |
|---|---|
| 0 | Setup — Ollama, dependencies |
| 1 | Embeddings: turning text into vectors |
| 2 | The corpus: 13 public-domain novels |
| 3 | Chunking: 300-word windows |
| 4 | Embedding everything + the FAISS index |
| 5 | Retrieval: top-k nearest neighbours |
| 6 | **Where it breaks** — the best match is not the answer |
| 7 | Windowed retrieval: the fix |
| 8 | Generation: grounded answers with citations |
| 9 | Measuring retrieval instead of trusting it |
| 10 | Shipping it as a web app |

## Before you start

In a terminal:

```bash
ollama list                      # what you already have
ollama pull embeddinggemma       # embedding model  (~600 MB)
ollama pull llama3.1:8b          # generator        (~4.9 GB)
ollama pull qwen3.5:9b           # second generator, for Part 8
```

---
# Part 0 — Setup

```
[ P0 ]  P1   P2   P3   P4   P5   P6   P7   P8   P9   P10
 ^^^^
```

In [1]:
# Everything this notebook needs. Safe to re-run.
%pip -q install ollama faiss-cpu numpy pandas tqdm requests truststore ipython-autotime flask

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [2]:
# autotime prints the wall-clock time under every cell from here on.
# Useful here: you can see exactly which steps are expensive.
%load_ext autotime

import textwrap


def pretty_print(*args):
    """print(), but wrapped to 80 columns so long model output stays readable."""
    text = " ".join(str(a) for a in args)
    print(textwrap.fill(text, width=80))

time: 189 µs (started: 2026-08-29 18:14:00 +05:30)

## Talking to Ollama

[Ollama](https://ollama.com) runs models locally and exposes an HTTP API on
`http://localhost:11434`. The `ollama` Python package wraps that API.

There are two ways to call it:

```python
import ollama

# (1) module-level helper — reads proxy environment variables
ollama.chat(model="llama3.1:8b", messages=[...])

# (2) explicit Client — pins the host, ignores proxy environment variables
client = ollama.Client(host="http://localhost:11434", trust_env=False)
client.chat(model="llama3.1:8b", messages=[...])
```

**We always use (2), and the reason is `trust_env=False`.**

When a VPN or corporate proxy is active, `HTTP_PROXY` / `HTTPS_PROXY` / `ALL_PROXY`
are set globally. The default client is built on `httpx`, which honours those
variables — so it tries to route your `localhost:11434` request *through the VPN*.
The proxy has no idea what your local Ollama is, and the call fails.

`trust_env=False` tells `httpx` to ignore those variables, so the request goes
straight to localhost. On a machine with no VPN both forms work; on a machine with
one, only the second does. Use the second and never think about it again.

In [3]:
import ollama

client = ollama.Client(host="http://localhost:11434", trust_env=False)

# Which models are actually available? If this errors, Ollama isn't running.
available = [m["model"] for m in client.list()["models"]]
pretty_print("Installed:", ", ".join(sorted(available)))

for needed in ["embeddinggemma:latest", "llama3.1:8b"]:
    mark = "OK  " if needed in available else "MISSING -> ollama pull"
    print(f"  {mark} {needed}")

Installed: embeddinggemma:latest, gemma3:1b, gemma3:27b, gemma3:4b, gemma3n:e4b,
gpt-oss:120b, gpt-oss:20b, llama3.1:8b, nomic-embed-text:latest,
qwen3-embedding:8b, qwen3.5:9b, tinyllama:latest
  OK   embeddinggemma:latest
  OK   llama3.1:8b
time: 337 ms (started: 2026-08-29 18:14:00 +05:30)

## The question this whole notebook is about

Before we build anything, let's ask a small local model a question **with no retrieval
at all** — just whatever it memorised during training.

The question is the title mystery of one of the Sherlock Holmes stories, and it is the
question we will follow all the way through this notebook.

Watch the answer carefully. It may well be right — the story is famous. The point is that
**you have no way to tell**, because there is nothing to check it against.

In [4]:
QUESTION = "What was the speckled band?"

resp = client.chat(
    model="llama3.1:8b",
    messages=[{"role": "user", "content": QUESTION}],
    options={"temperature": 0.0, "num_predict": 200},
)

pretty_print("Q:", QUESTION)
print()
pretty_print("A:", resp["message"]["content"].strip())
print()
pretty_print("(no sources, no passages, no way to check it — hold that thought)")

Q: What was the speckled band?

A: A classic mystery!  The Speckled Band is a short story by Sir Arthur Conan
Doyle, first published in 1892. It is one of the most famous stories in the
Sherlock Holmes canon and is considered one of the greatest detective stories of
all time.  The story revolves around the mysterious death of Helen Stoner, a
young woman who is the sister of a woman named Julia Stoner. Julia had died
under suspicious circumstances a year earlier, and Helen has come to consult
Sherlock Holmes about her own life being threatened.  Helen tells Holmes that
her sister Julia had died after a terrifying experience, in which she had been
awakened in the middle of the night by a strange, whistling sound, followed by a
sudden and inexplicable death. Helen believes that her own life is in danger, as
she has heard the same whistling sound and has reason to believe that her own
death is being planned.  Holmes agrees to investigate and, with the help of Dr.
John Watson, sets out

(no sources, no passages, no way to check it — hold that thought)
time: 3.48 s (started: 2026-08-29 18:14:01 +05:30)

---
# Part 1 — Embeddings: text as vectors

```
 P0  [ P1 ]  P2   P3   P4   P5   P6   P7   P8   P9   P10
      ^^^^
```

An **embedding model** maps a piece of text to a fixed-length list of numbers such that
texts that *mean* similar things land close together.

"Close together" is measured with **cosine similarity** — the cosine of the angle between
two vectors, from -1 (opposite) through 0 (unrelated) to 1 (identical direction).

If we first scale every vector to length 1 (**L2-normalise**), then cosine similarity is
just the dot product. That is a single, very fast instruction — which is exactly why we
normalise before putting anything into FAISS.

In [5]:
import numpy as np

EMBED_MODEL = "embeddinggemma:latest"

resp = client.embeddings(model=EMBED_MODEL, prompt="The quick brown fox jumps over the lazy dog.")
vec = np.asarray(resp["embedding"], dtype="float32")

pretty_print("Model:    ", EMBED_MODEL)
pretty_print("Dimension:", vec.shape)             # 768 for embeddinggemma
pretty_print("First 8:  ", np.round(vec[:8], 4).tolist())
pretty_print("L2 norm:  ", round(float(np.linalg.norm(vec)), 6))

Model:     embeddinggemma:latest
Dimension: (768,)
First 8:   [-0.11029999703168869, 0.05389999970793724, 0.06880000233650208,
-0.022299999371170998, -0.08060000091791153, 0.00419999985024333,
0.03519999980926514, 0.051600001752376556]
L2 norm:   1.0
time: 111 ms (started: 2026-08-29 18:14:04 +05:30)

In [6]:
# Does "similar meaning" really mean "close vector"? Let's check.

def embed_text(text: str) -> np.ndarray:
    """Embed one string and scale it to unit length, so dot product == cosine."""
    v = np.asarray(
        client.embeddings(model=EMBED_MODEL, prompt=text)["embedding"],
        dtype="float32",
    )
    return v / (np.linalg.norm(v) + 1e-12)


a = embed_text("A dog chases a cat in the garden.")
b = embed_text("In the yard, a puppy is running after a kitten.")
c = embed_text("The Fourier transform decomposes a signal into frequencies.")

print(f"cos(a, b)  same idea, no shared words = {float(a @ b):.3f}")
print(f"cos(a, c)  unrelated                   = {float(a @ c):.3f}")

cos(a, b)  same idea, no shared words = 0.787
cos(a, c)  unrelated                   = 0.217
time: 161 ms (started: 2026-08-29 18:14:04 +05:30)

## One detail that is easy to miss: task prefixes

EmbeddingGemma was trained with **instruction prefixes**. The model card asks you to wrap
text differently depending on whether it is a stored document or an incoming search query:

| role | format |
|---|---|
| document | `title: {title} \| text: {content}` |
| query | `task: search result \| query: {content}` |

This is called an **asymmetric** embedding model: a question and the passage that answers
it do not look alike, so the model is told which side it is embedding.

Run the next cell and notice something uncomfortable: on this pair the prefixed score is
**lower** than the unprefixed one.

That is not a bug, and it is worth sitting with for a moment:

> **The absolute cosine value is not a quality score.** Only the *ordering* it induces over
> your corpus matters. Two different formats produce two different number lines, and you
> cannot compare a score on one to a score on the other.

We use the prefixes because the model card specifies them. We judge whether they helped in
**Part 9**, by measuring retrieval, not by admiring a similarity number. And in **Part 7** we
throw out a tempting piece of logic that makes exactly this mistake — comparing a score to a
fixed threshold as if 0.35 meant something universal.

In [7]:
question = "Where does Sherlock Holmes live?"
passage  = ("I had called upon my friend Sherlock Holmes at his rooms in Baker Street, "
            "where he was deep in a chemical investigation.")

plain    = float(embed_text(question) @ embed_text(passage))
prefixed = float(
    embed_text(f"task: search result | query: {question}")
    @ embed_text(f"title: Adventures of Sherlock Holmes | text: {passage}")
)

print(f"no prefixes    {plain:.3f}")
print(f"with prefixes  {prefixed:.3f}")

no prefixes    0.529
with prefixes  0.484
time: 215 ms (started: 2026-08-29 18:14:05 +05:30)

---
# Part 2 — The corpus

```
 P0   P1  [ P2 ]  P3   P4   P5   P6   P7   P8   P9   P10
           ^^^^
```

Thirteen public-domain novels from Project Gutenberg — about 1.9 million words. Big enough
that retrieval is a real problem, small enough to index during a coffee break.

Each download is ~2-3 seconds. If you are behind a VPN and the downloads hang, copy the
pre-stripped copies from `corpus_jupyter_bkp/` into `corpus_jupyter/` and re-run.

In [ ]:
# ── Configuration — everything tunable lives here ────────────────────────
EMBED_MODEL     = "embeddinggemma:latest"
GEN_MODEL       = "llama3.1:8b"      # Part 8 swaps this out; one line to change

WORDS_PER_CHUNK = 300
OVERLAP_WORDS   = 60
TOPK            = 5

CORPUS_DIR    = "corpus_jupyter"
ARTIFACTS_DIR = "rag_artifacts"

GUTENBERG_BOOKS = {
    "Moby-Dick":                     "https://www.gutenberg.org/files/2701/2701-0.txt",
    "Pride and Prejudice":           "https://www.gutenberg.org/files/1342/1342-0.txt",
    "Frankenstein":                  "https://www.gutenberg.org/files/84/84-0.txt",
    "Alice in Wonderland":           "https://www.gutenberg.org/cache/epub/11/pg11.txt",
    "Dracula":                       "https://www.gutenberg.org/files/345/345-0.txt",
    "A Tale of Two Cities":          "https://www.gutenberg.org/files/98/98-0.txt",
    "The Great Gatsby":              "https://www.gutenberg.org/cache/epub/64317/pg64317.txt",
    "Adventures of Sherlock Holmes": "https://www.gutenberg.org/files/1661/1661-0.txt",
    "War and Peace":                 "https://www.gutenberg.org/files/2600/2600-0.txt",
    "Jane Eyre":                     "https://www.gutenberg.org/files/1260/1260-0.txt",
    "The Picture of Dorian Gray":    "https://www.gutenberg.org/files/174/174-0.txt",
    "Crime and Punishment":          "https://www.gutenberg.org/files/2554/2554-0.txt",
    "Wuthering Heights":             "https://www.gutenberg.org/files/768/768-0.txt",
}

time: 415 µs (started: 2026-08-29 18:14:05 +05:30)

In [9]:
import re
from pathlib import Path

import pandas as pd
import requests
import truststore
from tqdm import tqdm

truststore.inject_into_ssl()   # use the OS certificate store (corporate MITM proxies)

# Gutenberg wraps each book in a licence header and footer. Strip them.
START_MARK = re.compile(r"\*\*\* START OF (THIS|THE) PROJECT GUTENBERG EBOOK .* \*\*\*", re.I)
END_MARK   = re.compile(r"\*\*\* END OF (THIS|THE) PROJECT GUTENBERG EBOOK .* \*\*\*", re.I)

Path(CORPUS_DIR).mkdir(parents=True, exist_ok=True)

docs = []
for title, url in GUTENBERG_BOOKS.items():
    out_path = Path(CORPUS_DIR) / f"{title.replace(' ', '_')}.txt"

    if not out_path.exists():
        try:
            raw = requests.get(url, timeout=60)
            raw.raise_for_status()
            text = raw.text
            start, end = START_MARK.search(text), END_MARK.search(text)
            if start and end and end.start() > start.end():
                text = text[start.end():end.start()]
            out_path.write_text(text.strip(), encoding="utf-8")
            print(f"  downloaded  {title}")
        except Exception as e:
            print(f"  FAILED      {title}: {e}")
            continue

    docs.append({
        "title": title,
        "text":  out_path.read_text(encoding="utf-8", errors="ignore"),
        "path":  str(out_path),
    })

print(f"\n{len(docs)} books loaded")

13 books loaded
time: 331 ms (started: 2026-08-29 18:14:05 +05:30)

In [10]:
pd.DataFrame([
    {"title": d["title"], "words": len(d["text"].split())}
    for d in docs
]).sort_values("words", ascending=False).reset_index(drop=True)

                            title   words
0                   War and Peace  563286
1                       Moby-Dick  212796
2            Crime and Punishment  203505
3                       Jane Eyre  185390
4                         Dracula  161321
5            A Tale of Two Cities  135886
6             Pride and Prejudice  127360
7               Wuthering Heights  115945
8   Adventures of Sherlock Holmes  107562
9      The Picture of Dorian Gray   78979
10                   Frankenstein   75042
11               The Great Gatsby   48208
12            Alice in Wonderland   26525

time: 67.8 ms (started: 2026-08-29 18:14:05 +05:30)

---
# Part 3 — Chunking

```
 P0   P1   P2  [ P3 ]  P4   P5   P6   P7   P8   P9   P10
                ^^^^
```

We cannot embed a whole novel as one vector — a single 768-dim vector cannot represent
200,000 words, and we could not fit the result in a prompt anyway. So we cut each book into
**chunks** and embed those.

Two knobs:

- **`WORDS_PER_CHUNK = 300`** — big enough to hold a complete idea, small enough that a
  handful fit in a prompt.
- **`OVERLAP_WORDS = 60`** — consecutive chunks share their last/first 60 words, so a
  sentence that straddles a boundary still appears whole somewhere.

```
words:  |------------------ 300 ------------------|
chunk 0 |------------------------------------------|
chunk 1                          |------------------------------------------|
                                 |<-- 60 -->|
                                   overlap        step = 300 - 60 = 240
```

Overlap is insurance against a bad cut. It is **not** a substitute for the neighbour
expansion we build in Part 7 — Part 6 shows exactly why.

In [11]:
chunks = []          # each: id, title, text, preview, source_path, chunk_index
step = WORDS_PER_CHUNK - OVERLAP_WORDS

for d in docs:
    words = d["text"].split()
    chunk_index = 0
    for i in range(0, len(words), step):
        segment = words[i:i + WORDS_PER_CHUNK]
        if len(segment) < 75:        # drop the runt at the end of a book
            break
        text = " ".join(segment)
        chunks.append({
            "id":          f"{d['title'].replace(' ', '_')}#chunk{chunk_index}",
            "title":       d["title"],
            "text":        text,
            "preview":     text[:400],
            "source_path": d["path"],
            "chunk_index": chunk_index,
        })
        chunk_index += 1

print(f"{len(chunks)} chunks from {len(docs)} books")
print(f"average {np.mean([len(c['text'].split()) for c in chunks]):.0f} words per chunk")

8509 chunks from 13 books

average 300 words per chunk
time: 193 ms (started: 2026-08-29 18:14:05 +05:30)

In [12]:
# What does the overlap actually look like? Last 12 words of one chunk,
# first 12 of the next — they should be the same text.
a, b = chunks[10], chunks[11]
pretty_print("chunk 10 ends:  ...", " ".join(a["text"].split()[-12:]))
pretty_print("chunk 11 starts:   ", " ".join(b["text"].split()[:12]), "...")

chunk 10 ends:  ... are whale and sturgeon. And these, when either thrown ashore
or caught
chunk 11 starts:    the Nantucket Whale-Fishery_. “Spain—a great whale stranded
on the shores of Europe.” ...
time: 340 µs (started: 2026-08-29 18:14:05 +05:30)

---
# Part 4 — Embedding everything, and the FAISS index

```
 P0   P1   P2   P3  [ P4 ]  P5   P6   P7   P8   P9   P10
                     ^^^^
```

Now the expensive step: 8,509 chunks through the embedding model.

**This takes about 5-6 minutes** on an M-series Mac with 6 parallel workers (measured:
~26 chunks/second on real prose). Two things make it survivable:

- **Threads.** Each call is network-bound on `localhost`, so threads help even though
  Python has a GIL. 6 workers took it from ~68 ms to ~18 ms per chunk. Beyond 6 the
  Ollama server itself becomes the bottleneck — 12 workers measured no faster.
- **Retries.** One dropped connection at chunk 6,000 should not cost you the whole run.

Note we submit `title: … | text: …` — the document-side prefix from Part 1.

In [13]:
import time
from concurrent.futures import ThreadPoolExecutor

MAX_WORKERS = 6
RETRIES     = 3


def embed_text(text: str) -> np.ndarray:
    """Embed one string, unit-normalised, with retries. Used everywhere below."""
    for attempt in range(RETRIES):
        try:
            v = np.asarray(
                client.embeddings(model=EMBED_MODEL, prompt=text)["embedding"],
                dtype="float32",
            )
            return v / (np.linalg.norm(v) + 1e-12)
        except Exception:
            if attempt == RETRIES - 1:
                raise
            time.sleep(0.6 * (attempt + 1))

time: 359 µs (started: 2026-08-29 18:14:05 +05:30)

In [14]:
# ~5-6 minutes for 8,509 chunks. Good moment for a break.
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
    emb_vectors = list(tqdm(
        pool.map(lambda c: embed_text(f'title: {c["title"]} | text: {c["text"]}'), chunks),
        total=len(chunks),
        desc=f"embedding ({EMBED_MODEL})",
    ))

emb = np.vstack(emb_vectors)
print("embeddings:", emb.shape)

embedding (embeddinggemma:latest):   0%|          | 0/8509 [00:00<?, ?it/s]

embedding (embeddinggemma:latest):   0%|          | 2/8509 [00:00<10:57, 12.94it/s]

embedding (embeddinggemma:latest):   0%|          | 11/8509 [00:00<02:53, 48.87it/s]

embedding (embeddinggemma:latest):   0%|          | 17/8509 [00:00<02:53, 48.86it/s]

embedding (embeddinggemma:latest):   0%|          | 23/8509 [00:00<02:49, 49.94it/s]

embedding (embeddinggemma:latest):   0%|          | 29/8509 [00:00<02:46, 50.90it/s]

embedding (embeddinggemma:latest):   0%|          | 35/8509 [00:00<02:45, 51.15it/s]

embedding (embeddinggemma:latest):   0%|          | 41/8509 [00:00<02:44, 51.54it/s]

embedding (embeddinggemma:latest):   1%|          | 47/8509 [00:00<02:42, 52.06it/s]

embedding (embeddinggemma:latest):   1%|          | 53/8509 [00:01<02:41, 52.51it/s]

embedding (embeddinggemma:latest):   1%|          | 59/8509 [00:01<02:41, 52.38it/s]

embedding (embeddinggemma:latest):   1%|          | 65/8509 [00:01<02:39, 52.91it/s]

embedding (embeddinggemma:latest):   1%|          | 71/8509 [00:01<02:39, 52.80it/s]

embedding (embeddinggemma:latest):   1%|          | 77/8509 [00:01<02:39, 52.92it/s]

embedding (embeddinggemma:latest):   1%|          | 83/8509 [00:01<02:41, 52.22it/s]

embedding (embeddinggemma:latest):   1%|          | 89/8509 [00:01<02:39, 52.86it/s]

embedding (embeddinggemma:latest):   1%|          | 95/8509 [00:01<02:37, 53.26it/s]

embedding (embeddinggemma:latest):   1%|          | 101/8509 [00:01<02:37, 53.26it/s]

embedding (embeddinggemma:latest):   1%|▏         | 107/8509 [00:02<02:38, 52.89it/s]

embedding (embeddinggemma:latest):   1%|▏         | 113/8509 [00:02<02:39, 52.70it/s]

embedding (embeddinggemma:latest):   1%|▏         | 119/8509 [00:02<02:39, 52.52it/s]

embedding (embeddinggemma:latest):   1%|▏         | 125/8509 [00:02<02:41, 51.82it/s]

embedding (embeddinggemma:latest):   2%|▏         | 131/8509 [00:02<02:43, 51.14it/s]

embedding (embeddinggemma:latest):   2%|▏         | 137/8509 [00:02<02:44, 50.80it/s]

embedding (embeddinggemma:latest):   2%|▏         | 143/8509 [00:02<02:47, 50.08it/s]

embedding (embeddinggemma:latest):   2%|▏         | 149/8509 [00:02<02:46, 50.31it/s]

embedding (embeddinggemma:latest):   2%|▏         | 155/8509 [00:03<02:43, 51.09it/s]

embedding (embeddinggemma:latest):   2%|▏         | 161/8509 [00:03<02:45, 50.33it/s]

embedding (embeddinggemma:latest):   2%|▏         | 167/8509 [00:03<02:44, 50.82it/s]

embedding (embeddinggemma:latest):   2%|▏         | 173/8509 [00:03<02:45, 50.44it/s]

embedding (embeddinggemma:latest):   2%|▏         | 179/8509 [00:03<02:44, 50.56it/s]

embedding (embeddinggemma:latest):   2%|▏         | 185/8509 [00:03<02:44, 50.48it/s]

embedding (embeddinggemma:latest):   2%|▏         | 191/8509 [00:03<02:41, 51.41it/s]

embedding (embeddinggemma:latest):   2%|▏         | 197/8509 [00:03<02:40, 51.93it/s]

embedding (embeddinggemma:latest):   2%|▏         | 203/8509 [00:03<02:39, 51.96it/s]

embedding (embeddinggemma:latest):   2%|▏         | 209/8509 [00:04<02:41, 51.50it/s]

embedding (embeddinggemma:latest):   3%|▎         | 215/8509 [00:04<02:42, 51.00it/s]

embedding (embeddinggemma:latest):   3%|▎         | 221/8509 [00:04<02:41, 51.26it/s]

embedding (embeddinggemma:latest):   3%|▎         | 227/8509 [00:04<02:39, 51.89it/s]

embedding (embeddinggemma:latest):   3%|▎         | 233/8509 [00:04<02:38, 52.25it/s]

embedding (embeddinggemma:latest):   3%|▎         | 239/8509 [00:04<02:40, 51.39it/s]

embedding (embeddinggemma:latest):   3%|▎         | 245/8509 [00:04<02:39, 51.89it/s]

embedding (embeddinggemma:latest):   3%|▎         | 251/8509 [00:04<02:38, 52.19it/s]

embedding (embeddinggemma:latest):   3%|▎         | 257/8509 [00:05<02:36, 52.76it/s]

embedding (embeddinggemma:latest):   3%|▎         | 263/8509 [00:05<02:38, 51.99it/s]

embedding (embeddinggemma:latest):   3%|▎         | 269/8509 [00:05<02:41, 51.00it/s]

embedding (embeddinggemma:latest):   3%|▎         | 275/8509 [00:05<02:43, 50.45it/s]

embedding (embeddinggemma:latest):   3%|▎         | 281/8509 [00:05<02:50, 48.13it/s]

embedding (embeddinggemma:latest):   3%|▎         | 286/8509 [00:05<02:50, 48.34it/s]

embedding (embeddinggemma:latest):   3%|▎         | 292/8509 [00:05<02:43, 50.17it/s]

embedding (embeddinggemma:latest):   4%|▎         | 298/8509 [00:05<02:40, 51.05it/s]

embedding (embeddinggemma:latest):   4%|▎         | 304/8509 [00:05<02:39, 51.44it/s]

embedding (embeddinggemma:latest):   4%|▎         | 310/8509 [00:06<02:38, 51.68it/s]

embedding (embeddinggemma:latest):   4%|▎         | 316/8509 [00:06<02:36, 52.46it/s]

embedding (embeddinggemma:latest):   4%|▍         | 322/8509 [00:06<02:33, 53.20it/s]

embedding (embeddinggemma:latest):   4%|▍         | 328/8509 [00:06<02:33, 53.29it/s]

embedding (embeddinggemma:latest):   4%|▍         | 334/8509 [00:06<02:32, 53.47it/s]

embedding (embeddinggemma:latest):   4%|▍         | 340/8509 [00:06<02:33, 53.39it/s]

embedding (embeddinggemma:latest):   4%|▍         | 346/8509 [00:06<02:32, 53.54it/s]

embedding (embeddinggemma:latest):   4%|▍         | 352/8509 [00:06<02:35, 52.34it/s]

embedding (embeddinggemma:latest):   4%|▍         | 358/8509 [00:06<02:35, 52.27it/s]

embedding (embeddinggemma:latest):   4%|▍         | 364/8509 [00:07<02:35, 52.47it/s]

embedding (embeddinggemma:latest):   4%|▍         | 370/8509 [00:07<02:34, 52.80it/s]

embedding (embeddinggemma:latest):   4%|▍         | 376/8509 [00:07<02:33, 53.10it/s]

embedding (embeddinggemma:latest):   4%|▍         | 382/8509 [00:07<02:33, 53.12it/s]

embedding (embeddinggemma:latest):   5%|▍         | 388/8509 [00:07<02:34, 52.40it/s]

embedding (embeddinggemma:latest):   5%|▍         | 394/8509 [00:07<02:35, 52.13it/s]

embedding (embeddinggemma:latest):   5%|▍         | 400/8509 [00:07<02:35, 51.99it/s]

embedding (embeddinggemma:latest):   5%|▍         | 406/8509 [00:07<02:36, 51.79it/s]

embedding (embeddinggemma:latest):   5%|▍         | 412/8509 [00:07<02:35, 52.13it/s]

embedding (embeddinggemma:latest):   5%|▍         | 418/8509 [00:08<02:35, 52.00it/s]

embedding (embeddinggemma:latest):   5%|▍         | 424/8509 [00:08<02:33, 52.61it/s]

embedding (embeddinggemma:latest):   5%|▌         | 430/8509 [00:08<02:32, 53.05it/s]

embedding (embeddinggemma:latest):   5%|▌         | 436/8509 [00:08<02:32, 52.92it/s]

embedding (embeddinggemma:latest):   5%|▌         | 442/8509 [00:08<02:29, 53.94it/s]

embedding (embeddinggemma:latest):   5%|▌         | 448/8509 [00:08<02:28, 54.14it/s]

embedding (embeddinggemma:latest):   5%|▌         | 454/8509 [00:08<02:28, 54.30it/s]

embedding (embeddinggemma:latest):   5%|▌         | 460/8509 [00:08<02:32, 52.74it/s]

embedding (embeddinggemma:latest):   5%|▌         | 466/8509 [00:09<02:31, 53.21it/s]

embedding (embeddinggemma:latest):   6%|▌         | 472/8509 [00:09<02:32, 52.77it/s]

embedding (embeddinggemma:latest):   6%|▌         | 478/8509 [00:09<02:35, 51.79it/s]

embedding (embeddinggemma:latest):   6%|▌         | 484/8509 [00:09<02:33, 52.20it/s]

embedding (embeddinggemma:latest):   6%|▌         | 490/8509 [00:09<02:34, 51.99it/s]

embedding (embeddinggemma:latest):   6%|▌         | 496/8509 [00:09<02:31, 52.82it/s]

embedding (embeddinggemma:latest):   6%|▌         | 502/8509 [00:09<02:31, 52.77it/s]

embedding (embeddinggemma:latest):   6%|▌         | 508/8509 [00:09<02:34, 51.92it/s]

embedding (embeddinggemma:latest):   6%|▌         | 514/8509 [00:09<02:33, 52.12it/s]

embedding (embeddinggemma:latest):   6%|▌         | 520/8509 [00:10<02:34, 51.66it/s]

embedding (embeddinggemma:latest):   6%|▌         | 526/8509 [00:10<02:32, 52.43it/s]

embedding (embeddinggemma:latest):   6%|▋         | 532/8509 [00:10<02:32, 52.47it/s]

embedding (embeddinggemma:latest):   6%|▋         | 538/8509 [00:10<02:30, 52.95it/s]

embedding (embeddinggemma:latest):   6%|▋         | 544/8509 [00:10<02:29, 53.11it/s]

embedding (embeddinggemma:latest):   6%|▋         | 550/8509 [00:10<02:29, 53.08it/s]

embedding (embeddinggemma:latest):   7%|▋         | 556/8509 [00:10<02:29, 53.16it/s]

embedding (embeddinggemma:latest):   7%|▋         | 562/8509 [00:10<02:33, 51.90it/s]

embedding (embeddinggemma:latest):   7%|▋         | 568/8509 [00:10<02:30, 52.91it/s]

embedding (embeddinggemma:latest):   7%|▋         | 574/8509 [00:11<02:30, 52.60it/s]

embedding (embeddinggemma:latest):   7%|▋         | 580/8509 [00:11<02:29, 53.10it/s]

embedding (embeddinggemma:latest):   7%|▋         | 586/8509 [00:11<02:27, 53.55it/s]

embedding (embeddinggemma:latest):   7%|▋         | 592/8509 [00:11<02:27, 53.58it/s]

embedding (embeddinggemma:latest):   7%|▋         | 598/8509 [00:11<02:27, 53.72it/s]

embedding (embeddinggemma:latest):   7%|▋         | 604/8509 [00:11<02:27, 53.67it/s]

embedding (embeddinggemma:latest):   7%|▋         | 610/8509 [00:11<02:27, 53.55it/s]

embedding (embeddinggemma:latest):   7%|▋         | 616/8509 [00:11<02:27, 53.50it/s]

embedding (embeddinggemma:latest):   7%|▋         | 622/8509 [00:11<02:27, 53.38it/s]

embedding (embeddinggemma:latest):   7%|▋         | 628/8509 [00:12<02:28, 53.12it/s]

embedding (embeddinggemma:latest):   7%|▋         | 634/8509 [00:12<02:28, 52.86it/s]

embedding (embeddinggemma:latest):   8%|▊         | 640/8509 [00:12<02:30, 52.14it/s]

embedding (embeddinggemma:latest):   8%|▊         | 646/8509 [00:12<02:30, 52.33it/s]

embedding (embeddinggemma:latest):   8%|▊         | 652/8509 [00:12<02:29, 52.49it/s]

embedding (embeddinggemma:latest):   8%|▊         | 658/8509 [00:12<02:31, 51.83it/s]

embedding (embeddinggemma:latest):   8%|▊         | 664/8509 [00:12<02:31, 51.93it/s]

embedding (embeddinggemma:latest):   8%|▊         | 670/8509 [00:12<02:29, 52.36it/s]

embedding (embeddinggemma:latest):   8%|▊         | 676/8509 [00:12<02:28, 52.59it/s]

embedding (embeddinggemma:latest):   8%|▊         | 682/8509 [00:13<02:32, 51.28it/s]

embedding (embeddinggemma:latest):   8%|▊         | 688/8509 [00:13<02:32, 51.15it/s]

embedding (embeddinggemma:latest):   8%|▊         | 694/8509 [00:13<02:34, 50.71it/s]

embedding (embeddinggemma:latest):   8%|▊         | 700/8509 [00:13<02:34, 50.67it/s]

embedding (embeddinggemma:latest):   8%|▊         | 706/8509 [00:13<02:33, 50.75it/s]

embedding (embeddinggemma:latest):   8%|▊         | 712/8509 [00:13<02:32, 51.17it/s]

embedding (embeddinggemma:latest):   8%|▊         | 718/8509 [00:13<02:31, 51.38it/s]

embedding (embeddinggemma:latest):   9%|▊         | 724/8509 [00:13<02:30, 51.77it/s]

embedding (embeddinggemma:latest):   9%|▊         | 730/8509 [00:14<02:29, 51.87it/s]

embedding (embeddinggemma:latest):   9%|▊         | 736/8509 [00:14<02:31, 51.46it/s]

embedding (embeddinggemma:latest):   9%|▊         | 742/8509 [00:14<02:32, 51.10it/s]

embedding (embeddinggemma:latest):   9%|▉         | 748/8509 [00:14<02:32, 51.05it/s]

embedding (embeddinggemma:latest):   9%|▉         | 754/8509 [00:14<02:30, 51.43it/s]

embedding (embeddinggemma:latest):   9%|▉         | 760/8509 [00:14<02:30, 51.41it/s]

embedding (embeddinggemma:latest):   9%|▉         | 766/8509 [00:14<02:30, 51.39it/s]

embedding (embeddinggemma:latest):   9%|▉         | 772/8509 [00:14<02:32, 50.73it/s]

embedding (embeddinggemma:latest):   9%|▉         | 778/8509 [00:14<02:30, 51.25it/s]

embedding (embeddinggemma:latest):   9%|▉         | 784/8509 [00:15<02:33, 50.49it/s]

embedding (embeddinggemma:latest):   9%|▉         | 790/8509 [00:15<02:31, 50.79it/s]

embedding (embeddinggemma:latest):   9%|▉         | 796/8509 [00:15<02:34, 49.94it/s]

embedding (embeddinggemma:latest):   9%|▉         | 802/8509 [00:15<02:33, 50.08it/s]

embedding (embeddinggemma:latest):   9%|▉         | 808/8509 [00:15<02:33, 50.10it/s]

embedding (embeddinggemma:latest):  10%|▉         | 814/8509 [00:15<02:33, 50.07it/s]

embedding (embeddinggemma:latest):  10%|▉         | 820/8509 [00:15<02:33, 50.23it/s]

embedding (embeddinggemma:latest):  10%|▉         | 826/8509 [00:15<02:31, 50.72it/s]

embedding (embeddinggemma:latest):  10%|▉         | 832/8509 [00:16<02:31, 50.74it/s]

embedding (embeddinggemma:latest):  10%|▉         | 838/8509 [00:16<02:32, 50.35it/s]

embedding (embeddinggemma:latest):  10%|▉         | 844/8509 [00:16<02:33, 50.02it/s]

embedding (embeddinggemma:latest):  10%|▉         | 850/8509 [00:16<02:32, 50.36it/s]

embedding (embeddinggemma:latest):  10%|█         | 856/8509 [00:16<02:32, 50.33it/s]

embedding (embeddinggemma:latest):  10%|█         | 862/8509 [00:16<02:30, 50.72it/s]

embedding (embeddinggemma:latest):  10%|█         | 868/8509 [00:16<02:31, 50.31it/s]

embedding (embeddinggemma:latest):  10%|█         | 874/8509 [00:16<02:32, 50.05it/s]

embedding (embeddinggemma:latest):  10%|█         | 880/8509 [00:17<02:31, 50.41it/s]

embedding (embeddinggemma:latest):  10%|█         | 886/8509 [00:17<02:32, 49.84it/s]

embedding (embeddinggemma:latest):  10%|█         | 892/8509 [00:17<02:28, 51.22it/s]

embedding (embeddinggemma:latest):  11%|█         | 898/8509 [00:17<02:27, 51.61it/s]

embedding (embeddinggemma:latest):  11%|█         | 904/8509 [00:17<02:24, 52.69it/s]

embedding (embeddinggemma:latest):  11%|█         | 910/8509 [00:17<02:26, 51.78it/s]

embedding (embeddinggemma:latest):  11%|█         | 916/8509 [00:17<02:25, 52.22it/s]

embedding (embeddinggemma:latest):  11%|█         | 922/8509 [00:17<02:24, 52.68it/s]

embedding (embeddinggemma:latest):  11%|█         | 928/8509 [00:17<02:22, 53.18it/s]

embedding (embeddinggemma:latest):  11%|█         | 934/8509 [00:18<02:22, 53.20it/s]

embedding (embeddinggemma:latest):  11%|█         | 940/8509 [00:18<02:23, 52.80it/s]

embedding (embeddinggemma:latest):  11%|█         | 946/8509 [00:18<02:22, 53.22it/s]

embedding (embeddinggemma:latest):  11%|█         | 952/8509 [00:18<02:23, 52.77it/s]

embedding (embeddinggemma:latest):  11%|█▏        | 958/8509 [00:18<02:21, 53.24it/s]

embedding (embeddinggemma:latest):  11%|█▏        | 964/8509 [00:18<02:22, 53.12it/s]

embedding (embeddinggemma:latest):  11%|█▏        | 970/8509 [00:18<02:22, 53.06it/s]

embedding (embeddinggemma:latest):  11%|█▏        | 976/8509 [00:18<02:20, 53.78it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 982/8509 [00:18<02:20, 53.39it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 988/8509 [00:19<02:20, 53.39it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 994/8509 [00:19<02:19, 53.91it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1000/8509 [00:19<02:19, 53.87it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1006/8509 [00:19<02:19, 53.82it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1012/8509 [00:19<02:20, 53.50it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1018/8509 [00:19<02:19, 53.74it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1024/8509 [00:19<02:18, 54.14it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1030/8509 [00:19<02:17, 54.26it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1036/8509 [00:19<02:17, 54.23it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1042/8509 [00:20<02:17, 54.24it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1048/8509 [00:20<02:17, 54.40it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1054/8509 [00:20<02:17, 54.29it/s]

embedding (embeddinggemma:latest):  12%|█▏        | 1060/8509 [00:20<02:18, 53.82it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1066/8509 [00:20<02:17, 54.01it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1072/8509 [00:20<02:17, 54.09it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1078/8509 [00:20<02:18, 53.74it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1084/8509 [00:20<02:17, 54.14it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1090/8509 [00:20<02:16, 54.18it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1096/8509 [00:21<02:18, 53.70it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1102/8509 [00:21<02:17, 53.86it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1108/8509 [00:21<02:16, 54.32it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1114/8509 [00:21<02:16, 54.30it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1120/8509 [00:21<02:17, 53.59it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1126/8509 [00:21<02:17, 53.88it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1132/8509 [00:21<02:17, 53.69it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1138/8509 [00:21<02:17, 53.62it/s]

embedding (embeddinggemma:latest):  13%|█▎        | 1144/8509 [00:21<02:18, 53.07it/s]

embedding (embeddinggemma:latest):  14%|█▎        | 1150/8509 [00:22<02:18, 53.11it/s]

embedding (embeddinggemma:latest):  14%|█▎        | 1156/8509 [00:22<02:17, 53.55it/s]

embedding (embeddinggemma:latest):  14%|█▎        | 1162/8509 [00:22<02:18, 53.15it/s]

embedding (embeddinggemma:latest):  14%|█▎        | 1168/8509 [00:22<02:18, 52.89it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1174/8509 [00:22<02:16, 53.58it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1180/8509 [00:22<02:16, 53.62it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1186/8509 [00:22<02:20, 52.19it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1192/8509 [00:22<02:20, 52.20it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1198/8509 [00:22<02:19, 52.30it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1204/8509 [00:23<02:18, 52.76it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1210/8509 [00:23<02:17, 52.97it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1216/8509 [00:23<02:17, 53.13it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1222/8509 [00:23<02:15, 53.68it/s]

embedding (embeddinggemma:latest):  14%|█▍        | 1228/8509 [00:23<02:15, 53.73it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1234/8509 [00:23<02:16, 53.20it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1240/8509 [00:23<02:16, 53.36it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1246/8509 [00:23<02:15, 53.61it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1252/8509 [00:23<02:15, 53.46it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1258/8509 [00:24<02:14, 53.78it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1264/8509 [00:24<02:15, 53.58it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1270/8509 [00:24<02:17, 52.78it/s]

embedding (embeddinggemma:latest):  15%|█▍        | 1276/8509 [00:24<02:17, 52.76it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1282/8509 [00:24<02:16, 52.93it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1288/8509 [00:24<02:15, 53.35it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1294/8509 [00:24<02:14, 53.59it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1300/8509 [00:24<02:15, 53.12it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1306/8509 [00:25<02:18, 52.10it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1312/8509 [00:25<02:15, 53.27it/s]

embedding (embeddinggemma:latest):  15%|█▌        | 1318/8509 [00:25<02:14, 53.27it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1324/8509 [00:25<02:13, 53.74it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1330/8509 [00:25<02:12, 54.00it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1336/8509 [00:25<02:13, 53.89it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1342/8509 [00:25<02:14, 53.23it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1348/8509 [00:25<02:14, 53.14it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1354/8509 [00:25<02:14, 53.09it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1360/8509 [00:26<02:14, 53.14it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1366/8509 [00:26<02:15, 52.72it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1372/8509 [00:26<02:15, 52.62it/s]

embedding (embeddinggemma:latest):  16%|█▌        | 1378/8509 [00:26<02:14, 52.92it/s]

embedding (embeddinggemma:latest):  16%|█▋        | 1384/8509 [00:26<02:14, 52.80it/s]

embedding (embeddinggemma:latest):  16%|█▋        | 1390/8509 [00:26<02:14, 52.94it/s]

embedding (embeddinggemma:latest):  16%|█▋        | 1396/8509 [00:26<02:13, 53.23it/s]

embedding (embeddinggemma:latest):  16%|█▋        | 1402/8509 [00:26<02:14, 52.75it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1408/8509 [00:26<02:14, 52.99it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1414/8509 [00:27<02:13, 53.31it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1420/8509 [00:27<02:11, 53.84it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1426/8509 [00:27<02:09, 54.55it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1432/8509 [00:27<02:10, 54.29it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1438/8509 [00:27<02:09, 54.39it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1444/8509 [00:27<02:09, 54.48it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1450/8509 [00:27<02:10, 54.26it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1456/8509 [00:27<02:09, 54.43it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1462/8509 [00:27<02:09, 54.60it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1468/8509 [00:28<02:09, 54.32it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1474/8509 [00:28<02:08, 54.74it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1480/8509 [00:28<02:09, 54.38it/s]

embedding (embeddinggemma:latest):  17%|█▋        | 1486/8509 [00:28<02:08, 54.49it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1492/8509 [00:28<02:09, 54.04it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1498/8509 [00:28<02:09, 54.02it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1504/8509 [00:28<02:10, 53.81it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1510/8509 [00:28<02:10, 53.73it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1516/8509 [00:28<02:10, 53.42it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1522/8509 [00:29<02:11, 52.99it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1528/8509 [00:29<02:12, 52.84it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1534/8509 [00:29<02:11, 53.13it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1540/8509 [00:29<02:10, 53.28it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1546/8509 [00:29<02:09, 53.73it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1552/8509 [00:29<02:09, 53.78it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1558/8509 [00:29<02:09, 53.70it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1564/8509 [00:29<02:08, 53.88it/s]

embedding (embeddinggemma:latest):  18%|█▊        | 1570/8509 [00:29<02:07, 54.24it/s]

embedding (embeddinggemma:latest):  19%|█▊        | 1576/8509 [00:30<02:07, 54.26it/s]

embedding (embeddinggemma:latest):  19%|█▊        | 1582/8509 [00:30<02:06, 54.61it/s]

embedding (embeddinggemma:latest):  19%|█▊        | 1588/8509 [00:30<02:06, 54.70it/s]

embedding (embeddinggemma:latest):  19%|█▊        | 1594/8509 [00:30<02:06, 54.71it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1600/8509 [00:30<02:07, 54.31it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1606/8509 [00:30<02:06, 54.71it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1612/8509 [00:30<02:06, 54.50it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1618/8509 [00:30<02:04, 55.15it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1624/8509 [00:30<02:05, 54.79it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1630/8509 [00:31<02:05, 54.79it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1636/8509 [00:31<02:05, 54.70it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1642/8509 [00:31<02:04, 55.08it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1648/8509 [00:31<02:04, 55.13it/s]

embedding (embeddinggemma:latest):  19%|█▉        | 1654/8509 [00:31<02:04, 55.09it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1660/8509 [00:31<02:05, 54.70it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1666/8509 [00:31<02:04, 55.03it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1672/8509 [00:31<02:03, 55.56it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1678/8509 [00:31<02:03, 55.24it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1684/8509 [00:31<02:03, 55.42it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1690/8509 [00:32<02:03, 55.24it/s]

embedding (embeddinggemma:latest):  20%|█▉        | 1696/8509 [00:32<02:04, 54.52it/s]

embedding (embeddinggemma:latest):  20%|██        | 1702/8509 [00:32<02:01, 56.00it/s]

embedding (embeddinggemma:latest):  20%|██        | 1708/8509 [00:32<02:02, 55.42it/s]

embedding (embeddinggemma:latest):  20%|██        | 1714/8509 [00:32<02:02, 55.63it/s]

embedding (embeddinggemma:latest):  20%|██        | 1720/8509 [00:32<02:02, 55.48it/s]

embedding (embeddinggemma:latest):  20%|██        | 1726/8509 [00:32<02:02, 55.35it/s]

embedding (embeddinggemma:latest):  20%|██        | 1732/8509 [00:32<02:01, 55.63it/s]

embedding (embeddinggemma:latest):  20%|██        | 1738/8509 [00:32<02:05, 53.91it/s]

embedding (embeddinggemma:latest):  20%|██        | 1744/8509 [00:33<02:06, 53.56it/s]

embedding (embeddinggemma:latest):  21%|██        | 1750/8509 [00:33<02:07, 53.02it/s]

embedding (embeddinggemma:latest):  21%|██        | 1756/8509 [00:33<02:08, 52.67it/s]

embedding (embeddinggemma:latest):  21%|██        | 1762/8509 [00:33<02:08, 52.63it/s]

embedding (embeddinggemma:latest):  21%|██        | 1768/8509 [00:33<02:09, 51.93it/s]

embedding (embeddinggemma:latest):  21%|██        | 1774/8509 [00:33<02:09, 51.92it/s]

embedding (embeddinggemma:latest):  21%|██        | 1780/8509 [00:33<02:09, 51.83it/s]

embedding (embeddinggemma:latest):  21%|██        | 1786/8509 [00:33<02:11, 51.25it/s]

embedding (embeddinggemma:latest):  21%|██        | 1792/8509 [00:34<02:10, 51.47it/s]

embedding (embeddinggemma:latest):  21%|██        | 1798/8509 [00:34<02:12, 50.80it/s]

embedding (embeddinggemma:latest):  21%|██        | 1804/8509 [00:34<02:11, 50.93it/s]

embedding (embeddinggemma:latest):  21%|██▏       | 1810/8509 [00:34<02:12, 50.75it/s]

embedding (embeddinggemma:latest):  21%|██▏       | 1816/8509 [00:34<02:12, 50.69it/s]

embedding (embeddinggemma:latest):  21%|██▏       | 1822/8509 [00:34<02:13, 50.06it/s]

embedding (embeddinggemma:latest):  21%|██▏       | 1828/8509 [00:34<02:12, 50.33it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1834/8509 [00:34<02:12, 50.27it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1840/8509 [00:34<02:10, 50.92it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1846/8509 [00:35<02:08, 51.81it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1852/8509 [00:35<02:06, 52.65it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1858/8509 [00:35<02:06, 52.78it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1864/8509 [00:35<02:04, 53.32it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1870/8509 [00:35<02:02, 54.02it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1876/8509 [00:35<02:01, 54.45it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1882/8509 [00:35<02:02, 53.91it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1888/8509 [00:35<02:09, 51.25it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1894/8509 [00:36<02:13, 49.66it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1899/8509 [00:36<02:16, 48.28it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1904/8509 [00:36<02:21, 46.60it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1909/8509 [00:36<02:25, 45.40it/s]

embedding (embeddinggemma:latest):  22%|██▏       | 1914/8509 [00:36<02:30, 43.89it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1919/8509 [00:36<02:34, 42.59it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1924/8509 [00:36<02:39, 41.33it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1929/8509 [00:36<02:44, 40.06it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1934/8509 [00:37<02:51, 38.25it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1938/8509 [00:37<02:57, 37.10it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1942/8509 [00:37<03:05, 35.45it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1946/8509 [00:37<03:16, 33.44it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1950/8509 [00:37<03:22, 32.31it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1954/8509 [00:37<03:27, 31.66it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1958/8509 [00:37<03:31, 30.95it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1962/8509 [00:37<03:41, 29.62it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1965/8509 [00:38<03:42, 29.44it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1968/8509 [00:38<03:45, 28.95it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1971/8509 [00:38<03:46, 28.90it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1974/8509 [00:38<03:46, 28.87it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1977/8509 [00:38<03:55, 27.78it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1980/8509 [00:38<04:01, 27.04it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1983/8509 [00:38<04:05, 26.58it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1986/8509 [00:38<04:11, 25.91it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1989/8509 [00:38<04:19, 25.16it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1992/8509 [00:39<04:23, 24.75it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1995/8509 [00:39<04:21, 24.91it/s]

embedding (embeddinggemma:latest):  23%|██▎       | 1998/8509 [00:39<04:27, 24.32it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2001/8509 [00:39<04:29, 24.18it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2004/8509 [00:39<04:29, 24.14it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2007/8509 [00:39<04:27, 24.27it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2010/8509 [00:39<04:32, 23.86it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2013/8509 [00:39<04:34, 23.69it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2016/8509 [00:40<04:33, 23.75it/s]

embedding (embeddinggemma:latest):  24%|██▎       | 2019/8509 [00:40<04:37, 23.36it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2022/8509 [00:40<04:33, 23.75it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2025/8509 [00:40<04:27, 24.25it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2028/8509 [00:40<04:28, 24.18it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2031/8509 [00:40<04:30, 23.98it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2034/8509 [00:40<04:34, 23.55it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2037/8509 [00:40<04:34, 23.60it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2040/8509 [00:41<04:32, 23.76it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2043/8509 [00:41<04:30, 23.93it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2046/8509 [00:41<04:36, 23.37it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2049/8509 [00:41<04:31, 23.75it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2052/8509 [00:41<04:33, 23.59it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2055/8509 [00:41<04:41, 22.94it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2058/8509 [00:41<04:40, 23.01it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2061/8509 [00:42<04:35, 23.37it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2064/8509 [00:42<04:32, 23.68it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2067/8509 [00:42<04:32, 23.67it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2070/8509 [00:42<04:37, 23.18it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2073/8509 [00:42<04:38, 23.08it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2076/8509 [00:42<04:43, 22.68it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2079/8509 [00:42<04:46, 22.41it/s]

embedding (embeddinggemma:latest):  24%|██▍       | 2082/8509 [00:42<04:44, 22.55it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2085/8509 [00:43<04:46, 22.43it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2088/8509 [00:43<04:40, 22.92it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2091/8509 [00:43<04:31, 23.67it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2094/8509 [00:43<04:26, 24.09it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2097/8509 [00:43<04:28, 23.92it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2100/8509 [00:43<04:20, 24.57it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2103/8509 [00:43<04:26, 24.00it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2106/8509 [00:43<04:30, 23.66it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2109/8509 [00:44<04:28, 23.81it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2112/8509 [00:44<04:32, 23.48it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2115/8509 [00:44<04:35, 23.25it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2118/8509 [00:44<04:34, 23.29it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2121/8509 [00:44<04:31, 23.51it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2124/8509 [00:44<04:28, 23.74it/s]

embedding (embeddinggemma:latest):  25%|██▍       | 2127/8509 [00:44<04:30, 23.62it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2130/8509 [00:44<04:34, 23.25it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2133/8509 [00:45<04:36, 23.07it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2136/8509 [00:45<04:30, 23.53it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2139/8509 [00:45<04:25, 24.00it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2142/8509 [00:45<04:23, 24.16it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2145/8509 [00:45<04:19, 24.53it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2148/8509 [00:45<04:20, 24.45it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2151/8509 [00:45<04:23, 24.12it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2154/8509 [00:45<04:25, 23.89it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2157/8509 [00:46<04:31, 23.40it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2160/8509 [00:46<04:33, 23.19it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2163/8509 [00:46<04:39, 22.70it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2166/8509 [00:46<04:37, 22.89it/s]

embedding (embeddinggemma:latest):  25%|██▌       | 2169/8509 [00:46<04:35, 22.99it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2172/8509 [00:46<04:42, 22.42it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2175/8509 [00:46<04:40, 22.60it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2178/8509 [00:47<04:36, 22.91it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2181/8509 [00:47<04:33, 23.10it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2184/8509 [00:47<04:31, 23.26it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2187/8509 [00:47<04:34, 23.01it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2190/8509 [00:47<04:35, 22.96it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2193/8509 [00:47<04:25, 23.77it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2196/8509 [00:47<04:23, 23.91it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2199/8509 [00:47<04:16, 24.57it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2202/8509 [00:48<04:21, 24.13it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2205/8509 [00:48<04:28, 23.49it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2208/8509 [00:48<04:30, 23.28it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2211/8509 [00:48<04:30, 23.24it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2214/8509 [00:48<04:36, 22.73it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2217/8509 [00:48<04:39, 22.48it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2220/8509 [00:48<04:30, 23.22it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2223/8509 [00:48<04:27, 23.49it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2226/8509 [00:49<04:20, 24.09it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2229/8509 [00:49<04:19, 24.18it/s]

embedding (embeddinggemma:latest):  26%|██▌       | 2232/8509 [00:49<04:12, 24.88it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2235/8509 [00:49<04:17, 24.39it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2238/8509 [00:49<04:19, 24.19it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2241/8509 [00:49<04:22, 23.90it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2244/8509 [00:49<04:33, 22.94it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2247/8509 [00:49<04:26, 23.49it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2250/8509 [00:50<04:21, 23.92it/s]

embedding (embeddinggemma:latest):  26%|██▋       | 2253/8509 [00:50<04:23, 23.74it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2256/8509 [00:50<04:25, 23.57it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2259/8509 [00:50<04:23, 23.74it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2262/8509 [00:50<04:27, 23.39it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2265/8509 [00:50<04:26, 23.44it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2268/8509 [00:50<04:26, 23.38it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2271/8509 [00:50<04:25, 23.50it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2274/8509 [00:51<04:27, 23.31it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2277/8509 [00:51<04:33, 22.82it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2280/8509 [00:51<04:34, 22.71it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2283/8509 [00:51<04:31, 22.89it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2286/8509 [00:51<04:30, 23.04it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2289/8509 [00:51<04:25, 23.43it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2292/8509 [00:51<04:17, 24.10it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2295/8509 [00:51<04:19, 23.97it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2298/8509 [00:52<04:09, 24.91it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2301/8509 [00:52<04:16, 24.23it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2304/8509 [00:52<04:20, 23.84it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2307/8509 [00:52<04:18, 24.03it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2310/8509 [00:52<04:25, 23.32it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2313/8509 [00:52<04:22, 23.58it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2316/8509 [00:52<04:27, 23.16it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2319/8509 [00:53<04:26, 23.22it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2322/8509 [00:53<04:25, 23.28it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2325/8509 [00:53<04:28, 23.04it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2328/8509 [00:53<04:27, 23.15it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2331/8509 [00:53<04:25, 23.28it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2334/8509 [00:53<04:21, 23.61it/s]

embedding (embeddinggemma:latest):  27%|██▋       | 2337/8509 [00:53<04:09, 24.70it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2340/8509 [00:53<04:10, 24.66it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2343/8509 [00:54<04:18, 23.90it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2346/8509 [00:54<04:25, 23.23it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2349/8509 [00:54<04:27, 22.99it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2352/8509 [00:54<04:32, 22.59it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2355/8509 [00:54<04:34, 22.45it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2358/8509 [00:54<04:36, 22.28it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2361/8509 [00:54<04:36, 22.25it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2364/8509 [00:54<04:36, 22.22it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2367/8509 [00:55<04:34, 22.41it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2370/8509 [00:55<04:29, 22.77it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2373/8509 [00:55<04:33, 22.47it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2376/8509 [00:55<04:39, 21.93it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2379/8509 [00:55<04:45, 21.47it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2382/8509 [00:55<04:42, 21.67it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2385/8509 [00:55<04:38, 22.00it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2388/8509 [00:56<04:30, 22.60it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2391/8509 [00:56<04:30, 22.61it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2394/8509 [00:56<04:30, 22.59it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2397/8509 [00:56<04:28, 22.78it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2400/8509 [00:56<04:23, 23.18it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2403/8509 [00:56<04:20, 23.42it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2406/8509 [00:56<04:18, 23.65it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2409/8509 [00:56<04:17, 23.72it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2412/8509 [00:57<04:14, 23.91it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2415/8509 [00:57<04:16, 23.76it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2418/8509 [00:57<04:10, 24.32it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2421/8509 [00:57<04:03, 25.02it/s]

embedding (embeddinggemma:latest):  28%|██▊       | 2424/8509 [00:57<04:09, 24.39it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2427/8509 [00:57<04:17, 23.66it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2430/8509 [00:57<04:23, 23.04it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2433/8509 [00:57<04:21, 23.21it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2436/8509 [00:58<04:18, 23.53it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2439/8509 [00:58<04:18, 23.47it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2442/8509 [00:58<04:20, 23.27it/s]

embedding (embeddinggemma:latest):  29%|██▊       | 2445/8509 [00:58<04:18, 23.50it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2448/8509 [00:58<04:25, 22.82it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2451/8509 [00:58<04:26, 22.73it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2454/8509 [00:58<04:22, 23.02it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2457/8509 [00:58<04:33, 22.12it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2460/8509 [00:59<04:42, 21.42it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2463/8509 [00:59<04:38, 21.69it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2466/8509 [00:59<04:39, 21.63it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2469/8509 [00:59<04:37, 21.75it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2472/8509 [00:59<04:36, 21.85it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2475/8509 [00:59<04:33, 22.04it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2478/8509 [00:59<04:30, 22.32it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2481/8509 [01:00<04:23, 22.88it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2484/8509 [01:00<04:14, 23.64it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2487/8509 [01:00<04:11, 23.97it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2490/8509 [01:00<04:06, 24.42it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2493/8509 [01:00<04:07, 24.30it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2496/8509 [01:00<04:04, 24.61it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2499/8509 [01:00<03:59, 25.07it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2502/8509 [01:00<03:58, 25.18it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2505/8509 [01:01<04:05, 24.46it/s]

embedding (embeddinggemma:latest):  29%|██▉       | 2508/8509 [01:01<04:12, 23.81it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2511/8509 [01:01<04:15, 23.48it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2514/8509 [01:01<04:20, 23.02it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2517/8509 [01:01<04:20, 22.97it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2520/8509 [01:01<04:28, 22.29it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2523/8509 [01:01<04:28, 22.26it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2526/8509 [01:02<04:39, 21.43it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2529/8509 [01:02<04:36, 21.63it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2532/8509 [01:02<04:36, 21.64it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2535/8509 [01:02<04:33, 21.82it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2538/8509 [01:02<04:36, 21.61it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2541/8509 [01:02<04:29, 22.17it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2544/8509 [01:02<04:26, 22.39it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2547/8509 [01:02<04:31, 21.97it/s]

embedding (embeddinggemma:latest):  30%|██▉       | 2550/8509 [01:03<04:29, 22.08it/s]

embedding (embeddinggemma:latest):  30%|███       | 2553/8509 [01:03<04:26, 22.33it/s]

embedding (embeddinggemma:latest):  30%|███       | 2556/8509 [01:03<04:24, 22.49it/s]

embedding (embeddinggemma:latest):  30%|███       | 2559/8509 [01:03<04:27, 22.25it/s]

embedding (embeddinggemma:latest):  30%|███       | 2562/8509 [01:03<04:25, 22.37it/s]

embedding (embeddinggemma:latest):  30%|███       | 2565/8509 [01:03<04:23, 22.53it/s]

embedding (embeddinggemma:latest):  30%|███       | 2568/8509 [01:03<04:24, 22.49it/s]

embedding (embeddinggemma:latest):  30%|███       | 2571/8509 [01:04<04:23, 22.53it/s]

embedding (embeddinggemma:latest):  30%|███       | 2574/8509 [01:04<04:22, 22.58it/s]

embedding (embeddinggemma:latest):  30%|███       | 2577/8509 [01:04<04:22, 22.60it/s]

embedding (embeddinggemma:latest):  30%|███       | 2580/8509 [01:04<04:21, 22.70it/s]

embedding (embeddinggemma:latest):  30%|███       | 2583/8509 [01:04<04:17, 22.97it/s]

embedding (embeddinggemma:latest):  30%|███       | 2586/8509 [01:04<04:23, 22.48it/s]

embedding (embeddinggemma:latest):  30%|███       | 2589/8509 [01:04<04:22, 22.52it/s]

embedding (embeddinggemma:latest):  30%|███       | 2592/8509 [01:04<04:30, 21.89it/s]

embedding (embeddinggemma:latest):  30%|███       | 2595/8509 [01:05<04:36, 21.39it/s]

embedding (embeddinggemma:latest):  31%|███       | 2598/8509 [01:05<04:39, 21.14it/s]

embedding (embeddinggemma:latest):  31%|███       | 2601/8509 [01:05<04:41, 20.98it/s]

embedding (embeddinggemma:latest):  31%|███       | 2604/8509 [01:05<04:38, 21.22it/s]

embedding (embeddinggemma:latest):  31%|███       | 2607/8509 [01:05<04:22, 22.52it/s]

embedding (embeddinggemma:latest):  31%|███       | 2610/8509 [01:05<04:21, 22.59it/s]

embedding (embeddinggemma:latest):  31%|███       | 2613/8509 [01:05<04:25, 22.21it/s]

embedding (embeddinggemma:latest):  31%|███       | 2616/8509 [01:06<04:29, 21.86it/s]

embedding (embeddinggemma:latest):  31%|███       | 2619/8509 [01:06<04:28, 21.92it/s]

embedding (embeddinggemma:latest):  31%|███       | 2622/8509 [01:06<04:27, 22.00it/s]

embedding (embeddinggemma:latest):  31%|███       | 2625/8509 [01:06<04:26, 22.07it/s]

embedding (embeddinggemma:latest):  31%|███       | 2628/8509 [01:06<04:34, 21.45it/s]

embedding (embeddinggemma:latest):  31%|███       | 2631/8509 [01:06<04:31, 21.65it/s]

embedding (embeddinggemma:latest):  31%|███       | 2634/8509 [01:06<04:30, 21.71it/s]

embedding (embeddinggemma:latest):  31%|███       | 2637/8509 [01:07<04:28, 21.85it/s]

embedding (embeddinggemma:latest):  31%|███       | 2640/8509 [01:07<04:28, 21.85it/s]

embedding (embeddinggemma:latest):  31%|███       | 2643/8509 [01:07<04:29, 21.77it/s]

embedding (embeddinggemma:latest):  31%|███       | 2646/8509 [01:07<04:31, 21.61it/s]

embedding (embeddinggemma:latest):  31%|███       | 2649/8509 [01:07<04:26, 22.02it/s]

embedding (embeddinggemma:latest):  31%|███       | 2652/8509 [01:07<04:29, 21.71it/s]

embedding (embeddinggemma:latest):  31%|███       | 2655/8509 [01:07<04:33, 21.37it/s]

embedding (embeddinggemma:latest):  31%|███       | 2658/8509 [01:07<04:25, 22.03it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2661/8509 [01:08<04:18, 22.62it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2664/8509 [01:08<04:12, 23.13it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2667/8509 [01:08<04:14, 22.91it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2670/8509 [01:08<04:25, 22.01it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2673/8509 [01:08<04:24, 22.08it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2676/8509 [01:08<04:16, 22.74it/s]

embedding (embeddinggemma:latest):  31%|███▏      | 2679/8509 [01:08<04:14, 22.94it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2682/8509 [01:09<04:14, 22.88it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2685/8509 [01:09<04:13, 22.94it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2688/8509 [01:09<04:18, 22.50it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2691/8509 [01:09<04:24, 21.99it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2694/8509 [01:09<04:20, 22.30it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2697/8509 [01:09<04:20, 22.28it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2700/8509 [01:09<04:24, 21.96it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2703/8509 [01:09<04:20, 22.26it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2706/8509 [01:10<04:15, 22.69it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2709/8509 [01:10<04:09, 23.21it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2712/8509 [01:10<04:04, 23.75it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2715/8509 [01:10<04:01, 24.02it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2718/8509 [01:10<04:00, 24.08it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2721/8509 [01:10<03:56, 24.47it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2724/8509 [01:10<04:02, 23.82it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2727/8509 [01:11<04:18, 22.41it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2730/8509 [01:11<04:16, 22.52it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2733/8509 [01:11<04:11, 22.96it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2736/8509 [01:11<04:09, 23.14it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2739/8509 [01:11<04:12, 22.89it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2742/8509 [01:11<04:16, 22.44it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2745/8509 [01:11<04:18, 22.26it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2748/8509 [01:11<04:21, 22.05it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2751/8509 [01:12<04:18, 22.25it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2754/8509 [01:12<04:17, 22.39it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2757/8509 [01:12<04:20, 22.06it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2760/8509 [01:12<04:17, 22.37it/s]

embedding (embeddinggemma:latest):  32%|███▏      | 2763/8509 [01:12<04:16, 22.43it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2766/8509 [01:12<04:12, 22.70it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2769/8509 [01:12<04:11, 22.83it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2772/8509 [01:12<04:06, 23.28it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2775/8509 [01:13<04:04, 23.42it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2778/8509 [01:13<04:07, 23.16it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2781/8509 [01:13<04:15, 22.44it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2784/8509 [01:13<04:22, 21.80it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2787/8509 [01:13<04:23, 21.73it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2790/8509 [01:13<04:18, 22.16it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2793/8509 [01:13<04:20, 21.98it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2796/8509 [01:14<04:19, 21.99it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2799/8509 [01:14<04:17, 22.14it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2802/8509 [01:14<04:20, 21.92it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2805/8509 [01:14<04:25, 21.49it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2808/8509 [01:14<04:28, 21.23it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2811/8509 [01:14<04:28, 21.23it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2814/8509 [01:14<04:34, 20.78it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2817/8509 [01:15<04:37, 20.49it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2820/8509 [01:15<04:37, 20.54it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2823/8509 [01:15<04:36, 20.53it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2826/8509 [01:15<04:25, 21.40it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2829/8509 [01:15<04:24, 21.49it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2832/8509 [01:15<04:24, 21.49it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2835/8509 [01:15<04:36, 20.53it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2838/8509 [01:16<04:34, 20.69it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2841/8509 [01:16<04:30, 20.92it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2844/8509 [01:16<04:32, 20.77it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2847/8509 [01:16<04:28, 21.09it/s]

embedding (embeddinggemma:latest):  33%|███▎      | 2850/8509 [01:16<04:18, 21.88it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2853/8509 [01:16<04:15, 22.14it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2856/8509 [01:16<04:20, 21.71it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2859/8509 [01:17<04:16, 22.03it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2862/8509 [01:17<04:09, 22.59it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2865/8509 [01:17<04:11, 22.43it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2868/8509 [01:17<04:12, 22.35it/s]

embedding (embeddinggemma:latest):  34%|███▎      | 2871/8509 [01:17<04:18, 21.83it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2874/8509 [01:17<04:17, 21.85it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2877/8509 [01:17<04:09, 22.58it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2880/8509 [01:17<04:06, 22.84it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2883/8509 [01:18<04:06, 22.84it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2886/8509 [01:18<04:11, 22.40it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2889/8509 [01:18<04:20, 21.60it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2892/8509 [01:18<04:17, 21.78it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2895/8509 [01:18<04:20, 21.52it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2898/8509 [01:18<04:20, 21.50it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2901/8509 [01:18<04:26, 21.02it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2904/8509 [01:19<04:30, 20.73it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2907/8509 [01:19<04:32, 20.52it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2910/8509 [01:19<04:36, 20.26it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2913/8509 [01:19<04:38, 20.08it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2916/8509 [01:19<04:34, 20.37it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2919/8509 [01:19<04:30, 20.63it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2922/8509 [01:19<04:23, 21.24it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2925/8509 [01:20<04:17, 21.68it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2928/8509 [01:20<04:09, 22.41it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2931/8509 [01:20<04:04, 22.81it/s]

embedding (embeddinggemma:latest):  34%|███▍      | 2934/8509 [01:20<04:02, 22.95it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2937/8509 [01:20<04:01, 23.03it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2940/8509 [01:20<03:58, 23.38it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2943/8509 [01:20<03:57, 23.43it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2946/8509 [01:21<04:02, 22.96it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2949/8509 [01:21<04:17, 21.63it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2952/8509 [01:21<04:22, 21.15it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2955/8509 [01:21<04:19, 21.40it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2958/8509 [01:21<04:20, 21.27it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2961/8509 [01:21<04:14, 21.81it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2964/8509 [01:21<04:09, 22.20it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2967/8509 [01:21<04:09, 22.22it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2970/8509 [01:22<04:03, 22.74it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2973/8509 [01:22<04:02, 22.84it/s]

embedding (embeddinggemma:latest):  35%|███▍      | 2976/8509 [01:22<03:59, 23.09it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2979/8509 [01:22<03:59, 23.10it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2982/8509 [01:22<04:01, 22.90it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2985/8509 [01:22<04:00, 22.93it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2988/8509 [01:22<04:09, 22.11it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2991/8509 [01:23<04:14, 21.68it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2994/8509 [01:23<04:02, 22.75it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 2997/8509 [01:23<03:55, 23.36it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3000/8509 [01:23<03:53, 23.58it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3003/8509 [01:23<03:53, 23.57it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3006/8509 [01:23<03:58, 23.03it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3009/8509 [01:23<04:03, 22.63it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3012/8509 [01:23<04:08, 22.14it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3015/8509 [01:24<04:08, 22.14it/s]

embedding (embeddinggemma:latest):  35%|███▌      | 3018/8509 [01:24<04:00, 22.87it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3021/8509 [01:24<04:07, 22.20it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3024/8509 [01:24<04:09, 21.99it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3027/8509 [01:24<04:06, 22.25it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3030/8509 [01:24<04:07, 22.12it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3033/8509 [01:24<04:02, 22.62it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3036/8509 [01:25<03:52, 23.49it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3039/8509 [01:25<03:48, 23.92it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3042/8509 [01:25<03:48, 23.88it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3045/8509 [01:25<03:52, 23.48it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3048/8509 [01:25<03:54, 23.33it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3051/8509 [01:25<03:59, 22.74it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3054/8509 [01:25<04:01, 22.60it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3057/8509 [01:25<03:59, 22.81it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3060/8509 [01:26<04:03, 22.36it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3063/8509 [01:26<04:05, 22.19it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3066/8509 [01:26<04:05, 22.14it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3069/8509 [01:26<04:05, 22.20it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3072/8509 [01:26<04:05, 22.11it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3075/8509 [01:26<04:04, 22.19it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3078/8509 [01:26<03:59, 22.67it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3081/8509 [01:27<03:55, 23.01it/s]

embedding (embeddinggemma:latest):  36%|███▌      | 3084/8509 [01:27<03:47, 23.85it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3087/8509 [01:27<03:46, 23.95it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3090/8509 [01:27<03:43, 24.28it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3093/8509 [01:27<03:43, 24.24it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3096/8509 [01:27<03:53, 23.22it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3099/8509 [01:27<03:53, 23.15it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3102/8509 [01:27<04:02, 22.31it/s]

embedding (embeddinggemma:latest):  36%|███▋      | 3105/8509 [01:28<03:57, 22.78it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3108/8509 [01:28<03:55, 22.92it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3111/8509 [01:28<04:01, 22.37it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3114/8509 [01:28<03:59, 22.53it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3117/8509 [01:28<04:07, 21.80it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3120/8509 [01:28<04:06, 21.84it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3123/8509 [01:28<03:59, 22.44it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3126/8509 [01:28<03:49, 23.42it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3129/8509 [01:29<03:49, 23.43it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3132/8509 [01:29<03:42, 24.17it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3135/8509 [01:29<03:39, 24.47it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3138/8509 [01:29<03:39, 24.42it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3141/8509 [01:29<03:36, 24.77it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3144/8509 [01:29<03:35, 24.88it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3147/8509 [01:29<03:41, 24.18it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3150/8509 [01:29<03:47, 23.55it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3153/8509 [01:30<03:45, 23.71it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3156/8509 [01:30<03:46, 23.65it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3159/8509 [01:30<03:55, 22.68it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3162/8509 [01:30<03:56, 22.64it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3165/8509 [01:30<03:48, 23.38it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3168/8509 [01:30<03:47, 23.44it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3171/8509 [01:30<03:54, 22.79it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3174/8509 [01:30<03:55, 22.62it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3177/8509 [01:31<03:53, 22.79it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3180/8509 [01:31<03:53, 22.82it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3183/8509 [01:31<03:56, 22.52it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3186/8509 [01:31<03:59, 22.26it/s]

embedding (embeddinggemma:latest):  37%|███▋      | 3189/8509 [01:31<03:56, 22.45it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3192/8509 [01:31<03:55, 22.53it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3195/8509 [01:31<04:00, 22.05it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3198/8509 [01:32<03:55, 22.60it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3201/8509 [01:32<03:46, 23.39it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3204/8509 [01:32<03:43, 23.76it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3207/8509 [01:32<03:44, 23.61it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3210/8509 [01:32<03:53, 22.65it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3213/8509 [01:32<03:50, 22.93it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3216/8509 [01:32<03:49, 23.05it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3219/8509 [01:32<03:49, 23.02it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3222/8509 [01:33<03:49, 23.03it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3225/8509 [01:33<03:47, 23.22it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3228/8509 [01:33<03:54, 22.51it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3231/8509 [01:33<03:47, 23.24it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3234/8509 [01:33<03:43, 23.55it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3237/8509 [01:33<03:40, 23.87it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3240/8509 [01:33<03:40, 23.92it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3243/8509 [01:33<03:40, 23.92it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3246/8509 [01:34<03:38, 24.11it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3249/8509 [01:34<03:38, 24.05it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3252/8509 [01:34<03:39, 23.99it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3255/8509 [01:34<03:41, 23.71it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3258/8509 [01:34<03:37, 24.12it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3261/8509 [01:34<03:35, 24.31it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3264/8509 [01:34<03:39, 23.85it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3267/8509 [01:34<03:42, 23.51it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3270/8509 [01:35<03:41, 23.65it/s]

embedding (embeddinggemma:latest):  38%|███▊      | 3273/8509 [01:35<03:46, 23.13it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3276/8509 [01:35<04:44, 18.39it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3278/8509 [01:35<04:41, 18.60it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3280/8509 [01:35<04:38, 18.80it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3283/8509 [01:35<04:22, 19.88it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3286/8509 [01:35<04:23, 19.85it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3289/8509 [01:36<04:24, 19.74it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3292/8509 [01:36<04:20, 20.06it/s]

embedding (embeddinggemma:latest):  39%|███▊      | 3295/8509 [01:36<04:19, 20.09it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3298/8509 [01:36<04:19, 20.10it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3301/8509 [01:36<04:16, 20.30it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3304/8509 [01:36<04:25, 19.63it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3307/8509 [01:37<04:18, 20.09it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3310/8509 [01:37<04:17, 20.17it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3313/8509 [01:37<04:15, 20.33it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3316/8509 [01:37<04:08, 20.86it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3319/8509 [01:37<04:06, 21.03it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3322/8509 [01:37<04:07, 20.95it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3325/8509 [01:37<04:08, 20.89it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3328/8509 [01:38<03:59, 21.67it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3331/8509 [01:38<04:00, 21.55it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3334/8509 [01:38<04:00, 21.48it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3337/8509 [01:38<04:02, 21.37it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3340/8509 [01:38<04:02, 21.34it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3343/8509 [01:38<04:06, 20.93it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3346/8509 [01:38<04:11, 20.53it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3349/8509 [01:39<04:13, 20.35it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3352/8509 [01:39<04:13, 20.31it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3355/8509 [01:39<04:12, 20.44it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3358/8509 [01:39<04:14, 20.27it/s]

embedding (embeddinggemma:latest):  39%|███▉      | 3361/8509 [01:39<04:08, 20.73it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3364/8509 [01:39<03:58, 21.58it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3367/8509 [01:39<03:55, 21.82it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3370/8509 [01:39<03:53, 21.98it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3373/8509 [01:40<03:55, 21.84it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3376/8509 [01:40<03:50, 22.30it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3379/8509 [01:40<03:53, 21.93it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3382/8509 [01:40<03:53, 21.96it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3385/8509 [01:40<03:55, 21.76it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3388/8509 [01:40<04:00, 21.25it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3391/8509 [01:40<04:02, 21.11it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3394/8509 [01:41<04:01, 21.20it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3397/8509 [01:41<03:55, 21.75it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3400/8509 [01:41<03:51, 22.07it/s]

embedding (embeddinggemma:latest):  40%|███▉      | 3403/8509 [01:41<03:49, 22.27it/s]

embedding (embeddinggemma:latest):  40%|████      | 3406/8509 [01:41<03:46, 22.57it/s]

embedding (embeddinggemma:latest):  40%|████      | 3409/8509 [01:41<03:48, 22.34it/s]

embedding (embeddinggemma:latest):  40%|████      | 3412/8509 [01:41<03:49, 22.17it/s]

embedding (embeddinggemma:latest):  40%|████      | 3415/8509 [01:42<03:57, 21.47it/s]

embedding (embeddinggemma:latest):  40%|████      | 3418/8509 [01:42<03:59, 21.25it/s]

embedding (embeddinggemma:latest):  40%|████      | 3421/8509 [01:42<03:54, 21.67it/s]

embedding (embeddinggemma:latest):  40%|████      | 3424/8509 [01:42<03:49, 22.13it/s]

embedding (embeddinggemma:latest):  40%|████      | 3427/8509 [01:42<03:47, 22.30it/s]

embedding (embeddinggemma:latest):  40%|████      | 3430/8509 [01:42<03:51, 21.92it/s]

embedding (embeddinggemma:latest):  40%|████      | 3433/8509 [01:42<03:52, 21.82it/s]

embedding (embeddinggemma:latest):  40%|████      | 3436/8509 [01:43<03:54, 21.60it/s]

embedding (embeddinggemma:latest):  40%|████      | 3439/8509 [01:43<03:52, 21.77it/s]

embedding (embeddinggemma:latest):  40%|████      | 3442/8509 [01:43<03:45, 22.50it/s]

embedding (embeddinggemma:latest):  40%|████      | 3445/8509 [01:43<03:43, 22.70it/s]

embedding (embeddinggemma:latest):  41%|████      | 3448/8509 [01:43<03:45, 22.45it/s]

embedding (embeddinggemma:latest):  41%|████      | 3451/8509 [01:43<03:44, 22.51it/s]

embedding (embeddinggemma:latest):  41%|████      | 3454/8509 [01:43<03:46, 22.30it/s]

embedding (embeddinggemma:latest):  41%|████      | 3457/8509 [01:43<03:41, 22.83it/s]

embedding (embeddinggemma:latest):  41%|████      | 3460/8509 [01:44<03:39, 23.03it/s]

embedding (embeddinggemma:latest):  41%|████      | 3463/8509 [01:44<03:35, 23.47it/s]

embedding (embeddinggemma:latest):  41%|████      | 3466/8509 [01:44<03:41, 22.73it/s]

embedding (embeddinggemma:latest):  41%|████      | 3469/8509 [01:44<03:43, 22.52it/s]

embedding (embeddinggemma:latest):  41%|████      | 3472/8509 [01:44<03:45, 22.30it/s]

embedding (embeddinggemma:latest):  41%|████      | 3475/8509 [01:44<03:43, 22.53it/s]

embedding (embeddinggemma:latest):  41%|████      | 3478/8509 [01:44<03:45, 22.27it/s]

embedding (embeddinggemma:latest):  41%|████      | 3481/8509 [01:45<03:54, 21.43it/s]

embedding (embeddinggemma:latest):  41%|████      | 3484/8509 [01:45<03:50, 21.77it/s]

embedding (embeddinggemma:latest):  41%|████      | 3487/8509 [01:45<03:52, 21.63it/s]

embedding (embeddinggemma:latest):  41%|████      | 3490/8509 [01:45<03:51, 21.69it/s]

embedding (embeddinggemma:latest):  41%|████      | 3493/8509 [01:45<03:49, 21.90it/s]

embedding (embeddinggemma:latest):  41%|████      | 3496/8509 [01:45<03:41, 22.65it/s]

embedding (embeddinggemma:latest):  41%|████      | 3499/8509 [01:45<03:42, 22.51it/s]

embedding (embeddinggemma:latest):  41%|████      | 3502/8509 [01:45<03:42, 22.47it/s]

embedding (embeddinggemma:latest):  41%|████      | 3505/8509 [01:46<03:43, 22.38it/s]

embedding (embeddinggemma:latest):  41%|████      | 3508/8509 [01:46<03:39, 22.83it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3511/8509 [01:46<03:42, 22.49it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3514/8509 [01:46<03:46, 22.01it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3517/8509 [01:46<03:45, 22.09it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3520/8509 [01:46<03:40, 22.60it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3523/8509 [01:46<03:36, 22.99it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3526/8509 [01:47<03:41, 22.51it/s]

embedding (embeddinggemma:latest):  41%|████▏     | 3529/8509 [01:47<03:39, 22.70it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3532/8509 [01:47<03:33, 23.35it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3535/8509 [01:47<03:31, 23.47it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3538/8509 [01:47<03:34, 23.15it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3541/8509 [01:47<03:31, 23.44it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3544/8509 [01:47<03:36, 22.97it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3547/8509 [01:47<03:36, 22.90it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3550/8509 [01:48<03:37, 22.75it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3553/8509 [01:48<03:41, 22.41it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3556/8509 [01:48<03:41, 22.31it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3559/8509 [01:48<03:43, 22.11it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3562/8509 [01:48<03:43, 22.12it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3565/8509 [01:48<03:39, 22.48it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3568/8509 [01:48<03:38, 22.63it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3571/8509 [01:49<03:47, 21.74it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3574/8509 [01:49<03:45, 21.88it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3577/8509 [01:49<03:46, 21.80it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3580/8509 [01:49<03:44, 21.95it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3583/8509 [01:49<03:49, 21.49it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3586/8509 [01:49<03:52, 21.21it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3589/8509 [01:49<03:44, 21.91it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3592/8509 [01:49<03:37, 22.62it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3595/8509 [01:50<03:38, 22.53it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3598/8509 [01:50<03:36, 22.72it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3601/8509 [01:50<03:36, 22.68it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3604/8509 [01:50<03:33, 23.03it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3607/8509 [01:50<03:30, 23.30it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3610/8509 [01:50<03:24, 23.97it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3613/8509 [01:50<03:24, 23.92it/s]

embedding (embeddinggemma:latest):  42%|████▏     | 3616/8509 [01:50<03:24, 23.93it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3619/8509 [01:51<03:28, 23.46it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3622/8509 [01:51<03:35, 22.68it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3625/8509 [01:51<03:35, 22.70it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3628/8509 [01:51<03:33, 22.90it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3631/8509 [01:51<03:28, 23.38it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3634/8509 [01:51<03:34, 22.75it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3637/8509 [01:51<03:35, 22.63it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3640/8509 [01:52<03:33, 22.80it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3643/8509 [01:52<03:33, 22.80it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3646/8509 [01:52<03:30, 23.06it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3649/8509 [01:52<03:32, 22.92it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3652/8509 [01:52<03:30, 23.04it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3655/8509 [01:52<03:30, 23.09it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3658/8509 [01:52<03:25, 23.65it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3661/8509 [01:52<03:20, 24.15it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3664/8509 [01:53<03:17, 24.47it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3667/8509 [01:53<03:18, 24.35it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3670/8509 [01:53<03:20, 24.18it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3673/8509 [01:53<03:18, 24.39it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3676/8509 [01:53<03:18, 24.29it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3679/8509 [01:53<03:19, 24.23it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3682/8509 [01:53<03:20, 24.07it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3685/8509 [01:53<03:23, 23.75it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3688/8509 [01:54<03:26, 23.38it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3691/8509 [01:54<03:26, 23.28it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3694/8509 [01:54<03:32, 22.64it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3697/8509 [01:54<03:30, 22.86it/s]

embedding (embeddinggemma:latest):  43%|████▎     | 3700/8509 [01:54<03:26, 23.26it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3703/8509 [01:54<03:25, 23.36it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3706/8509 [01:54<03:26, 23.24it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3709/8509 [01:54<03:25, 23.35it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3712/8509 [01:55<03:23, 23.57it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3715/8509 [01:55<03:21, 23.82it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3718/8509 [01:55<03:21, 23.80it/s]

embedding (embeddinggemma:latest):  44%|████▎     | 3721/8509 [01:55<03:26, 23.21it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3724/8509 [01:55<03:26, 23.14it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3727/8509 [01:55<03:28, 22.93it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3730/8509 [01:55<03:29, 22.76it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3733/8509 [01:56<03:27, 22.99it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3736/8509 [01:56<03:31, 22.58it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3739/8509 [01:56<03:34, 22.19it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3742/8509 [01:56<03:36, 22.00it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3745/8509 [01:56<03:29, 22.72it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3748/8509 [01:56<03:30, 22.58it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3751/8509 [01:56<03:29, 22.72it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3754/8509 [01:56<03:28, 22.80it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3757/8509 [01:57<03:33, 22.23it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3760/8509 [01:57<03:31, 22.47it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3763/8509 [01:57<03:27, 22.86it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3766/8509 [01:57<03:25, 23.03it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3769/8509 [01:57<03:28, 22.74it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3772/8509 [01:57<03:25, 23.01it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3775/8509 [01:57<03:29, 22.61it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3778/8509 [01:58<03:27, 22.84it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3781/8509 [01:58<03:30, 22.51it/s]

embedding (embeddinggemma:latest):  44%|████▍     | 3784/8509 [01:58<03:31, 22.34it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3787/8509 [01:58<03:26, 22.88it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3790/8509 [01:58<03:24, 23.08it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3793/8509 [01:58<03:19, 23.59it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3796/8509 [01:58<03:20, 23.48it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3799/8509 [01:58<03:17, 23.88it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3802/8509 [01:59<03:09, 24.81it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3805/8509 [01:59<03:14, 24.20it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3808/8509 [01:59<03:16, 23.92it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3811/8509 [01:59<03:19, 23.50it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3814/8509 [01:59<03:19, 23.54it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3817/8509 [01:59<03:20, 23.41it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3820/8509 [01:59<03:16, 23.82it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3823/8509 [01:59<03:11, 24.43it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3826/8509 [02:00<03:11, 24.52it/s]

embedding (embeddinggemma:latest):  45%|████▍     | 3829/8509 [02:00<03:11, 24.39it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3832/8509 [02:00<03:16, 23.76it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3835/8509 [02:00<03:16, 23.82it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3838/8509 [02:00<03:15, 23.93it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3841/8509 [02:00<03:16, 23.80it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3844/8509 [02:00<03:19, 23.37it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3847/8509 [02:00<03:25, 22.72it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3850/8509 [02:01<03:24, 22.76it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3853/8509 [02:01<03:21, 23.16it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3856/8509 [02:01<03:20, 23.21it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3859/8509 [02:01<03:17, 23.49it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3862/8509 [02:01<03:21, 23.12it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3865/8509 [02:01<03:19, 23.25it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3868/8509 [02:01<03:18, 23.37it/s]

embedding (embeddinggemma:latest):  45%|████▌     | 3871/8509 [02:01<03:23, 22.81it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3874/8509 [02:02<03:21, 22.98it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3877/8509 [02:02<03:25, 22.56it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3880/8509 [02:02<03:27, 22.32it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3883/8509 [02:02<03:25, 22.56it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3886/8509 [02:02<03:25, 22.53it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3889/8509 [02:02<03:29, 22.03it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3892/8509 [02:02<03:32, 21.68it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3895/8509 [02:03<03:36, 21.34it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3898/8509 [02:03<03:33, 21.64it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3901/8509 [02:03<03:25, 22.46it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3904/8509 [02:03<03:17, 23.35it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3907/8509 [02:03<03:14, 23.61it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3910/8509 [02:03<03:14, 23.70it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3913/8509 [02:03<03:15, 23.49it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3916/8509 [02:03<03:21, 22.81it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3919/8509 [02:04<03:25, 22.30it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3922/8509 [02:04<03:27, 22.15it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3925/8509 [02:04<03:32, 21.61it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3928/8509 [02:04<03:32, 21.61it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3931/8509 [02:04<03:30, 21.71it/s]

embedding (embeddinggemma:latest):  46%|████▌     | 3934/8509 [02:04<03:31, 21.66it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3937/8509 [02:04<03:26, 22.17it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3940/8509 [02:05<03:28, 21.95it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3943/8509 [02:05<03:32, 21.46it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3946/8509 [02:05<03:40, 20.74it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3949/8509 [02:05<03:38, 20.84it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3952/8509 [02:05<03:32, 21.46it/s]

embedding (embeddinggemma:latest):  46%|████▋     | 3955/8509 [02:05<03:28, 21.85it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3958/8509 [02:05<03:27, 21.98it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3961/8509 [02:06<03:26, 22.00it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3964/8509 [02:06<03:23, 22.34it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3967/8509 [02:06<03:24, 22.26it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3970/8509 [02:06<03:24, 22.19it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3973/8509 [02:06<03:23, 22.27it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3976/8509 [02:06<03:20, 22.63it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3979/8509 [02:06<03:17, 22.92it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3982/8509 [02:06<03:16, 23.05it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3985/8509 [02:07<03:16, 23.01it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3988/8509 [02:07<03:19, 22.62it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3991/8509 [02:07<03:19, 22.66it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3994/8509 [02:07<03:19, 22.59it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 3997/8509 [02:07<03:17, 22.89it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4000/8509 [02:07<03:19, 22.61it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4003/8509 [02:07<03:21, 22.35it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4006/8509 [02:08<03:16, 22.87it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4009/8509 [02:08<03:11, 23.47it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4012/8509 [02:08<03:08, 23.92it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4015/8509 [02:08<03:11, 23.52it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4018/8509 [02:08<03:16, 22.83it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4021/8509 [02:08<03:19, 22.54it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4024/8509 [02:08<03:16, 22.80it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4027/8509 [02:08<03:21, 22.25it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4030/8509 [02:09<03:18, 22.54it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4033/8509 [02:09<03:15, 22.93it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4036/8509 [02:09<03:20, 22.28it/s]

embedding (embeddinggemma:latest):  47%|████▋     | 4039/8509 [02:09<03:26, 21.60it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4042/8509 [02:09<03:22, 22.07it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4045/8509 [02:09<03:21, 22.19it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4048/8509 [02:09<03:20, 22.23it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4051/8509 [02:10<03:19, 22.37it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4054/8509 [02:10<03:28, 21.33it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4057/8509 [02:10<03:29, 21.22it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4060/8509 [02:10<03:29, 21.24it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4063/8509 [02:10<03:30, 21.10it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4066/8509 [02:10<03:32, 20.95it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4069/8509 [02:10<03:30, 21.08it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4072/8509 [02:11<03:28, 21.30it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4075/8509 [02:11<03:23, 21.83it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4078/8509 [02:11<03:22, 21.93it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4081/8509 [02:11<03:24, 21.62it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4084/8509 [02:11<03:21, 21.91it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4087/8509 [02:11<03:20, 22.05it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4090/8509 [02:11<03:23, 21.69it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4093/8509 [02:11<03:21, 21.91it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4096/8509 [02:12<03:21, 21.86it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4099/8509 [02:12<03:23, 21.70it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4102/8509 [02:12<03:22, 21.81it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4105/8509 [02:12<03:19, 22.09it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4108/8509 [02:12<03:19, 22.07it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4111/8509 [02:12<03:18, 22.18it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4114/8509 [02:12<03:17, 22.26it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4117/8509 [02:13<03:17, 22.26it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4120/8509 [02:13<03:13, 22.72it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4123/8509 [02:13<03:16, 22.27it/s]

embedding (embeddinggemma:latest):  48%|████▊     | 4126/8509 [02:13<03:15, 22.43it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4129/8509 [02:13<03:14, 22.53it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4132/8509 [02:13<03:16, 22.28it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4135/8509 [02:13<03:16, 22.28it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4138/8509 [02:14<03:19, 21.94it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4141/8509 [02:14<03:17, 22.15it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4144/8509 [02:14<03:14, 22.49it/s]

embedding (embeddinggemma:latest):  49%|████▊     | 4147/8509 [02:14<03:16, 22.17it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4150/8509 [02:14<03:19, 21.82it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4153/8509 [02:14<03:18, 21.96it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4156/8509 [02:14<03:22, 21.55it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4159/8509 [02:14<03:24, 21.30it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4162/8509 [02:15<03:25, 21.17it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4165/8509 [02:15<03:26, 21.00it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4168/8509 [02:15<03:32, 20.39it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4171/8509 [02:15<03:30, 20.65it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4174/8509 [02:15<03:21, 21.50it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4177/8509 [02:15<03:23, 21.26it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4180/8509 [02:15<03:27, 20.83it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4183/8509 [02:16<03:24, 21.14it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4186/8509 [02:16<03:23, 21.28it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4189/8509 [02:16<03:21, 21.43it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4192/8509 [02:16<03:16, 21.99it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4195/8509 [02:16<03:12, 22.41it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4198/8509 [02:16<03:12, 22.36it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4201/8509 [02:16<03:15, 21.99it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4204/8509 [02:17<03:18, 21.72it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4207/8509 [02:17<03:15, 21.98it/s]

embedding (embeddinggemma:latest):  49%|████▉     | 4210/8509 [02:17<03:16, 21.93it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4213/8509 [02:17<03:12, 22.34it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4216/8509 [02:17<03:10, 22.56it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4219/8509 [02:17<03:09, 22.68it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4222/8509 [02:17<03:06, 22.93it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4225/8509 [02:17<03:06, 22.96it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4228/8509 [02:18<03:09, 22.55it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4231/8509 [02:18<03:15, 21.93it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4234/8509 [02:18<03:14, 21.95it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4237/8509 [02:18<03:11, 22.26it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4240/8509 [02:18<03:08, 22.62it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4243/8509 [02:18<03:08, 22.62it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4246/8509 [02:18<03:05, 22.97it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4249/8509 [02:19<03:03, 23.27it/s]

embedding (embeddinggemma:latest):  50%|████▉     | 4252/8509 [02:19<03:06, 22.86it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4255/8509 [02:19<03:10, 22.31it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4258/8509 [02:19<03:10, 22.28it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4261/8509 [02:19<03:08, 22.48it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4264/8509 [02:19<03:09, 22.36it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4267/8509 [02:19<03:11, 22.15it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4270/8509 [02:20<03:15, 21.72it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4273/8509 [02:20<03:06, 22.77it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4276/8509 [02:20<03:05, 22.82it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4279/8509 [02:20<03:02, 23.19it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4282/8509 [02:20<03:04, 22.92it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4285/8509 [02:20<03:08, 22.39it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4288/8509 [02:20<03:13, 21.82it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4291/8509 [02:20<03:20, 21.09it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4294/8509 [02:21<03:18, 21.21it/s]

embedding (embeddinggemma:latest):  50%|█████     | 4297/8509 [02:21<03:26, 20.36it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4300/8509 [02:21<03:23, 20.65it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4303/8509 [02:21<03:25, 20.49it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4306/8509 [02:21<03:17, 21.27it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4309/8509 [02:21<03:16, 21.42it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4312/8509 [02:21<03:17, 21.25it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4315/8509 [02:22<03:13, 21.66it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4318/8509 [02:22<03:11, 21.87it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4321/8509 [02:22<03:04, 22.65it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4324/8509 [02:22<03:02, 22.97it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4327/8509 [02:22<02:58, 23.46it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4330/8509 [02:22<02:54, 23.94it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4333/8509 [02:22<02:54, 23.91it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4336/8509 [02:22<02:56, 23.70it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4339/8509 [02:23<02:59, 23.19it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4342/8509 [02:23<02:58, 23.38it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4345/8509 [02:23<02:59, 23.22it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4348/8509 [02:23<02:59, 23.23it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4351/8509 [02:23<03:01, 22.94it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4354/8509 [02:23<03:02, 22.72it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4357/8509 [02:23<03:04, 22.44it/s]

embedding (embeddinggemma:latest):  51%|█████     | 4360/8509 [02:24<03:00, 22.97it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4363/8509 [02:24<02:54, 23.74it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4366/8509 [02:24<02:51, 24.21it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4369/8509 [02:24<02:48, 24.56it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4372/8509 [02:24<02:54, 23.72it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4375/8509 [02:24<02:57, 23.31it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4378/8509 [02:24<02:55, 23.56it/s]

embedding (embeddinggemma:latest):  51%|█████▏    | 4381/8509 [02:24<02:59, 23.04it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4384/8509 [02:25<02:57, 23.23it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4387/8509 [02:25<02:55, 23.48it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4390/8509 [02:25<02:54, 23.61it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4393/8509 [02:25<02:49, 24.24it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4396/8509 [02:25<02:49, 24.28it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4399/8509 [02:25<02:47, 24.49it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4402/8509 [02:25<02:49, 24.27it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4405/8509 [02:25<02:52, 23.79it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4408/8509 [02:26<02:56, 23.20it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4411/8509 [02:26<02:54, 23.45it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4414/8509 [02:26<02:49, 24.14it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4417/8509 [02:26<02:49, 24.10it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4420/8509 [02:26<02:47, 24.36it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4423/8509 [02:26<02:44, 24.86it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4426/8509 [02:26<02:49, 24.05it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4429/8509 [02:26<02:49, 24.07it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4432/8509 [02:27<02:52, 23.69it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4435/8509 [02:27<02:53, 23.48it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4438/8509 [02:27<02:52, 23.67it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4441/8509 [02:27<02:47, 24.27it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4444/8509 [02:27<02:49, 23.91it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4447/8509 [02:27<02:51, 23.70it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4450/8509 [02:27<02:52, 23.47it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4453/8509 [02:27<02:52, 23.45it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4456/8509 [02:28<02:51, 23.57it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4459/8509 [02:28<02:47, 24.16it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4462/8509 [02:28<02:44, 24.55it/s]

embedding (embeddinggemma:latest):  52%|█████▏    | 4465/8509 [02:28<02:50, 23.69it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4468/8509 [02:28<02:55, 23.07it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4471/8509 [02:28<02:54, 23.11it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4474/8509 [02:28<02:58, 22.66it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4477/8509 [02:28<03:00, 22.38it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4480/8509 [02:29<03:00, 22.37it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4483/8509 [02:29<02:58, 22.60it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4486/8509 [02:29<03:00, 22.26it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4489/8509 [02:29<03:05, 21.62it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4492/8509 [02:29<03:03, 21.88it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4495/8509 [02:29<03:03, 21.83it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4498/8509 [02:29<03:03, 21.90it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4501/8509 [02:30<03:06, 21.52it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4504/8509 [02:30<03:02, 22.00it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4507/8509 [02:30<03:04, 21.75it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4510/8509 [02:30<03:04, 21.67it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4513/8509 [02:30<02:59, 22.20it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4516/8509 [02:30<02:56, 22.65it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4519/8509 [02:30<02:59, 22.24it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4522/8509 [02:31<03:01, 21.92it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4525/8509 [02:31<03:00, 22.04it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4528/8509 [02:31<02:59, 22.16it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4531/8509 [02:31<02:58, 22.28it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4534/8509 [02:31<02:53, 22.95it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4537/8509 [02:31<02:52, 23.09it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4540/8509 [02:31<02:53, 22.87it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4543/8509 [02:31<02:57, 22.34it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4546/8509 [02:32<02:58, 22.15it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4549/8509 [02:32<02:56, 22.46it/s]

embedding (embeddinggemma:latest):  53%|█████▎    | 4552/8509 [02:32<02:54, 22.74it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4555/8509 [02:32<02:53, 22.83it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4558/8509 [02:32<02:53, 22.81it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4561/8509 [02:32<02:51, 23.06it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4564/8509 [02:32<02:52, 22.93it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4567/8509 [02:32<02:55, 22.50it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4570/8509 [02:33<02:55, 22.49it/s]

embedding (embeddinggemma:latest):  54%|█████▎    | 4573/8509 [02:33<02:48, 23.33it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4576/8509 [02:33<02:46, 23.55it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4579/8509 [02:33<02:48, 23.34it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4582/8509 [02:33<02:51, 22.93it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4585/8509 [02:33<02:55, 22.38it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4588/8509 [02:33<03:01, 21.64it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4591/8509 [02:34<03:08, 20.79it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4594/8509 [02:34<03:04, 21.22it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4597/8509 [02:34<03:07, 20.86it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4600/8509 [02:34<03:01, 21.53it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4603/8509 [02:34<03:02, 21.40it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4606/8509 [02:34<02:57, 21.98it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4609/8509 [02:34<03:00, 21.62it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4612/8509 [02:35<03:00, 21.61it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4615/8509 [02:35<03:04, 21.08it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4618/8509 [02:35<03:04, 21.08it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4621/8509 [02:35<03:00, 21.52it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4624/8509 [02:35<02:57, 21.87it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4627/8509 [02:35<02:52, 22.47it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4630/8509 [02:35<02:49, 22.84it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4633/8509 [02:35<02:46, 23.28it/s]

embedding (embeddinggemma:latest):  54%|█████▍    | 4636/8509 [02:36<02:47, 23.17it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4639/8509 [02:36<02:47, 23.06it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4642/8509 [02:36<02:53, 22.31it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4645/8509 [02:36<02:53, 22.24it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4648/8509 [02:36<02:56, 21.89it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4651/8509 [02:36<02:49, 22.77it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4654/8509 [02:36<02:46, 23.12it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4657/8509 [02:37<02:46, 23.19it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4660/8509 [02:37<02:46, 23.12it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4663/8509 [02:37<02:49, 22.73it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4666/8509 [02:37<02:56, 21.80it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4669/8509 [02:37<03:02, 21.05it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4672/8509 [02:37<03:04, 20.81it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4675/8509 [02:37<03:08, 20.33it/s]

embedding (embeddinggemma:latest):  55%|█████▍    | 4678/8509 [02:38<03:04, 20.73it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4681/8509 [02:38<03:06, 20.48it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4684/8509 [02:38<03:04, 20.72it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4687/8509 [02:38<02:59, 21.34it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4690/8509 [02:38<02:57, 21.54it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4693/8509 [02:38<02:54, 21.85it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4696/8509 [02:38<02:49, 22.49it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4699/8509 [02:39<02:54, 21.85it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4702/8509 [02:39<02:52, 22.09it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4705/8509 [02:39<02:53, 21.89it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4708/8509 [02:39<02:54, 21.84it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4711/8509 [02:39<02:56, 21.52it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4714/8509 [02:39<02:54, 21.70it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4717/8509 [02:39<02:51, 22.06it/s]

embedding (embeddinggemma:latest):  55%|█████▌    | 4720/8509 [02:39<02:48, 22.52it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4723/8509 [02:40<02:49, 22.29it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4726/8509 [02:40<02:49, 22.29it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4729/8509 [02:40<02:51, 21.98it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4732/8509 [02:40<02:52, 21.89it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4735/8509 [02:40<02:52, 21.82it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4738/8509 [02:40<02:54, 21.61it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4741/8509 [02:40<02:58, 21.15it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4744/8509 [02:41<03:00, 20.86it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4747/8509 [02:41<02:55, 21.40it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4750/8509 [02:41<02:58, 21.07it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4753/8509 [02:41<02:54, 21.48it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4756/8509 [02:41<02:45, 22.61it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4759/8509 [02:41<02:38, 23.62it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4762/8509 [02:41<02:35, 24.06it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4765/8509 [02:41<02:34, 24.28it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4768/8509 [02:42<02:33, 24.36it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4771/8509 [02:42<02:36, 23.87it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4774/8509 [02:42<02:37, 23.74it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4777/8509 [02:42<02:40, 23.26it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4780/8509 [02:42<02:41, 23.04it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4783/8509 [02:42<02:39, 23.43it/s]

embedding (embeddinggemma:latest):  56%|█████▌    | 4786/8509 [02:42<02:34, 24.16it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4789/8509 [02:42<02:33, 24.20it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4792/8509 [02:43<02:36, 23.78it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4795/8509 [02:43<02:39, 23.32it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4798/8509 [02:43<02:42, 22.90it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4801/8509 [02:43<02:43, 22.72it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4804/8509 [02:43<02:46, 22.29it/s]

embedding (embeddinggemma:latest):  56%|█████▋    | 4807/8509 [02:43<02:46, 22.28it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4810/8509 [02:43<02:43, 22.67it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4813/8509 [02:44<02:43, 22.61it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4816/8509 [02:44<02:39, 23.11it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4819/8509 [02:44<02:36, 23.55it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4822/8509 [02:44<02:31, 24.35it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4825/8509 [02:44<02:36, 23.58it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4828/8509 [02:44<02:38, 23.24it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4831/8509 [02:44<02:37, 23.39it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4834/8509 [02:44<02:34, 23.74it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4837/8509 [02:45<02:33, 23.85it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4840/8509 [02:45<02:33, 23.87it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4843/8509 [02:45<02:37, 23.24it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4846/8509 [02:45<02:38, 23.15it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4849/8509 [02:45<02:38, 23.09it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4852/8509 [02:45<02:41, 22.62it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4855/8509 [02:45<02:41, 22.58it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4858/8509 [02:45<02:44, 22.20it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4861/8509 [02:46<02:44, 22.17it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4864/8509 [02:46<02:42, 22.44it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4867/8509 [02:46<02:44, 22.09it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4870/8509 [02:46<02:43, 22.23it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4873/8509 [02:46<02:40, 22.67it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4876/8509 [02:46<02:37, 23.02it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4879/8509 [02:46<02:34, 23.48it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4882/8509 [02:47<02:37, 23.08it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4885/8509 [02:47<02:34, 23.44it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4888/8509 [02:47<02:32, 23.81it/s]

embedding (embeddinggemma:latest):  57%|█████▋    | 4891/8509 [02:47<02:29, 24.23it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4894/8509 [02:47<02:30, 23.96it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4897/8509 [02:47<02:30, 23.92it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4900/8509 [02:47<02:27, 24.53it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4903/8509 [02:47<02:29, 24.10it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4906/8509 [02:48<02:30, 23.93it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4909/8509 [02:48<02:29, 24.03it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4912/8509 [02:48<02:33, 23.36it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4915/8509 [02:48<02:33, 23.36it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4918/8509 [02:48<02:32, 23.55it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4921/8509 [02:48<02:34, 23.18it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4924/8509 [02:48<02:38, 22.57it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4927/8509 [02:48<02:42, 22.11it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4930/8509 [02:49<02:40, 22.26it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4933/8509 [02:49<02:39, 22.40it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4936/8509 [02:49<02:41, 22.15it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4939/8509 [02:49<02:40, 22.24it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4942/8509 [02:49<02:39, 22.29it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4945/8509 [02:49<02:40, 22.27it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4948/8509 [02:49<02:39, 22.35it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4951/8509 [02:50<02:35, 22.87it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4954/8509 [02:50<02:39, 22.32it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4957/8509 [02:50<02:45, 21.48it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4960/8509 [02:50<02:49, 20.94it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4963/8509 [02:50<02:52, 20.58it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4966/8509 [02:50<02:48, 21.04it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4969/8509 [02:50<02:47, 21.07it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4972/8509 [02:51<02:49, 20.81it/s]

embedding (embeddinggemma:latest):  58%|█████▊    | 4975/8509 [02:51<02:51, 20.61it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4978/8509 [02:51<02:46, 21.20it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4981/8509 [02:51<02:41, 21.91it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4984/8509 [02:51<02:40, 21.91it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4987/8509 [02:51<02:41, 21.81it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4990/8509 [02:51<02:41, 21.81it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4993/8509 [02:52<02:40, 21.97it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4996/8509 [02:52<02:32, 23.03it/s]

embedding (embeddinggemma:latest):  59%|█████▊    | 4999/8509 [02:52<02:30, 23.39it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5002/8509 [02:52<02:25, 24.13it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5005/8509 [02:52<02:27, 23.83it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5008/8509 [02:52<02:26, 23.96it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5011/8509 [02:52<02:32, 22.96it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5014/8509 [02:52<02:32, 22.89it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5017/8509 [02:53<02:32, 22.92it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5020/8509 [02:53<02:33, 22.67it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5023/8509 [02:53<02:36, 22.31it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5026/8509 [02:53<02:34, 22.51it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5029/8509 [02:53<02:30, 23.13it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5032/8509 [02:53<02:25, 23.88it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5035/8509 [02:53<02:25, 23.84it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5038/8509 [02:53<02:25, 23.87it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5041/8509 [02:54<02:23, 24.22it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5044/8509 [02:54<02:21, 24.53it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5047/8509 [02:54<02:22, 24.27it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5050/8509 [02:54<02:28, 23.34it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5053/8509 [02:54<02:30, 23.00it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5056/8509 [02:54<02:30, 22.97it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5059/8509 [02:54<02:33, 22.54it/s]

embedding (embeddinggemma:latest):  59%|█████▉    | 5062/8509 [02:54<02:35, 22.20it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5065/8509 [02:55<02:34, 22.30it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5068/8509 [02:55<02:36, 21.92it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5071/8509 [02:55<02:36, 21.97it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5074/8509 [02:55<02:36, 22.02it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5077/8509 [02:55<02:37, 21.76it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5080/8509 [02:55<02:34, 22.26it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5083/8509 [02:55<02:31, 22.68it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5086/8509 [02:56<02:27, 23.25it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5089/8509 [02:56<02:22, 23.99it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5092/8509 [02:56<02:22, 23.96it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5095/8509 [02:56<02:21, 24.11it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5098/8509 [02:56<02:23, 23.84it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5101/8509 [02:56<02:27, 23.08it/s]

embedding (embeddinggemma:latest):  60%|█████▉    | 5104/8509 [02:56<02:25, 23.37it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5107/8509 [02:56<02:22, 23.95it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5110/8509 [02:57<02:21, 24.08it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5113/8509 [02:57<02:19, 24.35it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5116/8509 [02:57<02:19, 24.29it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5119/8509 [02:57<02:18, 24.56it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5122/8509 [02:57<02:20, 24.06it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5125/8509 [02:57<02:20, 24.11it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5128/8509 [02:57<02:20, 24.09it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5131/8509 [02:57<02:23, 23.54it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5134/8509 [02:58<02:28, 22.80it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5137/8509 [02:58<02:27, 22.88it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5140/8509 [02:58<02:26, 23.07it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5143/8509 [02:58<02:33, 21.95it/s]

embedding (embeddinggemma:latest):  60%|██████    | 5146/8509 [02:58<02:31, 22.22it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5149/8509 [02:58<02:30, 22.37it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5152/8509 [02:58<02:34, 21.80it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5155/8509 [02:58<02:26, 22.82it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5158/8509 [02:59<02:29, 22.47it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5161/8509 [02:59<02:26, 22.90it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5164/8509 [02:59<02:24, 23.14it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5167/8509 [02:59<02:24, 23.11it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5170/8509 [02:59<02:24, 23.11it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5173/8509 [02:59<02:23, 23.27it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5176/8509 [02:59<02:24, 23.07it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5179/8509 [03:00<02:21, 23.54it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5182/8509 [03:00<02:21, 23.53it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5185/8509 [03:00<02:21, 23.41it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5188/8509 [03:00<02:23, 23.08it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5191/8509 [03:00<02:25, 22.84it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5194/8509 [03:00<02:22, 23.24it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5197/8509 [03:00<02:23, 23.11it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5200/8509 [03:00<02:25, 22.77it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5203/8509 [03:01<02:28, 22.26it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5206/8509 [03:01<02:26, 22.51it/s]

embedding (embeddinggemma:latest):  61%|██████    | 5209/8509 [03:01<02:28, 22.20it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5212/8509 [03:01<02:32, 21.58it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5215/8509 [03:01<02:31, 21.74it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5218/8509 [03:01<02:26, 22.47it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5221/8509 [03:01<02:24, 22.70it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5224/8509 [03:01<02:23, 22.95it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5227/8509 [03:02<02:22, 22.96it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5230/8509 [03:02<02:22, 23.02it/s]

embedding (embeddinggemma:latest):  61%|██████▏   | 5233/8509 [03:02<02:23, 22.90it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5236/8509 [03:02<02:24, 22.71it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5239/8509 [03:02<02:24, 22.60it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5242/8509 [03:02<02:21, 23.01it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5245/8509 [03:02<02:17, 23.80it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5248/8509 [03:03<02:14, 24.16it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5251/8509 [03:03<02:11, 24.68it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5254/8509 [03:03<02:14, 24.12it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5257/8509 [03:03<02:18, 23.41it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5260/8509 [03:03<02:20, 23.16it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5263/8509 [03:03<02:21, 22.96it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5266/8509 [03:03<02:22, 22.81it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5269/8509 [03:03<02:22, 22.68it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5272/8509 [03:04<02:23, 22.60it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5275/8509 [03:04<02:21, 22.86it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5278/8509 [03:04<02:20, 23.06it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5281/8509 [03:04<02:23, 22.43it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5284/8509 [03:04<02:21, 22.77it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5287/8509 [03:04<02:24, 22.33it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5290/8509 [03:04<02:31, 21.21it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5293/8509 [03:05<02:31, 21.22it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5296/8509 [03:05<02:32, 21.03it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5299/8509 [03:05<02:30, 21.38it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5302/8509 [03:05<02:28, 21.62it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5305/8509 [03:05<02:25, 22.05it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5308/8509 [03:05<02:18, 23.06it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5311/8509 [03:05<02:17, 23.27it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5314/8509 [03:05<02:16, 23.40it/s]

embedding (embeddinggemma:latest):  62%|██████▏   | 5317/8509 [03:06<02:16, 23.44it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5320/8509 [03:06<02:14, 23.73it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5323/8509 [03:06<02:11, 24.21it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5326/8509 [03:06<02:09, 24.60it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5329/8509 [03:06<02:06, 25.16it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5332/8509 [03:06<02:08, 24.63it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5335/8509 [03:06<02:11, 24.15it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5338/8509 [03:06<02:11, 24.14it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5341/8509 [03:07<02:13, 23.80it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5344/8509 [03:07<02:09, 24.48it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5347/8509 [03:07<02:11, 24.12it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5350/8509 [03:07<02:17, 23.05it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5353/8509 [03:07<02:19, 22.58it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5356/8509 [03:07<02:21, 22.27it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5359/8509 [03:07<02:23, 22.02it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5362/8509 [03:07<02:21, 22.24it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5365/8509 [03:08<02:23, 21.84it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5368/8509 [03:08<02:23, 21.96it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5371/8509 [03:08<02:22, 22.07it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5374/8509 [03:08<02:19, 22.53it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5377/8509 [03:08<02:20, 22.32it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5380/8509 [03:08<02:28, 21.13it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5383/8509 [03:08<02:24, 21.62it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5386/8509 [03:09<02:23, 21.82it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5389/8509 [03:09<02:22, 21.84it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5392/8509 [03:09<02:27, 21.19it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5395/8509 [03:09<02:29, 20.78it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5398/8509 [03:09<02:26, 21.17it/s]

embedding (embeddinggemma:latest):  63%|██████▎   | 5401/8509 [03:09<02:29, 20.78it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5404/8509 [03:09<02:27, 20.98it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5407/8509 [03:10<02:28, 20.84it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5410/8509 [03:10<02:25, 21.30it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5413/8509 [03:10<02:26, 21.17it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5416/8509 [03:10<02:23, 21.48it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5419/8509 [03:10<02:22, 21.66it/s]

embedding (embeddinggemma:latest):  64%|██████▎   | 5422/8509 [03:10<02:19, 22.09it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5425/8509 [03:10<02:18, 22.33it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5428/8509 [03:11<02:19, 22.16it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5431/8509 [03:11<02:18, 22.15it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5434/8509 [03:11<02:18, 22.26it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5437/8509 [03:11<02:13, 22.93it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5440/8509 [03:11<02:12, 23.20it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5443/8509 [03:11<02:11, 23.38it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5446/8509 [03:11<02:10, 23.51it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5449/8509 [03:11<02:09, 23.68it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5452/8509 [03:12<02:09, 23.64it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5455/8509 [03:12<02:08, 23.75it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5458/8509 [03:12<02:03, 24.63it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5461/8509 [03:12<02:03, 24.63it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5464/8509 [03:12<02:04, 24.47it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5467/8509 [03:12<02:03, 24.65it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5470/8509 [03:12<02:03, 24.61it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5473/8509 [03:12<02:03, 24.58it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5476/8509 [03:13<02:01, 25.00it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5479/8509 [03:13<02:01, 25.00it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5482/8509 [03:13<02:03, 24.44it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5485/8509 [03:13<02:05, 24.13it/s]

embedding (embeddinggemma:latest):  64%|██████▍   | 5488/8509 [03:13<02:07, 23.72it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5491/8509 [03:13<02:07, 23.72it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5494/8509 [03:13<02:11, 22.87it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5497/8509 [03:13<02:17, 21.94it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5500/8509 [03:14<02:23, 20.96it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5503/8509 [03:14<02:19, 21.48it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5506/8509 [03:14<02:19, 21.52it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5509/8509 [03:14<02:16, 22.04it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5512/8509 [03:14<02:15, 22.08it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5515/8509 [03:14<02:11, 22.75it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5518/8509 [03:14<02:06, 23.61it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5521/8509 [03:15<02:02, 24.42it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5524/8509 [03:15<02:01, 24.50it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5527/8509 [03:15<02:03, 24.10it/s]

embedding (embeddinggemma:latest):  65%|██████▍   | 5530/8509 [03:15<02:01, 24.59it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5533/8509 [03:15<02:01, 24.56it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5536/8509 [03:15<02:01, 24.41it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5539/8509 [03:15<02:02, 24.16it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5542/8509 [03:15<02:03, 23.95it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5545/8509 [03:16<02:02, 24.23it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5548/8509 [03:16<02:00, 24.49it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5551/8509 [03:16<02:00, 24.57it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5554/8509 [03:16<01:59, 24.65it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5557/8509 [03:16<01:58, 24.98it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5560/8509 [03:16<01:58, 24.86it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5563/8509 [03:16<01:58, 24.92it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5566/8509 [03:16<02:01, 24.31it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5569/8509 [03:16<02:02, 24.04it/s]

embedding (embeddinggemma:latest):  65%|██████▌   | 5572/8509 [03:17<02:07, 23.09it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5575/8509 [03:17<02:10, 22.53it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5578/8509 [03:17<02:11, 22.28it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5581/8509 [03:17<02:08, 22.74it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5584/8509 [03:17<02:06, 23.12it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5587/8509 [03:17<02:07, 22.84it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5590/8509 [03:17<02:05, 23.17it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5593/8509 [03:18<02:05, 23.30it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5596/8509 [03:18<02:05, 23.13it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5599/8509 [03:18<02:10, 22.29it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5602/8509 [03:18<02:13, 21.84it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5605/8509 [03:18<02:13, 21.79it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5608/8509 [03:18<02:11, 22.04it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5611/8509 [03:18<02:11, 21.96it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5614/8509 [03:18<02:10, 22.23it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5617/8509 [03:19<02:10, 22.19it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5620/8509 [03:19<02:10, 22.11it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5623/8509 [03:19<02:12, 21.71it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5626/8509 [03:19<02:11, 21.88it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5629/8509 [03:19<02:12, 21.69it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5632/8509 [03:19<02:12, 21.78it/s]

embedding (embeddinggemma:latest):  66%|██████▌   | 5635/8509 [03:19<02:10, 22.09it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5638/8509 [03:20<02:12, 21.59it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5641/8509 [03:20<02:12, 21.67it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5644/8509 [03:20<02:11, 21.72it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5647/8509 [03:20<02:14, 21.23it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5650/8509 [03:20<02:12, 21.61it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5653/8509 [03:20<02:08, 22.16it/s]

embedding (embeddinggemma:latest):  66%|██████▋   | 5656/8509 [03:20<02:05, 22.80it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5659/8509 [03:21<02:03, 23.16it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5662/8509 [03:21<02:00, 23.57it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5665/8509 [03:21<02:00, 23.57it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5668/8509 [03:21<02:00, 23.66it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5671/8509 [03:21<01:59, 23.82it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5674/8509 [03:21<01:58, 23.87it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5677/8509 [03:21<01:56, 24.34it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5680/8509 [03:21<01:57, 24.02it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5683/8509 [03:22<01:58, 23.86it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5686/8509 [03:22<01:58, 23.80it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5689/8509 [03:22<01:58, 23.80it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5692/8509 [03:22<01:59, 23.63it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5695/8509 [03:22<01:57, 23.89it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5698/8509 [03:22<01:57, 23.91it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5701/8509 [03:22<01:54, 24.43it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5704/8509 [03:22<01:56, 24.06it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5707/8509 [03:23<01:56, 23.95it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5710/8509 [03:23<01:57, 23.91it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5713/8509 [03:23<01:55, 24.19it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5716/8509 [03:23<01:51, 24.98it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5719/8509 [03:23<01:52, 24.82it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5722/8509 [03:23<01:52, 24.88it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5725/8509 [03:23<01:55, 24.10it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5728/8509 [03:23<01:56, 23.96it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5731/8509 [03:24<01:55, 23.97it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5734/8509 [03:24<01:54, 24.18it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5737/8509 [03:24<01:54, 24.12it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5740/8509 [03:24<01:54, 24.12it/s]

embedding (embeddinggemma:latest):  67%|██████▋   | 5743/8509 [03:24<01:58, 23.26it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5746/8509 [03:24<01:56, 23.78it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5749/8509 [03:24<02:00, 22.86it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5752/8509 [03:24<02:02, 22.58it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5755/8509 [03:25<02:03, 22.32it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5758/8509 [03:25<02:03, 22.24it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5761/8509 [03:25<02:03, 22.25it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5764/8509 [03:25<01:59, 22.92it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5767/8509 [03:25<01:57, 23.34it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5770/8509 [03:25<01:54, 23.83it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5773/8509 [03:25<01:50, 24.69it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5776/8509 [03:25<01:49, 24.86it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5779/8509 [03:26<01:51, 24.51it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5782/8509 [03:26<01:51, 24.48it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5785/8509 [03:26<01:55, 23.65it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5788/8509 [03:26<01:54, 23.79it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5791/8509 [03:26<01:51, 24.32it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5794/8509 [03:26<01:51, 24.39it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5797/8509 [03:26<01:51, 24.37it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5800/8509 [03:26<01:52, 24.19it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5803/8509 [03:27<01:52, 24.01it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5806/8509 [03:27<01:56, 23.17it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5809/8509 [03:27<01:58, 22.75it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5812/8509 [03:27<02:00, 22.36it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5815/8509 [03:27<02:01, 22.09it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5818/8509 [03:27<01:58, 22.63it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5821/8509 [03:27<01:54, 23.49it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5824/8509 [03:27<01:52, 23.82it/s]

embedding (embeddinggemma:latest):  68%|██████▊   | 5827/8509 [03:28<01:49, 24.44it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5830/8509 [03:28<01:50, 24.34it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5833/8509 [03:28<01:49, 24.50it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5836/8509 [03:28<01:48, 24.70it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5839/8509 [03:28<01:48, 24.64it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5842/8509 [03:28<01:44, 25.62it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5845/8509 [03:28<01:47, 24.83it/s]

embedding (embeddinggemma:latest):  69%|██████▊   | 5848/8509 [03:28<01:47, 24.68it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5851/8509 [03:29<01:46, 25.03it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5854/8509 [03:29<01:46, 24.93it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5857/8509 [03:29<01:46, 24.84it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5860/8509 [03:29<01:46, 24.91it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5863/8509 [03:29<01:47, 24.66it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5866/8509 [03:29<01:48, 24.39it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5869/8509 [03:29<01:50, 23.84it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5872/8509 [03:29<01:51, 23.58it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5875/8509 [03:30<01:51, 23.57it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5878/8509 [03:30<01:51, 23.53it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5881/8509 [03:30<01:52, 23.34it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5884/8509 [03:30<01:52, 23.23it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5887/8509 [03:30<01:53, 23.11it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5890/8509 [03:30<01:52, 23.21it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5893/8509 [03:30<01:54, 22.81it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5896/8509 [03:30<01:53, 23.04it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5899/8509 [03:31<01:53, 23.06it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5902/8509 [03:31<01:50, 23.52it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5905/8509 [03:31<01:50, 23.67it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5908/8509 [03:31<01:50, 23.50it/s]

embedding (embeddinggemma:latest):  69%|██████▉   | 5911/8509 [03:31<01:51, 23.35it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5914/8509 [03:31<01:53, 22.87it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5917/8509 [03:31<01:54, 22.65it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5920/8509 [03:32<01:54, 22.60it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5923/8509 [03:32<01:54, 22.56it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5926/8509 [03:32<01:53, 22.83it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5929/8509 [03:32<01:55, 22.35it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5932/8509 [03:32<01:52, 22.97it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5935/8509 [03:32<01:48, 23.64it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5938/8509 [03:32<01:48, 23.72it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5941/8509 [03:32<01:48, 23.62it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5944/8509 [03:33<01:50, 23.25it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5947/8509 [03:33<01:51, 23.05it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5950/8509 [03:33<01:56, 21.92it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5953/8509 [03:33<01:54, 22.31it/s]

embedding (embeddinggemma:latest):  70%|██████▉   | 5956/8509 [03:33<01:48, 23.44it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5959/8509 [03:33<01:50, 23.12it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5962/8509 [03:33<01:50, 22.96it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5965/8509 [03:33<01:52, 22.62it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5968/8509 [03:34<01:52, 22.55it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5971/8509 [03:34<01:54, 22.18it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5974/8509 [03:34<01:56, 21.82it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5977/8509 [03:34<01:56, 21.79it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5980/8509 [03:34<01:59, 21.13it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5983/8509 [03:34<01:57, 21.46it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5986/8509 [03:34<01:59, 21.17it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5989/8509 [03:35<01:59, 21.09it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5992/8509 [03:35<02:00, 20.96it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5995/8509 [03:35<01:57, 21.47it/s]

embedding (embeddinggemma:latest):  70%|███████   | 5998/8509 [03:35<01:54, 21.93it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6001/8509 [03:35<01:57, 21.28it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6004/8509 [03:35<01:55, 21.69it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6007/8509 [03:35<01:54, 21.84it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6010/8509 [03:36<01:52, 22.21it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6013/8509 [03:36<01:50, 22.57it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6016/8509 [03:36<01:51, 22.32it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6019/8509 [03:36<01:49, 22.79it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6022/8509 [03:36<01:46, 23.37it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6025/8509 [03:36<01:45, 23.46it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6028/8509 [03:36<01:43, 23.90it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6031/8509 [03:36<01:41, 24.38it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6034/8509 [03:37<01:41, 24.45it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6037/8509 [03:37<01:39, 24.80it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6040/8509 [03:37<01:40, 24.47it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6043/8509 [03:37<01:39, 24.80it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6046/8509 [03:37<01:37, 25.23it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6049/8509 [03:37<01:37, 25.11it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6052/8509 [03:37<01:38, 24.82it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6055/8509 [03:37<01:37, 25.06it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6058/8509 [03:38<01:38, 24.80it/s]

embedding (embeddinggemma:latest):  71%|███████   | 6061/8509 [03:38<01:36, 25.29it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6064/8509 [03:38<01:37, 24.99it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6067/8509 [03:38<01:39, 24.58it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6070/8509 [03:38<01:40, 24.29it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6073/8509 [03:38<01:39, 24.42it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6076/8509 [03:38<01:40, 24.12it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6079/8509 [03:38<01:44, 23.32it/s]

embedding (embeddinggemma:latest):  71%|███████▏  | 6082/8509 [03:39<01:46, 22.81it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6085/8509 [03:39<01:47, 22.55it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6088/8509 [03:39<01:49, 22.12it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6091/8509 [03:39<01:52, 21.44it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6094/8509 [03:39<01:52, 21.49it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6097/8509 [03:39<01:53, 21.19it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6100/8509 [03:39<01:53, 21.24it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6103/8509 [03:40<01:52, 21.43it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6106/8509 [03:40<01:50, 21.68it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6109/8509 [03:40<01:46, 22.57it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6112/8509 [03:40<01:43, 23.27it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6115/8509 [03:40<01:42, 23.36it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6118/8509 [03:40<01:42, 23.40it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6121/8509 [03:40<01:44, 22.96it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6124/8509 [03:40<01:42, 23.17it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6127/8509 [03:41<01:40, 23.68it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6130/8509 [03:41<01:37, 24.33it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6133/8509 [03:41<01:37, 24.41it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6136/8509 [03:41<01:41, 23.32it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6139/8509 [03:41<01:41, 23.37it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6142/8509 [03:41<01:41, 23.34it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6145/8509 [03:41<01:41, 23.31it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6148/8509 [03:41<01:39, 23.64it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6151/8509 [03:42<01:40, 23.51it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6154/8509 [03:42<01:39, 23.64it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6157/8509 [03:42<01:41, 23.24it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6160/8509 [03:42<01:41, 23.08it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6163/8509 [03:42<01:40, 23.30it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6166/8509 [03:42<01:39, 23.49it/s]

embedding (embeddinggemma:latest):  72%|███████▏  | 6169/8509 [03:42<01:37, 24.09it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6172/8509 [03:42<01:35, 24.42it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6175/8509 [03:43<01:35, 24.43it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6178/8509 [03:43<01:36, 24.24it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6181/8509 [03:43<01:36, 24.18it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6184/8509 [03:43<01:36, 24.00it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6187/8509 [03:43<01:36, 23.99it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6190/8509 [03:43<01:34, 24.45it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6193/8509 [03:43<01:34, 24.58it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6196/8509 [03:43<01:32, 24.97it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6199/8509 [03:44<01:33, 24.64it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6202/8509 [03:44<01:33, 24.80it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6205/8509 [03:44<01:32, 24.83it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6208/8509 [03:44<01:31, 25.15it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6211/8509 [03:44<01:32, 24.73it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6214/8509 [03:44<01:34, 24.31it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6217/8509 [03:44<01:36, 23.76it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6220/8509 [03:44<01:36, 23.73it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6223/8509 [03:45<01:36, 23.59it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6226/8509 [03:45<01:36, 23.55it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6229/8509 [03:45<01:36, 23.51it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6232/8509 [03:45<01:39, 22.92it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6235/8509 [03:45<01:37, 23.27it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6238/8509 [03:45<01:36, 23.50it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6241/8509 [03:45<01:36, 23.40it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6244/8509 [03:45<01:38, 22.92it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6247/8509 [03:46<01:39, 22.67it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6250/8509 [03:46<01:38, 23.03it/s]

embedding (embeddinggemma:latest):  73%|███████▎  | 6253/8509 [03:46<01:38, 22.83it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6256/8509 [03:46<01:40, 22.43it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6259/8509 [03:46<01:40, 22.48it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6262/8509 [03:46<01:37, 23.12it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6265/8509 [03:46<01:34, 23.72it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6268/8509 [03:46<01:33, 23.84it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6271/8509 [03:47<01:31, 24.44it/s]

embedding (embeddinggemma:latest):  74%|███████▎  | 6274/8509 [03:47<01:31, 24.52it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6277/8509 [03:47<01:31, 24.36it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6280/8509 [03:47<01:31, 24.29it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6283/8509 [03:47<01:32, 24.17it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6286/8509 [03:47<01:32, 24.13it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6289/8509 [03:47<01:34, 23.48it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6292/8509 [03:47<01:37, 22.84it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6295/8509 [03:48<01:37, 22.71it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6298/8509 [03:48<01:36, 22.82it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6301/8509 [03:48<01:39, 22.30it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6304/8509 [03:48<01:38, 22.38it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6307/8509 [03:48<01:39, 22.09it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6310/8509 [03:48<01:39, 22.10it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6313/8509 [03:48<01:38, 22.39it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6316/8509 [03:49<01:35, 22.99it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6319/8509 [03:49<01:32, 23.62it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6322/8509 [03:49<01:31, 23.92it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6325/8509 [03:49<01:29, 24.30it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6328/8509 [03:49<01:29, 24.44it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6331/8509 [03:49<01:27, 24.94it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6334/8509 [03:49<01:28, 24.51it/s]

embedding (embeddinggemma:latest):  74%|███████▍  | 6337/8509 [03:49<01:28, 24.57it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6340/8509 [03:50<01:26, 24.96it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6343/8509 [03:50<01:27, 24.83it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6346/8509 [03:50<01:29, 24.11it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6349/8509 [03:50<01:29, 24.08it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6352/8509 [03:50<01:28, 24.42it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6355/8509 [03:50<01:28, 24.46it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6358/8509 [03:50<01:29, 24.16it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6361/8509 [03:50<01:28, 24.19it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6364/8509 [03:51<01:29, 23.94it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6367/8509 [03:51<01:30, 23.64it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6370/8509 [03:51<01:31, 23.26it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6373/8509 [03:51<01:33, 22.81it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6376/8509 [03:51<01:33, 22.75it/s]

embedding (embeddinggemma:latest):  75%|███████▍  | 6379/8509 [03:51<01:33, 22.80it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6382/8509 [03:51<01:35, 22.31it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6385/8509 [03:51<01:35, 22.13it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6388/8509 [03:52<01:33, 22.67it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6391/8509 [03:52<01:32, 22.95it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6394/8509 [03:52<01:32, 22.76it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6397/8509 [03:52<01:33, 22.49it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6400/8509 [03:52<01:35, 22.17it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6403/8509 [03:52<01:34, 22.30it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6406/8509 [03:52<01:35, 22.10it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6409/8509 [03:53<01:32, 22.73it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6412/8509 [03:53<01:29, 23.33it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6415/8509 [03:53<01:28, 23.55it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6418/8509 [03:53<01:33, 22.35it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6421/8509 [03:53<01:34, 22.10it/s]

embedding (embeddinggemma:latest):  75%|███████▌  | 6424/8509 [03:53<01:37, 21.41it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6427/8509 [03:53<01:37, 21.28it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6430/8509 [03:53<01:37, 21.41it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6433/8509 [03:54<01:37, 21.21it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6436/8509 [03:54<01:39, 20.85it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6439/8509 [03:54<01:39, 20.76it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6442/8509 [03:54<01:37, 21.27it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6445/8509 [03:54<01:34, 21.86it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6448/8509 [03:54<01:34, 21.85it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6451/8509 [03:54<01:33, 21.99it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6454/8509 [03:55<01:32, 22.33it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6457/8509 [03:55<01:29, 22.98it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6460/8509 [03:55<01:30, 22.71it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6463/8509 [03:55<01:28, 23.20it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6466/8509 [03:55<01:27, 23.35it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6469/8509 [03:55<01:26, 23.47it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6472/8509 [03:55<01:28, 23.13it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6475/8509 [03:56<01:30, 22.49it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6478/8509 [03:56<01:27, 23.25it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6481/8509 [03:56<01:27, 23.30it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6484/8509 [03:56<01:27, 23.17it/s]

embedding (embeddinggemma:latest):  76%|███████▌  | 6487/8509 [03:56<01:29, 22.50it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6490/8509 [03:56<01:29, 22.57it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6493/8509 [03:56<01:29, 22.61it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6496/8509 [03:56<01:29, 22.61it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6499/8509 [03:57<01:30, 22.13it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6502/8509 [03:57<01:32, 21.78it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6505/8509 [03:57<01:32, 21.73it/s]

embedding (embeddinggemma:latest):  76%|███████▋  | 6508/8509 [03:57<01:32, 21.58it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6511/8509 [03:57<01:31, 21.77it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6514/8509 [03:57<01:33, 21.32it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6517/8509 [03:57<01:33, 21.39it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6520/8509 [03:58<01:32, 21.46it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6523/8509 [03:58<01:31, 21.68it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6526/8509 [03:58<01:33, 21.28it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6529/8509 [03:58<01:32, 21.34it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6532/8509 [03:58<01:31, 21.51it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6535/8509 [03:58<01:27, 22.66it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6538/8509 [03:58<01:27, 22.64it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6541/8509 [03:58<01:26, 22.68it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6544/8509 [03:59<01:26, 22.59it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6547/8509 [03:59<01:26, 22.81it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6550/8509 [03:59<01:23, 23.39it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6553/8509 [03:59<01:23, 23.52it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6556/8509 [03:59<01:24, 23.00it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6559/8509 [03:59<01:25, 22.89it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6562/8509 [03:59<01:22, 23.67it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6565/8509 [04:00<01:21, 23.79it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6568/8509 [04:00<01:22, 23.45it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6571/8509 [04:00<01:23, 23.24it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6574/8509 [04:00<01:20, 24.15it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6577/8509 [04:00<01:18, 24.47it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6580/8509 [04:00<01:18, 24.47it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6583/8509 [04:00<01:17, 24.77it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6586/8509 [04:00<01:17, 24.75it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6589/8509 [04:00<01:16, 25.03it/s]

embedding (embeddinggemma:latest):  77%|███████▋  | 6592/8509 [04:01<01:17, 24.87it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6595/8509 [04:01<01:18, 24.40it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6598/8509 [04:01<01:19, 24.19it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6601/8509 [04:01<01:19, 23.92it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6604/8509 [04:01<01:17, 24.54it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6607/8509 [04:01<01:16, 24.72it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6610/8509 [04:01<01:17, 24.63it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6613/8509 [04:01<01:20, 23.63it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6616/8509 [04:02<01:21, 23.33it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6619/8509 [04:02<01:22, 22.89it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6622/8509 [04:02<01:21, 23.17it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6625/8509 [04:02<01:21, 23.08it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6628/8509 [04:02<01:20, 23.37it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6631/8509 [04:02<01:20, 23.24it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6634/8509 [04:02<01:20, 23.28it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6637/8509 [04:03<01:20, 23.14it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6640/8509 [04:03<01:20, 23.24it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6643/8509 [04:03<01:19, 23.48it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6646/8509 [04:03<01:19, 23.51it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6649/8509 [04:03<01:17, 23.90it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6652/8509 [04:03<01:13, 25.10it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6655/8509 [04:03<01:14, 24.72it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6658/8509 [04:03<01:18, 23.45it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6661/8509 [04:04<01:20, 22.85it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6664/8509 [04:04<01:20, 22.81it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6667/8509 [04:04<01:22, 22.45it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6670/8509 [04:04<01:21, 22.50it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6673/8509 [04:04<01:22, 22.21it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6676/8509 [04:04<01:20, 22.64it/s]

embedding (embeddinggemma:latest):  78%|███████▊  | 6679/8509 [04:04<01:19, 22.98it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6682/8509 [04:04<01:21, 22.55it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6685/8509 [04:05<01:20, 22.66it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6688/8509 [04:05<01:20, 22.76it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6691/8509 [04:05<01:19, 22.75it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6694/8509 [04:05<01:17, 23.53it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6697/8509 [04:05<01:15, 23.99it/s]

embedding (embeddinggemma:latest):  79%|███████▊  | 6700/8509 [04:05<01:15, 23.89it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6703/8509 [04:05<01:15, 23.89it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6706/8509 [04:05<01:16, 23.52it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6709/8509 [04:06<01:14, 24.10it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6712/8509 [04:06<01:13, 24.54it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6715/8509 [04:06<01:12, 24.68it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6718/8509 [04:06<01:12, 24.79it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6721/8509 [04:06<01:12, 24.65it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6724/8509 [04:06<01:11, 25.13it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6727/8509 [04:06<01:11, 24.79it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6730/8509 [04:06<01:12, 24.57it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6733/8509 [04:07<01:11, 24.94it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6736/8509 [04:07<01:11, 24.68it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6739/8509 [04:07<01:11, 24.88it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6742/8509 [04:07<01:10, 25.19it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6745/8509 [04:07<01:11, 24.71it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6748/8509 [04:07<01:12, 24.21it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6751/8509 [04:07<01:15, 23.39it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6754/8509 [04:07<01:15, 23.15it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6757/8509 [04:08<01:14, 23.41it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6760/8509 [04:08<01:14, 23.36it/s]

embedding (embeddinggemma:latest):  79%|███████▉  | 6763/8509 [04:08<01:16, 22.76it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6766/8509 [04:08<01:16, 22.85it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6769/8509 [04:08<01:15, 23.02it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6772/8509 [04:08<01:16, 22.72it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6775/8509 [04:08<01:16, 22.58it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6778/8509 [04:08<01:15, 22.85it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6781/8509 [04:09<01:16, 22.58it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6784/8509 [04:09<01:16, 22.50it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6787/8509 [04:09<01:17, 22.25it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6790/8509 [04:09<01:18, 21.89it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6793/8509 [04:09<01:18, 21.81it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6796/8509 [04:09<01:21, 21.12it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6799/8509 [04:09<01:22, 20.70it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6802/8509 [04:10<01:23, 20.50it/s]

embedding (embeddinggemma:latest):  80%|███████▉  | 6805/8509 [04:10<01:23, 20.40it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6808/8509 [04:10<01:21, 20.96it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6811/8509 [04:10<01:17, 21.81it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6814/8509 [04:10<01:16, 22.15it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6817/8509 [04:10<01:18, 21.57it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6820/8509 [04:10<01:19, 21.25it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6823/8509 [04:11<01:18, 21.43it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6826/8509 [04:11<01:16, 22.11it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6829/8509 [04:11<01:16, 21.96it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6832/8509 [04:11<01:19, 21.19it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6835/8509 [04:11<01:18, 21.44it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6838/8509 [04:11<01:14, 22.53it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6841/8509 [04:11<01:11, 23.19it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6844/8509 [04:12<01:09, 23.82it/s]

embedding (embeddinggemma:latest):  80%|████████  | 6847/8509 [04:12<01:09, 24.01it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6851/8509 [04:12<01:04, 25.81it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6854/8509 [04:12<01:05, 25.11it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6857/8509 [04:12<01:05, 25.28it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6860/8509 [04:12<01:05, 25.12it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6863/8509 [04:12<01:07, 24.30it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6866/8509 [04:12<01:09, 23.53it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6869/8509 [04:13<01:09, 23.44it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6872/8509 [04:13<01:09, 23.44it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6875/8509 [04:13<01:11, 22.91it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6878/8509 [04:13<01:11, 22.96it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6881/8509 [04:13<01:10, 23.11it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6884/8509 [04:13<01:09, 23.30it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6887/8509 [04:13<01:10, 23.11it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6890/8509 [04:13<01:07, 23.95it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6893/8509 [04:14<01:07, 23.81it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6896/8509 [04:14<01:07, 23.87it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6899/8509 [04:14<01:08, 23.64it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6902/8509 [04:14<01:08, 23.57it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6905/8509 [04:14<01:08, 23.57it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6908/8509 [04:14<01:07, 23.57it/s]

embedding (embeddinggemma:latest):  81%|████████  | 6911/8509 [04:14<01:07, 23.80it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6914/8509 [04:14<01:07, 23.73it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6917/8509 [04:15<01:06, 23.76it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6920/8509 [04:15<01:08, 23.29it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6923/8509 [04:15<01:09, 22.81it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6926/8509 [04:15<01:08, 23.00it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6929/8509 [04:15<01:07, 23.55it/s]

embedding (embeddinggemma:latest):  81%|████████▏ | 6932/8509 [04:15<01:05, 24.06it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6935/8509 [04:15<01:05, 24.01it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6938/8509 [04:15<01:05, 23.93it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6941/8509 [04:16<01:07, 23.08it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6944/8509 [04:16<01:08, 22.92it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6947/8509 [04:16<01:08, 22.85it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6950/8509 [04:16<01:08, 22.90it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6953/8509 [04:16<01:08, 22.75it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6956/8509 [04:16<01:09, 22.47it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6959/8509 [04:16<01:09, 22.16it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6962/8509 [04:17<01:09, 22.14it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6965/8509 [04:17<01:09, 22.21it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6968/8509 [04:17<01:09, 22.24it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6971/8509 [04:17<01:07, 22.76it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6974/8509 [04:17<01:07, 22.90it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6977/8509 [04:17<01:06, 23.18it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6980/8509 [04:17<01:06, 23.08it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6983/8509 [04:17<01:05, 23.24it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6986/8509 [04:18<01:04, 23.79it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6989/8509 [04:18<01:02, 24.50it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6992/8509 [04:18<01:04, 23.46it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6995/8509 [04:18<01:03, 23.99it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 6998/8509 [04:18<01:03, 23.82it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7001/8509 [04:18<01:03, 23.80it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7004/8509 [04:18<01:05, 23.09it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7007/8509 [04:18<01:05, 22.82it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7010/8509 [04:19<01:06, 22.41it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7013/8509 [04:19<01:06, 22.34it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7016/8509 [04:19<01:06, 22.36it/s]

embedding (embeddinggemma:latest):  82%|████████▏ | 7019/8509 [04:19<01:06, 22.39it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7022/8509 [04:19<01:04, 23.11it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7025/8509 [04:19<01:05, 22.61it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7028/8509 [04:19<01:04, 22.81it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7031/8509 [04:20<01:03, 23.14it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7034/8509 [04:20<01:03, 23.37it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7037/8509 [04:20<01:02, 23.55it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7040/8509 [04:20<01:00, 24.37it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7043/8509 [04:20<00:59, 24.52it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7046/8509 [04:20<00:58, 25.12it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7049/8509 [04:20<00:59, 24.57it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7052/8509 [04:20<01:00, 24.12it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7055/8509 [04:21<01:01, 23.67it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7058/8509 [04:21<01:00, 24.11it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7061/8509 [04:21<00:58, 24.55it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7064/8509 [04:21<00:58, 24.61it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7067/8509 [04:21<00:58, 24.52it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7070/8509 [04:21<00:57, 24.94it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7073/8509 [04:21<00:57, 24.95it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7076/8509 [04:21<00:57, 24.93it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7079/8509 [04:21<00:58, 24.64it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7082/8509 [04:22<00:57, 25.03it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7085/8509 [04:22<00:56, 25.04it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7088/8509 [04:22<00:57, 24.62it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7091/8509 [04:22<00:57, 24.61it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7094/8509 [04:22<00:59, 23.97it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7097/8509 [04:22<00:57, 24.37it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7100/8509 [04:22<00:58, 24.19it/s]

embedding (embeddinggemma:latest):  83%|████████▎ | 7103/8509 [04:22<00:57, 24.25it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7106/8509 [04:23<00:58, 24.13it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7109/8509 [04:23<00:57, 24.15it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7112/8509 [04:23<00:59, 23.42it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7115/8509 [04:23<01:01, 22.56it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7118/8509 [04:23<01:02, 22.12it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7121/8509 [04:23<01:03, 21.94it/s]

embedding (embeddinggemma:latest):  84%|████████▎ | 7124/8509 [04:23<01:02, 22.20it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7127/8509 [04:24<01:02, 22.08it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7130/8509 [04:24<01:01, 22.43it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7133/8509 [04:24<01:00, 22.57it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7136/8509 [04:24<01:00, 22.56it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7139/8509 [04:24<01:01, 22.37it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7142/8509 [04:24<01:00, 22.46it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7145/8509 [04:24<01:00, 22.45it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7148/8509 [04:24<00:59, 22.76it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7151/8509 [04:25<01:00, 22.55it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7154/8509 [04:25<00:59, 22.83it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7157/8509 [04:25<00:59, 22.73it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7160/8509 [04:25<00:58, 23.21it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7163/8509 [04:25<00:57, 23.39it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7166/8509 [04:25<00:57, 23.17it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7169/8509 [04:25<00:57, 23.36it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7172/8509 [04:26<00:57, 23.26it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7175/8509 [04:26<00:57, 23.40it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7178/8509 [04:26<00:57, 22.97it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7181/8509 [04:26<00:58, 22.65it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7184/8509 [04:26<00:59, 22.17it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7187/8509 [04:26<00:58, 22.50it/s]

embedding (embeddinggemma:latest):  84%|████████▍ | 7190/8509 [04:26<00:59, 22.25it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7193/8509 [04:26<01:00, 21.92it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7196/8509 [04:27<00:59, 21.98it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7199/8509 [04:27<00:59, 22.16it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7202/8509 [04:27<00:59, 21.83it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7205/8509 [04:27<00:59, 21.90it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7208/8509 [04:27<00:56, 22.97it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7211/8509 [04:27<00:55, 23.48it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7214/8509 [04:27<00:54, 23.72it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7217/8509 [04:27<00:54, 23.50it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7220/8509 [04:28<00:55, 23.26it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7223/8509 [04:28<00:54, 23.46it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7226/8509 [04:28<00:54, 23.58it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7229/8509 [04:28<00:55, 23.00it/s]

embedding (embeddinggemma:latest):  85%|████████▍ | 7232/8509 [04:28<00:54, 23.36it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7235/8509 [04:28<00:53, 23.75it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7238/8509 [04:28<00:52, 24.05it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7241/8509 [04:28<00:51, 24.58it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7244/8509 [04:29<00:51, 24.60it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7247/8509 [04:29<00:51, 24.58it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7250/8509 [04:29<00:50, 24.84it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7253/8509 [04:29<00:49, 25.19it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7256/8509 [04:29<00:50, 24.88it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7259/8509 [04:29<00:51, 24.43it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7262/8509 [04:29<00:51, 24.01it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7265/8509 [04:29<00:52, 23.69it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7268/8509 [04:30<00:54, 22.93it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7271/8509 [04:30<00:53, 23.14it/s]

embedding (embeddinggemma:latest):  85%|████████▌ | 7274/8509 [04:30<00:53, 23.01it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7277/8509 [04:30<00:55, 22.38it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7280/8509 [04:30<00:55, 22.01it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7283/8509 [04:30<00:54, 22.29it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7286/8509 [04:30<00:53, 22.65it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7289/8509 [04:31<00:53, 22.87it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7292/8509 [04:31<00:53, 22.92it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7295/8509 [04:31<00:52, 23.05it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7298/8509 [04:31<00:51, 23.53it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7301/8509 [04:31<00:50, 23.70it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7304/8509 [04:31<00:49, 24.12it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7307/8509 [04:31<00:49, 24.08it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7310/8509 [04:31<00:51, 23.47it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7313/8509 [04:32<00:52, 22.93it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7316/8509 [04:32<00:50, 23.74it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7319/8509 [04:32<00:50, 23.44it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7322/8509 [04:32<00:51, 22.85it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7325/8509 [04:32<00:53, 22.08it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7328/8509 [04:32<00:52, 22.32it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7331/8509 [04:32<00:51, 22.80it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7334/8509 [04:32<00:51, 22.94it/s]

embedding (embeddinggemma:latest):  86%|████████▌ | 7337/8509 [04:33<00:51, 22.78it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7340/8509 [04:33<00:50, 23.12it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7343/8509 [04:33<00:51, 22.85it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7346/8509 [04:33<00:49, 23.39it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7349/8509 [04:33<00:50, 22.98it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7352/8509 [04:33<00:49, 23.29it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7355/8509 [04:33<00:51, 22.60it/s]

embedding (embeddinggemma:latest):  86%|████████▋ | 7358/8509 [04:34<00:51, 22.47it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7361/8509 [04:34<00:49, 23.13it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7364/8509 [04:34<00:49, 23.20it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7367/8509 [04:34<00:50, 22.63it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7370/8509 [04:34<00:49, 22.80it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7373/8509 [04:34<00:51, 21.99it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7376/8509 [04:34<00:52, 21.39it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7379/8509 [04:35<00:55, 20.45it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7382/8509 [04:35<00:54, 20.74it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7385/8509 [04:35<00:54, 20.47it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7388/8509 [04:35<00:55, 20.19it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7391/8509 [04:35<00:54, 20.39it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7394/8509 [04:35<00:54, 20.56it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7397/8509 [04:35<00:56, 19.71it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7399/8509 [04:36<00:57, 19.43it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7402/8509 [04:36<00:55, 20.05it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7405/8509 [04:36<00:53, 20.69it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7408/8509 [04:36<00:51, 21.54it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7411/8509 [04:36<00:49, 22.28it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7414/8509 [04:36<00:48, 22.45it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7417/8509 [04:36<00:48, 22.29it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7420/8509 [04:36<00:48, 22.43it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7423/8509 [04:37<00:48, 22.17it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7426/8509 [04:37<00:48, 22.20it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7429/8509 [04:37<00:48, 22.37it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7432/8509 [04:37<00:47, 22.51it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7435/8509 [04:37<00:47, 22.80it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7438/8509 [04:37<00:46, 23.26it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7441/8509 [04:37<00:46, 22.81it/s]

embedding (embeddinggemma:latest):  87%|████████▋ | 7444/8509 [04:38<00:46, 23.05it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7447/8509 [04:38<00:46, 22.61it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7450/8509 [04:38<00:47, 22.32it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7453/8509 [04:38<00:47, 22.44it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7456/8509 [04:38<00:47, 22.39it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7459/8509 [04:38<00:46, 22.38it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7462/8509 [04:38<00:46, 22.46it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7465/8509 [04:38<00:45, 23.03it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7468/8509 [04:39<00:45, 23.04it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7471/8509 [04:39<00:44, 23.31it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7474/8509 [04:39<00:44, 23.12it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7477/8509 [04:39<00:44, 23.13it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7480/8509 [04:39<00:44, 23.33it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7483/8509 [04:39<00:44, 23.15it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7486/8509 [04:39<00:46, 22.08it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7489/8509 [04:40<00:46, 21.80it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7492/8509 [04:40<00:47, 21.31it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7495/8509 [04:40<00:46, 21.67it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7498/8509 [04:40<00:46, 21.88it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7501/8509 [04:40<00:45, 22.15it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7504/8509 [04:40<00:45, 22.23it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7507/8509 [04:40<00:45, 22.14it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7510/8509 [04:40<00:47, 21.24it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7513/8509 [04:41<00:44, 22.44it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7516/8509 [04:41<00:44, 22.17it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7519/8509 [04:41<00:44, 22.22it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7522/8509 [04:41<00:44, 22.11it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7525/8509 [04:41<00:43, 22.53it/s]

embedding (embeddinggemma:latest):  88%|████████▊ | 7528/8509 [04:41<00:43, 22.50it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7531/8509 [04:41<00:41, 23.42it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7534/8509 [04:42<00:42, 22.97it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7537/8509 [04:42<00:43, 22.13it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7540/8509 [04:42<00:45, 21.49it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7543/8509 [04:42<00:46, 20.71it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7546/8509 [04:42<00:45, 21.08it/s]

embedding (embeddinggemma:latest):  89%|████████▊ | 7549/8509 [04:42<00:45, 21.16it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7552/8509 [04:42<00:44, 21.39it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7555/8509 [04:43<00:44, 21.27it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7558/8509 [04:43<00:44, 21.34it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7561/8509 [04:43<00:44, 21.54it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7564/8509 [04:43<00:43, 21.71it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7567/8509 [04:43<00:43, 21.54it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7570/8509 [04:43<00:43, 21.47it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7573/8509 [04:43<00:42, 21.99it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7576/8509 [04:43<00:43, 21.62it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7579/8509 [04:44<00:42, 21.75it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7582/8509 [04:44<00:42, 21.95it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7585/8509 [04:44<00:41, 22.07it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7588/8509 [04:44<00:41, 22.39it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7591/8509 [04:44<00:41, 22.07it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7594/8509 [04:44<00:42, 21.62it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7597/8509 [04:44<00:42, 21.62it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7600/8509 [04:45<00:41, 21.83it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7603/8509 [04:45<00:40, 22.37it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7606/8509 [04:45<00:41, 21.96it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7609/8509 [04:45<00:40, 22.17it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7612/8509 [04:45<00:39, 22.52it/s]

embedding (embeddinggemma:latest):  89%|████████▉ | 7615/8509 [04:45<00:38, 23.02it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7618/8509 [04:45<00:37, 23.48it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7621/8509 [04:46<00:40, 21.91it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7624/8509 [04:46<00:41, 21.57it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7627/8509 [04:46<00:40, 21.69it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7630/8509 [04:46<00:39, 22.36it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7633/8509 [04:46<00:38, 22.56it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7636/8509 [04:46<00:39, 22.19it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7639/8509 [04:46<00:39, 22.27it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7642/8509 [04:46<00:38, 22.47it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7645/8509 [04:47<00:39, 22.06it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7648/8509 [04:47<00:37, 22.80it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7651/8509 [04:47<00:38, 22.54it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7654/8509 [04:47<00:38, 22.05it/s]

embedding (embeddinggemma:latest):  90%|████████▉ | 7657/8509 [04:47<00:38, 22.29it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7660/8509 [04:47<00:40, 20.94it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7663/8509 [04:47<00:40, 21.02it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7666/8509 [04:48<00:40, 20.93it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7669/8509 [04:48<00:39, 21.35it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7672/8509 [04:48<00:38, 21.96it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7675/8509 [04:48<00:37, 22.32it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7678/8509 [04:48<00:37, 22.25it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7681/8509 [04:48<00:36, 22.53it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7684/8509 [04:48<00:35, 23.05it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7687/8509 [04:48<00:35, 23.17it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7690/8509 [04:49<00:35, 22.81it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7693/8509 [04:49<00:36, 22.44it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7696/8509 [04:49<00:37, 21.93it/s]

embedding (embeddinggemma:latest):  90%|█████████ | 7699/8509 [04:49<00:37, 21.52it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7702/8509 [04:49<00:37, 21.49it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7705/8509 [04:49<00:37, 21.55it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7708/8509 [04:49<00:38, 20.89it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7711/8509 [04:50<00:38, 20.94it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7714/8509 [04:50<00:37, 21.27it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7717/8509 [04:50<00:35, 22.05it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7720/8509 [04:50<00:35, 21.96it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7723/8509 [04:50<00:35, 21.97it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7726/8509 [04:50<00:36, 21.50it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7729/8509 [04:50<00:36, 21.63it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7732/8509 [04:51<00:35, 21.94it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7735/8509 [04:51<00:34, 22.34it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7738/8509 [04:51<00:33, 22.69it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7741/8509 [04:51<00:33, 23.09it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7744/8509 [04:51<00:32, 23.26it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7747/8509 [04:51<00:33, 22.92it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7750/8509 [04:51<00:33, 22.66it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7753/8509 [04:51<00:32, 22.96it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7756/8509 [04:52<00:32, 23.16it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7759/8509 [04:52<00:32, 23.32it/s]

embedding (embeddinggemma:latest):  91%|█████████ | 7762/8509 [04:52<00:31, 24.07it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7765/8509 [04:52<00:30, 24.25it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7768/8509 [04:52<00:30, 24.62it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7771/8509 [04:52<00:29, 24.76it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7774/8509 [04:52<00:29, 24.59it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7777/8509 [04:52<00:29, 24.88it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7780/8509 [04:53<00:29, 24.57it/s]

embedding (embeddinggemma:latest):  91%|█████████▏| 7783/8509 [04:53<00:29, 24.25it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7786/8509 [04:53<00:31, 23.26it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7789/8509 [04:53<00:31, 22.63it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7792/8509 [04:53<00:31, 23.05it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7795/8509 [04:53<00:31, 22.99it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7798/8509 [04:53<00:31, 22.72it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7801/8509 [04:54<00:31, 22.66it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7804/8509 [04:54<00:31, 22.34it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7807/8509 [04:54<00:31, 22.11it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7810/8509 [04:54<00:32, 21.69it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7813/8509 [04:54<00:31, 21.96it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7816/8509 [04:54<00:31, 22.19it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7819/8509 [04:54<00:30, 22.29it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7822/8509 [04:54<00:30, 22.37it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7825/8509 [04:55<00:29, 22.89it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7828/8509 [04:55<00:32, 20.95it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7832/8509 [04:55<00:28, 23.48it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7835/8509 [04:55<00:28, 23.51it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7838/8509 [04:55<00:28, 23.66it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7841/8509 [04:55<00:29, 22.89it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7844/8509 [04:55<00:29, 22.54it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7847/8509 [04:56<00:29, 22.44it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7850/8509 [04:56<00:29, 22.60it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7853/8509 [04:56<00:28, 23.24it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7856/8509 [04:56<00:27, 23.86it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7859/8509 [04:56<00:27, 23.84it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7862/8509 [04:56<00:26, 24.48it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7865/8509 [04:56<00:26, 24.69it/s]

embedding (embeddinggemma:latest):  92%|█████████▏| 7868/8509 [04:56<00:25, 24.90it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7871/8509 [04:57<00:26, 24.54it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7874/8509 [04:57<00:25, 24.79it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7877/8509 [04:57<00:25, 24.87it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7880/8509 [04:57<00:25, 24.20it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7883/8509 [04:57<00:26, 24.07it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7886/8509 [04:57<00:26, 23.53it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7889/8509 [04:57<00:26, 23.25it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7892/8509 [04:57<00:26, 23.34it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7895/8509 [04:58<00:26, 23.11it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7898/8509 [04:58<00:25, 23.89it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7901/8509 [04:58<00:25, 24.19it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7904/8509 [04:58<00:25, 23.86it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7907/8509 [04:58<00:24, 24.13it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7910/8509 [04:58<00:24, 24.17it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7913/8509 [04:58<00:24, 24.07it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7916/8509 [04:58<00:24, 23.82it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7919/8509 [04:59<00:25, 22.74it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7922/8509 [04:59<00:26, 22.01it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7925/8509 [04:59<00:27, 21.59it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7928/8509 [04:59<00:26, 21.93it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7931/8509 [04:59<00:25, 22.74it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7934/8509 [04:59<00:24, 23.36it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7937/8509 [04:59<00:23, 24.03it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7940/8509 [04:59<00:23, 23.85it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7943/8509 [05:00<00:23, 24.12it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7946/8509 [05:00<00:23, 23.91it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7949/8509 [05:00<00:23, 23.50it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7952/8509 [05:00<00:23, 23.31it/s]

embedding (embeddinggemma:latest):  93%|█████████▎| 7955/8509 [05:00<00:23, 23.12it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7958/8509 [05:00<00:23, 23.22it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7961/8509 [05:00<00:23, 23.64it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7964/8509 [05:00<00:22, 24.34it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7967/8509 [05:01<00:22, 24.29it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7970/8509 [05:01<00:22, 23.59it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7973/8509 [05:01<00:23, 23.14it/s]

embedding (embeddinggemma:latest):  94%|█████████▎| 7976/8509 [05:01<00:23, 22.66it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7979/8509 [05:01<00:23, 22.65it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7982/8509 [05:01<00:22, 23.09it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7985/8509 [05:01<00:22, 23.64it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7988/8509 [05:02<00:22, 23.66it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7991/8509 [05:02<00:22, 23.45it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7994/8509 [05:02<00:22, 22.62it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 7997/8509 [05:02<00:23, 21.74it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8000/8509 [05:02<00:24, 21.05it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8003/8509 [05:02<00:23, 21.65it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8006/8509 [05:02<00:23, 21.39it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8009/8509 [05:02<00:22, 22.48it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8012/8509 [05:03<00:21, 23.27it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8015/8509 [05:03<00:21, 23.13it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8018/8509 [05:03<00:21, 22.67it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8021/8509 [05:03<00:21, 22.70it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8024/8509 [05:03<00:21, 22.76it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8027/8509 [05:03<00:21, 22.78it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8030/8509 [05:03<00:20, 23.41it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8033/8509 [05:04<00:20, 23.73it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8036/8509 [05:04<00:20, 23.11it/s]

embedding (embeddinggemma:latest):  94%|█████████▍| 8039/8509 [05:04<00:20, 23.25it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8042/8509 [05:04<00:20, 22.81it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8045/8509 [05:04<00:20, 22.17it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8048/8509 [05:04<00:20, 22.18it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8051/8509 [05:04<00:21, 21.73it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8054/8509 [05:04<00:21, 21.59it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8057/8509 [05:05<00:20, 21.81it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8060/8509 [05:05<00:20, 21.93it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8063/8509 [05:05<00:20, 22.10it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8066/8509 [05:05<00:19, 22.52it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8069/8509 [05:05<00:18, 23.33it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8072/8509 [05:05<00:18, 23.27it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8075/8509 [05:05<00:18, 23.70it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8078/8509 [05:06<00:18, 23.51it/s]

embedding (embeddinggemma:latest):  95%|█████████▍| 8081/8509 [05:06<00:17, 23.88it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8084/8509 [05:06<00:18, 23.56it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8087/8509 [05:06<00:18, 23.20it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8090/8509 [05:06<00:17, 23.30it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8093/8509 [05:06<00:18, 23.10it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8096/8509 [05:06<00:17, 23.15it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8099/8509 [05:06<00:17, 22.89it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8102/8509 [05:07<00:17, 22.68it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8105/8509 [05:07<00:17, 22.64it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8108/8509 [05:07<00:18, 22.22it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8111/8509 [05:07<00:17, 22.20it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8114/8509 [05:07<00:17, 22.16it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8117/8509 [05:07<00:17, 22.35it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8120/8509 [05:07<00:17, 22.73it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8123/8509 [05:08<00:17, 22.21it/s]

embedding (embeddinggemma:latest):  95%|█████████▌| 8126/8509 [05:08<00:17, 21.93it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8129/8509 [05:08<00:17, 21.55it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8132/8509 [05:08<00:17, 21.74it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8135/8509 [05:08<00:17, 21.52it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8138/8509 [05:08<00:16, 22.32it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8141/8509 [05:08<00:16, 22.38it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8144/8509 [05:08<00:16, 22.60it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8147/8509 [05:09<00:15, 23.21it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8150/8509 [05:09<00:14, 24.21it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8153/8509 [05:09<00:14, 23.78it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8156/8509 [05:09<00:14, 23.88it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8159/8509 [05:09<00:15, 23.11it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8162/8509 [05:09<00:14, 23.25it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8165/8509 [05:09<00:14, 23.17it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8168/8509 [05:09<00:14, 24.06it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8171/8509 [05:10<00:14, 23.98it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8174/8509 [05:10<00:14, 23.82it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8177/8509 [05:10<00:14, 23.51it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8180/8509 [05:10<00:13, 23.80it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8183/8509 [05:10<00:13, 23.31it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8186/8509 [05:10<00:14, 22.72it/s]

embedding (embeddinggemma:latest):  96%|█████████▌| 8189/8509 [05:10<00:13, 23.54it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8192/8509 [05:10<00:13, 23.93it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8195/8509 [05:11<00:12, 24.33it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8198/8509 [05:11<00:12, 24.13it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8201/8509 [05:11<00:12, 24.31it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8204/8509 [05:11<00:12, 24.22it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8207/8509 [05:11<00:12, 24.16it/s]

embedding (embeddinggemma:latest):  96%|█████████▋| 8210/8509 [05:11<00:12, 24.16it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8213/8509 [05:11<00:12, 24.31it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8216/8509 [05:11<00:12, 23.83it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8219/8509 [05:12<00:12, 23.46it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8222/8509 [05:12<00:12, 23.77it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8225/8509 [05:12<00:11, 23.86it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8228/8509 [05:12<00:12, 23.22it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8231/8509 [05:12<00:12, 22.58it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8234/8509 [05:12<00:11, 22.99it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8237/8509 [05:12<00:11, 23.27it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8240/8509 [05:12<00:11, 23.87it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8243/8509 [05:13<00:11, 23.83it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8246/8509 [05:13<00:10, 24.32it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8249/8509 [05:13<00:10, 25.11it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8252/8509 [05:13<00:10, 24.54it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8255/8509 [05:13<00:10, 25.01it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8258/8509 [05:13<00:10, 24.79it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8261/8509 [05:13<00:09, 24.80it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8264/8509 [05:13<00:09, 25.13it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8267/8509 [05:14<00:09, 24.53it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8270/8509 [05:14<00:09, 25.32it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8273/8509 [05:14<00:09, 24.91it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8276/8509 [05:14<00:09, 25.40it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8279/8509 [05:14<00:09, 25.19it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8282/8509 [05:14<00:09, 24.87it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8285/8509 [05:14<00:09, 24.31it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8288/8509 [05:14<00:09, 24.53it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8291/8509 [05:15<00:08, 24.27it/s]

embedding (embeddinggemma:latest):  97%|█████████▋| 8294/8509 [05:15<00:08, 24.14it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8297/8509 [05:15<00:08, 24.07it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8300/8509 [05:15<00:08, 24.10it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8303/8509 [05:15<00:08, 23.84it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8306/8509 [05:15<00:08, 22.97it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8309/8509 [05:15<00:08, 23.14it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8312/8509 [05:15<00:08, 23.03it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8315/8509 [05:16<00:08, 22.94it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8318/8509 [05:16<00:08, 22.78it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8321/8509 [05:16<00:08, 23.10it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8324/8509 [05:16<00:08, 22.55it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8327/8509 [05:16<00:08, 22.28it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8330/8509 [05:16<00:08, 21.91it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8333/8509 [05:16<00:08, 21.50it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8336/8509 [05:17<00:07, 21.71it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8339/8509 [05:17<00:07, 21.92it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8342/8509 [05:17<00:07, 22.32it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8345/8509 [05:17<00:07, 22.23it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8348/8509 [05:17<00:07, 22.10it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8351/8509 [05:17<00:07, 21.89it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8354/8509 [05:17<00:07, 21.98it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8357/8509 [05:17<00:06, 22.41it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8360/8509 [05:18<00:06, 22.21it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8363/8509 [05:18<00:06, 22.19it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8366/8509 [05:18<00:06, 21.39it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8369/8509 [05:18<00:06, 20.42it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8372/8509 [05:18<00:06, 20.81it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8375/8509 [05:18<00:06, 21.30it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8378/8509 [05:18<00:06, 21.82it/s]

embedding (embeddinggemma:latest):  98%|█████████▊| 8381/8509 [05:19<00:05, 22.68it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8384/8509 [05:19<00:05, 22.51it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8387/8509 [05:19<00:05, 22.17it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8390/8509 [05:19<00:05, 22.77it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8393/8509 [05:19<00:05, 23.14it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8396/8509 [05:19<00:04, 23.19it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8399/8509 [05:19<00:04, 23.04it/s]

embedding (embeddinggemma:latest):  99%|█████████▊| 8402/8509 [05:20<00:04, 22.33it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8405/8509 [05:20<00:04, 22.39it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8408/8509 [05:20<00:04, 22.24it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8411/8509 [05:20<00:04, 21.70it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8414/8509 [05:20<00:04, 21.80it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8417/8509 [05:20<00:04, 21.93it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8420/8509 [05:20<00:04, 21.81it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8423/8509 [05:21<00:04, 21.40it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8426/8509 [05:21<00:03, 21.89it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8429/8509 [05:21<00:03, 22.61it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8432/8509 [05:21<00:03, 22.95it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8435/8509 [05:21<00:03, 23.58it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8438/8509 [05:21<00:02, 23.98it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8441/8509 [05:21<00:02, 24.40it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8444/8509 [05:21<00:02, 23.80it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8447/8509 [05:22<00:02, 23.55it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8450/8509 [05:22<00:02, 24.12it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8453/8509 [05:22<00:02, 24.61it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8456/8509 [05:22<00:02, 24.48it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8459/8509 [05:22<00:02, 24.76it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8462/8509 [05:22<00:01, 24.56it/s]

embedding (embeddinggemma:latest):  99%|█████████▉| 8465/8509 [05:22<00:01, 24.89it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8468/8509 [05:22<00:01, 24.23it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8471/8509 [05:22<00:01, 24.23it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8474/8509 [05:23<00:01, 23.50it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8477/8509 [05:23<00:01, 22.76it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8480/8509 [05:23<00:01, 23.32it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8483/8509 [05:23<00:01, 22.01it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8486/8509 [05:23<00:01, 22.23it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8489/8509 [05:23<00:00, 23.07it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8492/8509 [05:23<00:00, 23.41it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8495/8509 [05:24<00:00, 23.82it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8498/8509 [05:24<00:00, 24.35it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8501/8509 [05:24<00:00, 24.39it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8504/8509 [05:24<00:00, 24.67it/s]

embedding (embeddinggemma:latest): 100%|█████████▉| 8507/8509 [05:24<00:00, 24.90it/s]

embedding (embeddinggemma:latest): 100%|██████████| 8509/8509 [05:24<00:00, 26.22it/s]

embeddings: (8509, 768)
time: 5min 24s (started: 2026-08-29 18:14:05 +05:30)

## The index

`IndexFlatIP` is FAISS's **exact** inner-product index — it compares the query against every
stored vector. No approximation, no training, nothing to tune. At 8,509 vectors that is a
sub-millisecond matrix multiply.

The "IP" is why we normalised: **inner product on unit vectors *is* cosine similarity.**

At millions of vectors you would switch to an approximate index (`IndexIVFFlat`, `IndexHNSW`)
and trade a little recall for a lot of speed. At this size that would be a pure loss —
you would add tuning knobs and lose exactness for no gain.

In [15]:
import faiss

index = faiss.IndexFlatIP(emb.shape[1])
index.add(emb)
print("FAISS index:", index.ntotal, "vectors of dim", emb.shape[1])

FAISS index: 8509 vectors of dim 768
time: 28.6 ms (started: 2026-08-29 18:19:30 +05:30)

---
# Part 5 — Retrieval

```
 P0   P1   P2   P3   P4  [ P5 ]  P6   P7   P8   P9   P10
                          ^^^^
```

Embed the question with the **query-side** prefix, then ask FAISS for the nearest chunks.

In [16]:
query = "Best detective in the world"

q_vec = embed_text(f"task: search result | query: {query}")
D, I = index.search(q_vec.reshape(1, -1), TOPK)

print(f"Top {TOPK} for: {query!r}\n")
for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):
    c = chunks[idx]
    print(f"  #{rank}  {score:.3f}  {c['title']} (chunk {c['chunk_index']})")
    pretty_print("      ", c["preview"][:300])
    print()

Top 5 for: 'Best detective in the world'

  #1  0.413  Adventures of Sherlock Holmes (chunk 63)
       confidence in Mr. Holmes, sir,” said the police agent loftily. “He has
his own little methods, which are, if he won’t mind my saying so, just a little
too theoretical and fantastic, but he has the makings of a detective in him. It
is not too much to say that once or twice, as in that business of the

  #2  0.410  Adventures of Sherlock Holmes (chunk 132)
       corresponds with the injuries. There is no sign of any other weapon.”
“And the murderer?” “Is a tall man, left-handed, limps with the right leg, wears
thick-soled shooting-boots and a grey cloak, smokes Indian cigars, uses a cigar-
holder, and carries a blunt pen-knife in his pocket. There are severa

  #3  0.400  Adventures of Sherlock Holmes (chunk 134)
       a strong presumption that the person whom McCarthy expected to meet him
at Boscombe Pool was someone who had been in Australia.” “What of the rat,
then?” Sherlock Holmes took a folded paper from his pocket and flattened it out
on the table. “This is a map of the Colony of Victoria,” he said. “I wire

  #4  0.393  Adventures of Sherlock Holmes (chunk 109)
       case,” I remarked. “If ever circumstantial evidence pointed to a criminal
it does so here.” “Circumstantial evidence is a very tricky thing,” answered
Holmes thoughtfully. “It may seem to point very straight to one thing, but if
you shift your own point of view a little, you may find it pointing in

  #5  0.392  Adventures of Sherlock Holmes (chunk 135)
       of the criminal.” “But how did you gain them?” “You know my method. It is
founded upon the observation of trifles.” “His height I know that you might
roughly judge from the length of his stride. His boots, too, might be told from
their traces.” “Yes, they were peculiar boots.” “But his lameness?” “T

time: 576 ms (started: 2026-08-29 19:56:50 +05:30)

Sensible: every hit is from *The Adventures of Sherlock Holmes*, and we never told the system
who Sherlock Holmes is or that the books have genres. That is semantic search working.

Now look at the **scores**: they are all around 0.37, and they are all within a few
thousandths of each other. Remember that. It is the subject of Part 7.

---
# Part 6 — Where it breaks

```
 P0   P1   P2   P3   P4   P5  [ P6 ]  P7   P8   P9   P10
                               ^^^^
```

That last query was easy: the answer was a *topic*, and topics are what embeddings are good at.

Here is the question we asked in Part 0, now with a corpus behind it:

> *What was the speckled band?*

Run it and look at the `score` column and the `names_the_answer` column before reading on.

In [ ]:
q_vec = embed_text(f"task: search result | query: {QUESTION}")
D, I = index.search(q_vec.reshape(1, -1), TOPK)

display(pd.DataFrame([{
    "rank":             rank,
    "score":            round(float(score), 3),
    "title":            chunks[idx]["title"],
    "chunk":            chunks[idx]["chunk_index"],
    "names_the_answer": "swamp adder" in chunks[idx]["text"].lower(),
} for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1)]))

# The table says WHICH rank. Read rank 1 in full to see why it is the wrong one.
print("=" * 78)
print("RANK 1 — the best match FAISS could find")
print("=" * 78)
pretty_print(chunks[int(I[0][0])]["text"])

   rank  score                          title  chunk  names_the_answer
0     1  0.337  Adventures of Sherlock Holmes    281             False
1     2  0.304  Adventures of Sherlock Holmes    256             False
2     3  0.298  Adventures of Sherlock Holmes    282              True
3     4  0.292  Adventures of Sherlock Holmes    245             False
4     5  0.286                  War and Peace    259             False

==============================================================================
RANK 1 — the best match FAISS could find
==============================================================================
I have ever listened. It swelled up louder and louder, a hoarse yell of pain and
fear and anger all mingled in the one dreadful shriek. They say that away down
in the village, and even in the distant parsonage, that cry raised the sleepers
from their beds. It struck cold to our hearts, and I stood gazing at Holmes, and
he at me, until the last echoes of it had died away into the silence from which
it rose. “What can it mean?” I gasped. “It means that it is all over,” Holmes
answered. “And perhaps, after all, it is for the best. Take your pistol, and we
will enter Dr. Roylott’s room.” With a grave face he lit the lamp and led the
way down the corridor. Twice he struck at the chamber door without any reply
from within. Then he turned the handle and entered, I at his heels, with the
cocked pistol in my hand. It was a singular sight which met our eyes. On the
table stood a dark-lantern with the shutter half open, throwing a brilliant beam
of light upon the iron safe, the door of which was ajar. Beside this table, on
the wooden chair, sat Dr. Grimesby Roylott clad in a long grey dressing-gown,
his bare ankles protruding beneath, and his feet thrust into red heelless
Turkish slippers. Across his lap lay the short stock with the long lash which we
had noticed during the day. His chin was cocked upward and his eyes were fixed
in a dreadful, rigid stare at the corner of the ceiling. Round his brow he had a
peculiar yellow band, with brownish speckles, which seemed to be bound tightly
round his head. As we entered he made neither sound nor motion. “The band! the
speckled band!”
time: 68.4 ms (started: 2026-08-29 19:56:50 +05:30)

## Read that table again

Two things are wrong here.

**First, the top hit does not contain the answer.** Rank 1 is the climax of the story — the
scream in the night, then Roylott dead in his chair. Read its last few lines, printed under the
table:

> *"Round his brow he had a peculiar yellow band, with brownish speckles, which seemed to be
> bound tightly round his head."*

That is a description of the thing, in the right story, in the right scene, and it reads like an
answer. It is also wrong: what looks like a band of cloth is a snake. The chunk that says so —
the one naming the **swamp adder** — is at rank 3.

Why? Because we asked "what **was** the speckled band?" and embeddings match on topic, not on
the difference between a definition and a description. The scene and the explanation are about
the same thing, so they look alike in vector space.

> **The best-matching chunk and the chunk containing the answer are not the same thing.**

**Second, look at the scores.** The top hit is **0.337** — the lowest top-1 score anywhere in
this notebook (compare 0.66 for the mad tea party). The whole top-5 spans about 0.05.

That is the retriever quietly telling you it is struggling — but only if you already knew what
a good score looks like *for this model, on this corpus, with these prefixes*. On its own the
number means nothing, which is the entire problem with thresholding on it.

In [18]:
# Where is the answer, then? Look at the top hit's immediate neighbours in the book.
top = int(I[0][0])
hit = chunks[top]

print(f"top hit: {hit['title']}, chunk {hit['chunk_index']}\n")
for offset in (-1, 0, +1):
    neighbour = next(
        (c for c in chunks
         if c["source_path"] == hit["source_path"]
         and c["chunk_index"] == hit["chunk_index"] + offset),
        None,
    )
    if neighbour is None:
        continue
    label = "THE HIT" if offset == 0 else f"offset {offset:+d}"
    print(f"  {label:9}  chunk {neighbour['chunk_index']}  "
          f"names_the_answer={'swamp adder' in neighbour['text'].lower()!s}")

# The chunk immediately after the hit is the one that answers the question. Read it.
after = next(c for c in chunks
             if c["source_path"] == hit["source_path"]
             and c["chunk_index"] == hit["chunk_index"] + 1)

print("\n" + "=" * 78)
print(f"CHUNK {after['chunk_index']} — the very next 300 words")
print("=" * 78)
pretty_print(after["text"].replace("swamp adder", ">>> SWAMP ADDER <<<"))

top hit: Adventures of Sherlock Holmes, chunk 281

  offset -1  chunk 280  names_the_answer=False
  THE HIT    chunk 281  names_the_answer=False
  offset +1  chunk 282  names_the_answer=True

==============================================================================
CHUNK 282 — the very next 300 words
==============================================================================
noticed during the day. His chin was cocked upward and his eyes were fixed in a
dreadful, rigid stare at the corner of the ceiling. Round his brow he had a
peculiar yellow band, with brownish speckles, which seemed to be bound tightly
round his head. As we entered he made neither sound nor motion. “The band! the
speckled band!” whispered Holmes. I took a step forward. In an instant his
strange headgear began to move, and there reared itself from among his hair the
squat diamond-shaped head and puffed neck of a loathsome serpent. “It is a >>>
SWAMP ADDER <<<!” cried Holmes; “the deadliest snake in India. He has died
within ten seconds of being bitten. Violence does, in truth, recoil upon the
violent, and the schemer falls into the pit which he digs for another. Let us
thrust this creature back into its den, and we can then remove Miss Stoner to
some place of shelter and let the county police know what has happened.” As he
spoke he drew the dog-whip swiftly from the dead man’s lap, and throwing the
noose round the reptile’s neck he drew it from its horrid perch and, carrying it
at arm’s length, threw it into the iron safe, which he closed upon it. Such are
the true facts of the death of Dr. Grimesby Roylott, of Stoke Moran. It is not
necessary that I should prolong a narrative which has already run to too great a
length by telling how we broke the sad news to the terrified girl, how we
conveyed her by the morning train to the care of her good aunt at Harrow, of how
the slow process of official inquiry came to the conclusion that the doctor met
his fate while indiscreetly playing with a dangerous pet. The
time: 1.98 ms (started: 2026-08-29 19:56:51 +05:30)

There it is.

Both chunks describe the yellow band — chunk 282 opens with the same sentences chunk 281 ends
with, which is the 60-word overlap from Part 3 doing its job. Only chunk 282 keeps going, to
the serpent rearing out of the dead man's hair and Holmes naming it.

The answer was 300 words away the entire time. We just never asked for it.

Notice what the overlap did and did not do. It carried the *description* across the boundary —
that is exactly what overlap is for, protecting a sentence that straddles a split. It did
nothing for the *explanation*, which lives entirely in the next chunk. No overlap size short of
duplicating whole chunks would have fixed this.

That is what the rest of this notebook is about.

---
# Part 7 — Windowed retrieval

```
 P0   P1   P2   P3   P4   P5   P6  [ P7 ]  P8   P9   P10
                                    ^^^^
```

The fix: whenever we retrieve a chunk, also take the chunks **on either side of it in the
original book**.

```
        retrieved by FAISS
               │
    ┌──────────▼──────────┐
    │  161  │  162  │  163  │      <- what we actually send to the LLM
    └───────┴───────┴───────┘
      ±1 neighbours, same book, in reading order
```

To do that in O(1) we need one lookup table from `(book, chunk number)` to a position in
`chunks`. Without it, every neighbour lookup would scan all 8,509 chunks — which is what
the slow loop in the previous cell was doing.

In [19]:
KEY_TO_IDX = {(c["source_path"], c["chunk_index"]): i for i, c in enumerate(chunks)}
print(f"{len(KEY_TO_IDX)} (book, chunk) keys")

8509 (book, chunk) keys
time: 1.49 ms (started: 2026-08-29 18:19:30 +05:30)

In [20]:
def expand_with_neighbors_simple(I, chunks, neighbors=1, max_out=8):
    """
    For each FAISS hit in I[0], emit the hit plus its ±neighbors chunks from the
    same book, in reading order. Deduplicated (two hits can share a neighbour),
    hit order preserved, capped at max_out chunks.

    Returns a flat list — one dict per chunk, so each becomes one numbered,
    citable passage in the prompt.
    """
    seen, contexts = set(), []

    for gi in I[0]:
        c = chunks[int(gi)]
        for delta in range(-neighbors, neighbors + 1):
            j = KEY_TO_IDX.get((c["source_path"], c["chunk_index"] + delta))
            if j is None or j in seen:
                continue
            seen.add(j)
            n = chunks[j]
            contexts.append({
                "title":        n["title"],
                "source_path":  n["source_path"],
                "chunk_index":  n["chunk_index"],
                "text":         n["text"],
                "approx_words": len(n["text"].split()),
                "is_hit":       delta == 0,
            })
            if len(contexts) >= max_out:
                return contexts
    return contexts

time: 498 µs (started: 2026-08-29 18:19:30 +05:30)

## A heuristic we are deliberately *not* keeping

A tempting shortcut is to pick how many hits to expand with a confidence rule:

```python
init_topk = 1 if (top1 >= 0.35 and margin >= 0.05) else min(3, topk)
```

The idea is reasonable — *if the best hit is strong and clearly beats the runner-up, trust it
alone; otherwise cast a wider net.* The next cell measures whether it ever actually fires.

In [21]:
probe_questions = [
    "Why did Mr Darcy's first marriage proposal to Elizabeth fail?",
    "Who ran away with Mr Wickham?",
    "What is the name of Ahab's ship?",
    "What does the Queen of Hearts shout when angry?",
    "Who does Alice meet at the mad tea party?",
    "What was the speckled band?",
    "Where does Sherlock Holmes live?",
    "What creature does Victor Frankenstein create?",
]

rows = []
for q in probe_questions:
    D_, _ = index.search(embed_text(f"task: search result | query: {q}").reshape(1, -1), TOPK)
    top1, top2 = float(D_[0][0]), float(D_[0][1])
    rows.append({
        "question": q[:44],
        "top1":     round(top1, 3),
        "margin":   round(top1 - top2, 4),
        "fires?":   top1 >= 0.35 and (top1 - top2) >= 0.05,
    })

probe = pd.DataFrame(rows)
display(probe)
print(f"\nrule fires on {probe['fires?'].sum()} of {len(probe)} questions; "
      f"mean margin {probe['margin'].mean():.4f} against a 0.05 threshold")

                                       question   top1  margin  fires?
0  Why did Mr Darcy's first marriage proposal t  0.543  0.0007   False
1                 Who ran away with Mr Wickham?  0.462  0.0147   False
2              What is the name of Ahab's ship?  0.562  0.0060   False
3  What does the Queen of Hearts shout when ang  0.453  0.0743    True
4     Who does Alice meet at the mad tea party?  0.662  0.1008    True
5                   What was the speckled band?  0.337  0.0328   False
6              Where does Sherlock Holmes live?  0.568  0.0071   False
7  What creature does Victor Frankenstein creat  0.570  0.0127   False

rule fires on 2 of 8 questions; mean margin 0.0311 against a 0.05 threshold
time: 541 ms (started: 2026-08-29 18:19:30 +05:30)

The rule fires on **2 of 8** questions (mean margin ~0.031 against a 0.05 threshold), and the
two that fire are the two *easy* ones — the mad tea party and the Queen of Hearts, where any
sensible pipeline would have succeeded regardless. On everything hard it silently falls through
to `min(3, topk)`. It reads like adaptive logic and behaves like a hard-coded 3.

Worse, look at which question has the smallest margin of all: the speckled band, at 0.0007.
The rule cannot distinguish "two passages are equally good" from "two passages are equally
useless".

The deeper lesson is about the `0.35` too:

> **Absolute cosine thresholds do not transfer.** They depend on the embedding model, on
> whether you used its task prefixes (Part 1 showed the number moving *down* when we followed
> the model card), and on the corpus. A number tuned on one setup is meaningless on another.

So we delete the heuristic and pass an explicit `topk`. If you later want adaptive retrieval,
build it on something that survives a model swap — the *shape* of the score curve, or a
reranker that actually reads the passages.

In [22]:
def search_windowed(query: str, topk: int = 3, neighbors: int = 1, max_out: int = 12):
    """
    Embed the query -> FAISS top-k -> expand each hit with ±neighbours.
    Returns (df_hits, contexts): the raw hits for you, the contexts for the LLM.
    """
    q_vec = embed_text(f"task: search result | query: {query}")
    D, I = index.search(q_vec.reshape(1, -1), max(topk, TOPK))

    contexts = expand_with_neighbors_simple(
        np.array([I[0][:topk]]), chunks, neighbors=neighbors, max_out=max_out
    )

    df_hits = pd.DataFrame([{
        "rank":        rank,
        "score":       round(float(score), 3),
        "title":       chunks[idx]["title"],
        "chunk_index": chunks[idx]["chunk_index"],
    } for rank, (score, idx) in enumerate(zip(D[0].tolist(), I[0].tolist()), start=1)])

    return df_hits, contexts

time: 387 µs (started: 2026-08-29 19:56:51 +05:30)

In [23]:
df_hits, contexts = search_windowed(QUESTION, topk=3, neighbors=1)

print("=== raw FAISS hits ===")
display(df_hits)

print(f"\n=== expanded context: {len(contexts)} chunks ===")
display(pd.DataFrame([{
    "title":       c["title"],
    "chunk_index": c["chunk_index"],
    "is_hit":      c["is_hit"],
    "words":       c["approx_words"],
    "names_the_answer": "swamp adder" in c["text"].lower(),
} for c in contexts]))

=== raw FAISS hits ===

   rank  score                          title  chunk_index
0     1  0.337  Adventures of Sherlock Holmes          281
1     2  0.304  Adventures of Sherlock Holmes          256
2     3  0.298  Adventures of Sherlock Holmes          282
3     4  0.292  Adventures of Sherlock Holmes          245
4     5  0.286                  War and Peace          259

=== expanded context: 7 chunks ===

                           title  chunk_index  is_hit  words  names_the_answer
0  Adventures of Sherlock Holmes          280   False    300             False
1  Adventures of Sherlock Holmes          281    True    300             False
2  Adventures of Sherlock Holmes          282   False    300              True
3  Adventures of Sherlock Holmes          255   False    300             False
4  Adventures of Sherlock Holmes          256    True    300             False
5  Adventures of Sherlock Holmes          257   False    300             False
6  Adventures of Sherlock Holmes          283   False    300             False

time: 65.2 ms (started: 2026-08-29 19:56:51 +05:30)

Three hits became seven chunks — fewer than nine, because neighbouring windows overlap and
the duplicates are dropped. Chunk 282 is in the context, so **the swamp adder is finally in
front of the model**.

One column is worth a second look. `is_hit` reads `False` for chunk 282 — but chunk 282 is
**rank 3** in the table right above it. The window got there first: chunk 282 was emitted as
chunk 281's `+1` neighbour, and the dedup kept that first copy. So `is_hit` records *how a
chunk entered the context*, not whether it was also a hit in its own right.

At `topk=1` the distinction collapses and the window does all of the work — rank 3 is never
sent at all, and chunk 282 arrives purely because it sits next to rank 1. That is the
configuration Part 8 opens with.

Whether the model *uses* it is a separate question — which is Part 8.

---
# Part 8 — Generation: the "G" in RAG

```
 P0   P1   P2   P3   P4   P5   P6   P7  [ P8 ]  P9   P10
                                         ^^^^
```

Everything so far was **retrieval**. Now we hand the passages to a model and ask for an
answer that cites them.

Three rules in the prompt, and each one is doing a job:

1. **"Use ONLY the passages"** — the difference between answering *from the corpus* and
   answering from training data. Without it you cannot tell which one you got.
2. **"Cite the passage number"** — makes the answer checkable.
3. **"Say so if the passages don't answer it"** — gives the model an exit that is not
   making something up.

We number the passages and label each with its book and chunk number, so the model can see
which ones are adjacent.

In [24]:
def answer(question: str, contexts: list, model: str = GEN_MODEL, **kw) -> str:
    """Ask `model` to answer `question` using only `contexts`, with citations."""
    block = "\n\n".join(
        f"[{i}] ({c['title']}, chunk {c['chunk_index']})\n{c['text']}"
        for i, c in enumerate(contexts, start=1)
    )
    resp = client.chat(
        model=model,
        messages=[{"role": "user", "content":
            "Answer the question using ONLY the passages below. Cite the passage numbers "
            "you used, like [2].\n"
            "The passages are excerpts from novels, so the speaker of a line may be named "
            "in a neighbouring passage rather than the one containing the line — read them "
            "together before deciding who is speaking.\n"
            "If the passages genuinely do not answer the question, say so and state what "
            "they do show instead.\n\n"
            f"{block}\n\nQuestion: {question}\nAnswer:"
        }],
        options={"temperature": 0.0, "num_predict": 250},
        **kw,
    )
    return resp["message"]["content"].strip()

time: 438 µs (started: 2026-08-29 18:19:31 +05:30)

### Panel A — the top hit alone, no window

This is the naive pipeline: retrieve the single best chunk, hand it over.

In [25]:
_, ctx_a = search_windowed(QUESTION, topk=1, neighbors=0)
print(f"context: {len(ctx_a)} chunk, {sum(c['approx_words'] for c in ctx_a)} words\n")
pretty_print(answer(QUESTION, ctx_a))

context: 1 chunk, 300 words

The passage does not explicitly describe what the speckled band is, but it does
mention that it is a "peculiar yellow band, with brownish speckles" that is
bound tightly around Dr. Roylott's head [1].
time: 3.75 s (started: 2026-08-29 18:19:31 +05:30)

**Look at what just happened.**

The model answered that the speckled band was a *yellow band with brownish speckles bound
around Dr Roylott's head* — **and it cited a passage**. The citation is real. The passage
exists. The quote is accurate.

And the answer is wrong. The speckled band is a **snake**. What the model described is the
snake coiled in a dead man's hair, which the passage describes without ever explaining.
It has confidently reported a murder weapon as an item of clothing.

> **A citation proves a passage was used. It does not prove the passage contained the answer.**

This is what makes bad RAG dangerous rather than merely useless: it does not look like a
failure. There is a real quote, a real source, and a fluent answer. Nothing in the output
flags it.

### Panel B — the same hit, with its neighbours

In [26]:
_, ctx_b = search_windowed(QUESTION, topk=1, neighbors=1)
print(f"context: {len(ctx_b)} chunks, {sum(c['approx_words'] for c in ctx_b)} words\n")
pretty_print(answer(QUESTION, ctx_b))

context: 3 chunks, 900 words

The speckled band was a yellow band with brownish speckles, bound tightly around
Dr. Roylott's head, which was actually a loathsome swamp adder, the deadliest
snake in India, that had been hidden in his hair. [3]
time: 2.71 s (started: 2026-08-29 18:19:35 +05:30)

**Same retriever. Same model. Same question. Same top hit.**

The only change was ±1 chunk of context — and the answer went from an item of clothing to
*"a loathsome swamp adder, the deadliest snake in India"*.

This is the whole argument for windowed retrieval in one cell. The retriever was never really
broken: it found the right *neighbourhood* on its very first try. It just handed over the
wrong 300 words of it.

### Panel C — more hits, still windowed

Panel B worked. So more context should work even better, right? Let's take top-3 hits with
±1 neighbours — seven chunks instead of three.

In [27]:
_, ctx_c = search_windowed(QUESTION, topk=3, neighbors=1)
print(f"context: {len(ctx_c)} chunks, {sum(c['approx_words'] for c in ctx_c)} words\n")
pretty_print(answer(QUESTION, ctx_c))

context: 7 chunks, 2100 words

The passages do not explicitly state what the "speckled band" is. However, based
on the context and the reactions of the characters, it can be inferred that the
"speckled band" refers to a snake, specifically a swamp adder, which is
mentioned in passage [3]. The characters' horror and loathing at the sight of
the snake, as well as the fact that it is described as the "deadliest snake in
India", suggest that the "speckled band" is a snake.  Passage [2] mentions the
"band" and the "speckled band" in the same context, and Holmes' reaction to
seeing the snake is to exclaim "The band! the speckled band!" This suggests that
the "band" refers to the snake's markings or pattern, which is described as a
"peculiar yellow band, with brownish speckles".  Therefore, while the passages
do not explicitly state what the "speckled band" is, the context and the
reactions of the characters suggest that it is a snake, specifically a swamp
adder.
time: 6.4 s (started: 2026-08-29 18:19:37 +05:30)

**More context made the answer worse.**

Panel C hedges — "the passages do not explicitly state… it can be inferred" — even though it
is looking at strictly more information than Panel B, including the exact chunk that names the
adder. The four extra chunks are all *about* the speckled band without defining it, and they
dilute the one chunk that matters.

> **Context is not free. Padding the prompt with plausible-but-unhelpful passages measurably
> degrades the answer.** This is why Part 9 measures instead of assuming.

### Panel D — same context, different model

The right passage **is** in `ctx_c` — we put it there, and Panel B proves the model can use it.
So Panel C is no longer a retrieval problem, and no amount of retriever tuning will fix it.

Let's hold the context fixed and change only the generator.

In [28]:
# think=False is mandatory for reasoning models on Ollama. Without it, qwen3.5 and
# gpt-oss spend the entire num_predict budget on hidden reasoning tokens and return
# an EMPTY string — measured 16.3s of nothing at num_predict=220.
pretty_print("qwen3.5:9b →", answer(QUESTION, ctx_c, model="qwen3.5:9b", think=False))

qwen3.5:9b → The speckled band was a swamp adder, which is described as "the
deadliest snake in India." [3]
time: 11.4 s (started: 2026-08-29 18:19:44 +05:30)

Same passages, same prompt — and a crisp, correct, cited answer where `llama3.1:8b` hedged.

That is the lesson of Part 8, and it is easy to get backwards:

| symptom | actual stage at fault |
|---|---|
| right passage never appears in context | **retriever** — chunking, top-k, window |
| right passage is in context, answer still wrong or hedged | **generator** — model, prompt |

Before tuning a retriever, always check whether the answer was already in the context.
Half the time you are debugging the wrong half of the system.

**On model choice.** `llama3.1:8b` is the default because it is a reasonable, widely-available
8B model and it fails in instructive ways. `qwen3.5:9b` with `think=False` is measurably better
at extracting a specific fact from a noisy context. `GEN_MODEL` at the top is one line — change
it and re-run the panels.

### Back to where we started

Part 0 asked this same question with no retrieval at all. Scroll up and compare that answer
with Panel D's.

The un-retrieved answer may well have been *correct* — the story is famous enough to be
memorised in the weights. That is exactly the trap. You had no way to tell the difference
between the model knowing and the model guessing, because there was nothing attached to it.

Panel D's answer points at a chunk you can open and read.

**RAG's product is not correctness. It is checkability.**

---
# Part 9 — Measure it, don't trust it

```
 P0   P1   P2   P3   P4   P5   P6   P7   P8  [ P9 ]  P10
                                              ^^^^
```

We have been eyeballing single queries. That is how you build a demo, not a system.

The cheapest useful evaluation: a handful of questions where you know the answer, plus a
string that **must** appear in the retrieved context for the answer to be derivable at all.

This measures **context recall** — did retrieval put the necessary evidence in front of the
model? It deliberately does not grade the model's prose. It isolates the retriever, which is
what we are tuning.

Twelve questions is not a benchmark. It is enough to stop you shipping a regression, and you
can write it in ten minutes.

In [29]:
GOLD = [
    ("Why did Mr Darcy's first marriage proposal to Elizabeth fail?", "Pride and Prejudice",           "gentlemanlike"),
    ("Who ran away with Mr Wickham?",                                 "Pride and Prejudice",           "Lydia"),
    ("What does Captain Ahab nail to the mast as a reward?",          "Moby-Dick",                     "doubloon"),
    ("What is the name of Ahab's ship?",                              "Moby-Dick",                     "Pequod"),
    ("What does the Queen of Hearts shout when angry?",               "Alice in Wonderland",           "off with"),
    ("Who does Alice meet at the mad tea party?",                     "Alice in Wonderland",           "Hatter"),
    ("What was the speckled band?",                                   "Adventures of Sherlock Holmes",  "swamp adder"),
    ("Where does Sherlock Holmes live?",                              "Adventures of Sherlock Holmes",  "Baker Street"),
    ("What creature does Victor Frankenstein create?",                "Frankenstein",                  "creature"),
    ("Who is the vampire hunter that pursues Dracula?",               "Dracula",                       "Van Helsing"),
    ("What does Sydney Carton do at the end?",                        "A Tale of Two Cities",          "far, far better"),
    ("What keeps Dorian Gray from ageing?",                           "The Picture of Dorian Gray",    "portrait"),
]

# Embed each gold question once and reuse across the whole sweep.
gold_hits = {
    q: index.search(embed_text(f"task: search result | query: {q}").reshape(1, -1), 5)
    for q, _, _ in GOLD
}
print(f"{len(GOLD)} gold questions embedded")

12 gold questions embedded
time: 720 ms (started: 2026-08-29 18:19:55 +05:30)

In [30]:
rows = []
for topk in (1, 3, 5):
    for neighbors in (0, 1, 2):
        found, sizes = 0, []
        for question, book, must_contain in GOLD:
            D_, I_ = gold_hits[question]
            ctx = expand_with_neighbors_simple(
                np.array([I_[0][:topk]]), chunks, neighbors=neighbors, max_out=100
            )
            sizes.append(len(ctx))
            found += any(must_contain.lower() in c["text"].lower() for c in ctx)
        rows.append({
            "top_k":        topk,
            "neighbors":    neighbors,
            "recall":       f"{found}/{len(GOLD)}",
            "avg_chunks":   round(np.mean(sizes), 1),
            "avg_words":    int(np.mean(sizes) * WORDS_PER_CHUNK),
        })

pd.DataFrame(rows).pivot(index="top_k", columns="neighbors", values=["recall", "avg_chunks"])

          recall             avg_chunks
neighbors      0     1     2          0     1     2
top_k
1           6/12  8/12  8/12        1.0   3.0   5.0
3           9/12  9/12  9/12        3.0   8.3  13.7
5           9/12  9/12  9/12        5.0  13.3  21.3

time: 17 ms (started: 2026-08-29 18:19:56 +05:30)

## Reading the table

Measured on this corpus (your run should reproduce this):

| top-k | ±0 | ±1 | ±2 |
|---|---|---|---|
| **1** | 6/12  (1.0 chunks) | **8/12**  (3.0) | 8/12  (5.0) |
| **3** | 9/12  (3.0) | 9/12  (8.3) | 9/12  (13.7) |
| **5** | 9/12  (5.0) | 9/12  (13.3) | 9/12  (21.3) |

Three results worth more than any single demo:

**1. Neighbours matter most when you retrieve least.** At top-1 the window takes you from
6/12 to 8/12 — the speckled band is one of those two, so Part 6 was not a lucky anecdote.
By top-3 the window adds nothing at all.

**2. More hits beat wider windows.** Going 1→3 on `top_k` buys 3 questions. Going ±0→±1 on a
single hit buys 2, and costs the same 3 chunks. If you have a fixed context budget,
**spend it on more hits before you spend it on wider windows.**

**3. ±2 is never worth it.** It never beat ±1 on any row, and it costs 60% more context.

That last one is why you measure. "More context is better" sounds obviously true, and on this
corpus it is false past ±1 — you would have paid for it in latency and tokens forever without
ever noticing. Panel C is the same finding in prose: the extra chunks made the answer *worse*.

## And the three it never finds

Three questions fail at *every* setting: **Ahab's doubloon**, **Baker Street**, and
**Sydney Carton's last line**. Those are not window problems — the right chunk never enters
the top 5 at all, so no amount of expansion can rescue them.

All three are the same shape: a question whose answer hinges on a rare proper noun or an exact
phrase. Dense embeddings compress exactly that kind of detail away.

The standard fixes are **BM25 keyword search fused with dense retrieval**, and a
**cross-encoder reranker** over a wider candidate set. Both are the natural next step —
and now you have a gold set to prove whether they helped.

---
# Part 10 — Ship it

```
 P0   P1   P2   P3   P4   P5   P6   P7   P8   P9  [ P10 ]
                                                   ^^^^^
```

Nobody is going to run a notebook to ask a question. We save the expensive artifacts to disk
and serve them from a small Flask app, so startup is a file read instead of a 6-minute rebuild.

In [31]:
import json

Path(ARTIFACTS_DIR).mkdir(parents=True, exist_ok=True)

with open(Path(ARTIFACTS_DIR) / "chunks.json", "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False)

np.save(Path(ARTIFACTS_DIR) / "embeddings.npy", emb)
faiss.write_index(index, str(Path(ARTIFACTS_DIR) / "faiss_index.bin"))

with open(Path(ARTIFACTS_DIR) / "config.json", "w") as f:
    json.dump({
        "EMBED_MODEL":     EMBED_MODEL,
        "GEN_MODEL":       GEN_MODEL,
        "WORDS_PER_CHUNK": WORDS_PER_CHUNK,
        "OVERLAP_WORDS":   OVERLAP_WORDS,
        "TOPK":            TOPK,
    }, f, indent=2)

for f in sorted(Path(ARTIFACTS_DIR).iterdir()):
    print(f"  {f.name:20} {f.stat().st_size/1e6:8.2f} MB")

  chunks.json             19.30 MB
  config.json              0.00 MB
  embeddings.npy          26.14 MB
  faiss_index.bin         26.14 MB
time: 131 ms (started: 2026-08-29 18:19:56 +05:30)

## The web app

The app lives beside this notebook as two ordinary files, not inside it:

| file | what it is |
|---|---|
| `v3_hello_rag.py` | Flask server — loads `rag_artifacts/`, serves `/` and `/ask` |
| `templates/v3_index.html` | the page — verdict line, rank table, context cards, prompt viewer |

Open them in your editor alongside this notebook. There is nothing in either file you have not
already built here: `embed_text`, `expand_with_neighbors_simple` and `search_windowed` are
copied across **unchanged**, and `/ask` assembles exactly the prompt from Part 8.

Keeping them identical is deliberate. If the app carried its own slightly different copy of
`expand_with_neighbors_simple`, the app and this notebook could quietly disagree about what
"context" means, and every number here would stop describing what the app actually does.

The page adds one control the notebook does not have: a **highlight** box. Type a phrase —
`swamp adder` — and every retrieved chunk is searched for it, case-insensitively. Matches are
highlighted and counted, so you can see which rank holds the answer, which ranks were cut by
top-k, and whether the phrase reached the model at all.

It is a measurement, not a constraint. The phrase never enters the prompt and never touches
retrieval; it is the same after-the-fact substring check as `must_contain` in Part 9.

## Running it

The cell above wrote `rag_artifacts/`, which is everything the app needs. Start it from a
terminal — not from this notebook, since it blocks until you stop it:

```bash
python v3_hello_rag.py
```

Then open <http://localhost:5001>.

The page shows **the answer, the passages it cites, and the exact prompt that produced it**,
all on one screen. The "show the exact prompt" toggle is the point: it is where RAG stops
being magic and becomes string concatenation into a context window.

### What to demo, in order

1. Ask *"What was the speckled band?"* with highlight `swamp adder`, **top-k = 1,
   neighbours = 0**. The answer comes back confident and wrong — a band around a man's head —
   and the verdict reads *the model never saw it*: rank 1 does not contain the phrase, and
   top-k = 1 cut the rank that does.
2. Change **neighbours to 1** and ask again. It becomes a snake, and the verdict flips to *the
   model saw it — but no hit it sent contained it*. A neighbouring chunk carried it. Nothing
   else changed.
3. Set **top-k = 3**. The same passage is now tagged **rank 3** instead of "neighbour" — it
   arrives on its own merit — and the greyed "cut by top-k" rows show what the narrower
   setting had been throwing away.
4. Open **"Show the exact prompt"**. This is where RAG stops being magic: it is a string with
   some retrieved text pasted into it.
5. Untick **"generate an answer"** to get retrieval-only latency, and compare.

---

# What we built

```
question ─▶ embed ─▶ FAISS top-k ─▶ ±neighbour window ─▶ prompt ─▶ answer + citations
```

Every piece is replaceable, and now you can measure whether a replacement helped.

### The five things worth remembering

1. **The best-matching chunk is not the chunk with the answer.** Embeddings rank by topic, and
   the most dramatic passage about a thing routinely outranks the one that explains it.
2. **A citation is not a correctness check.** Panel A quoted a real passage, accurately, and
   still called a snake an item of clothing.
3. **Absolute similarity thresholds do not transfer** across models, prefixes, or corpora.
   0.337 was a bad score here and would be a fine score elsewhere.
4. **More context is not free.** Panel C got worse than Panel B by adding four chunks.
5. **Diagnose the right stage.** If the answer was already in the context, the retriever is
   not your problem.
6. **Twelve gold questions** told us ±2 neighbours is never worth it. Eyeballing never would.

### Where to go next

- **Hybrid retrieval** — BM25 + dense, fused with RRF. Fixes the proper-noun misses in Part 9.
- **Reranking** — retrieve 50, let a cross-encoder pick 5.
- **Better chunking** — split on sentence and paragraph boundaries instead of a word count.